### ISSUE TITLE
Sidebar option grandchild pages

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#100]
@kpettinga I'm noticing a lot of pages still have the [child_pages] shortcode which, as you mentioned, will be swapped out in favor of a sidebar. Posting here as a reminder

**Comment by kpettinga** [comment]
@Jessdwilson this should be all set.

There is now a Page with Sidebar template available for use. I've gone ahead and assigned it to the Resources & Support page and all its children. Refer to those pages for examples on selecting sidebar options.
