### ISSUE TITLE
Gotham appearance in Safari

### ISSUE THREAD

**Issue by jalbertgagnier** [ObjectiveSubject/cgu#102]
Looks like Gotham bold shows as a 'faux-bold' in Safari.

![safari-chrome](https://cloud.githubusercontent.com/assets/1825143/18997627/4aa10678-8703-11e6-9dcf-d489600461c1.png)

**Comment by jalbertgagnier** [comment]
Safari seems to be very peculiar with Gotham!
![extrabold](https://cloud.githubusercontent.com/assets/1825143/20349432/6e60886e-abd8-11e6-9ceb-bc75747fe752.png)

**Comment by holliscooper-cgu** [comment]
I need to check cloud typography and make sure we haven't hit our bandwidth cap for a development site - Gotham stopped rendering some time last night. If so, we'll get the font files moved and into production this morning.

**Comment by davekellam** [comment]
Is this still happening? As I mentioned in #259, there was a debug flag turned on for some reason. So it would have been using the version of Gotham off your computer, rather than the typography.com one, which may have created some sort of faux bold on bold situation.

**Comment by kpettinga** [comment]
@holliscooper-cgu @davekellam @jalbertgagnier this was my fault. I needed debug mode turned on for the wpengine site while I was testing in IE. Forgot to turn it off. It's all set now.

@davekellam thanks for turning it off!
