### ISSUE TITLE
Admissions info pushed to Program pages

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#106]
@kpettinga the Cost & Aid information for programs on the **Admissions** pages should be pushed to the Cost & Aid pages of **Program** pages so that the CGU team doesn't need to enter this info twice. 

See attached screenshot of our original designs for the Admissions Cost & Aid section, we have a section for Tuitions and Fees under Admission Info 

![os admissions mockup](https://cloud.githubusercontent.com/assets/1680051/19084250/ca2c86c8-8a33-11e6-911c-f9d011c06f36.png)
![wp admission info](https://cloud.githubusercontent.com/assets/1680051/19084252/cbdf732c-8a33-11e6-9d1b-00c16212b819.png)

**Comment by kpettinga** [comment]
hey @Jessdwilson 

I've implemented a new `[content]` shortcode to help handle this. It lets you grab content from another post and put it on a page of your choice. You just need to specify the post ID which can always be found in the url of the post you're editing.
For instance in this URL: _http://cgu.wpengine.com/wp-admin/post.php?post=5044&action=edit_
**5044** is the post ID. This is the same number that will be found in the Admission info fields when editing the top-level Programs.

Here's an example of using the shortcode.
`[content post="5044" span="8"]`
This will grab the content from the "Positive Psych - Cost & Aid" admissions post which has an ID of 5044.

`span="8"` is an optional part that lets you specify the width of the content.
