### ISSUE TITLE
Takeover Nav: add more space between "Campus life" and the button

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/cgu#111]
@kpettinga I've noticed the school logo should have the Claremont Graduate University lockup, exactly like the main nav.

Also can the rollovers on the links be CGU Red?

Here's a screen shot of the page.

![image](https://cloud.githubusercontent.com/assets/12611145/19314956/f7e64694-9069-11e6-8cc2-90b20c2176d8.png)

**Comment by elliotarthur** [comment]
@kpettinga Could we add more space between "Campus life" and the button please.

![image](https://cloud.githubusercontent.com/assets/12611145/20224801/557f8656-a80e-11e6-9312-70731b7e99fb.png)

**Comment by Jessdwilson** [comment]
@kpettinga in addition to the spacing of the links, the client has also requested that we order the schools to be the same order they are on the schools landing page

**Comment by holliscooper-cgu** [comment]
@kpettinga The spacing of the Request Info button on the design site looks fine. We would like the re-ordering of the schools:
- School of Social Science, Policy & Evaluation
- Drucker School of Management
- School of Arts & Humanities
- School of Community & Global Health
- School of Educational Studies
- Center for Information Systems & Technology
- Institute of Mathematical Sciences

We may have two of these merging in the future (CISAT and IMS), so if there's a way we can control this order on our end, that would be great.

**Comment by Jessdwilson** [comment]
@holliscooper-cgu the order of schools in the hamburger menu has been updated, this can be edited by going to the School post > Quick Edit > Order
