### ISSUE TITLE
Homepage: Scrim for the copy on the History Module

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/cgu#113]
@kpettinga Could we include a black scrim about 50/60% transparency.

Screenshot of page.
![image](https://cloud.githubusercontent.com/assets/12611145/19317171/27ddbe24-9072-11e6-9892-4035b58da50f.png)

**Comment by holliscooper-cgu** [comment]
@kpettinga @Jessdwilson I'm going to close this issue based on our conversation last week where we discussed having scrim transparency options that we could choose from. I'll create a new issue for scrims across the site.
