### ISSUE TITLE
Programs: Sidebar - lines appearing

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/cgu#116]
@kpettinga On the program breakdown sidebar (blue sidebar), we're not using lines to break apart each section here only spacing. Can you remove please? Screen shot to show you what I'm talking about.

![image](https://cloud.githubusercontent.com/assets/12611145/19318321/3de85e1e-9076-11e6-9863-faf1078cbb8c.png)

**Comment by kpettinga** [comment]
@elliotarthur this is a content entry issue. The client is entering content like this.
