### ISSUE TITLE
Programs: module spacing on pages

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/cgu#118]
INTERDISCIPLINARY CONCENTRATIONS module could do with more spacing between the bottom of the button and the top of the next Studies header. Visually, I think they need more space to help let each section breath and not feel too close to the other study.

Re-looking at the screen shot the space above Media studies should follow all the other studies.

![cgu programs page](https://cloud.githubusercontent.com/assets/12611145/19318749/e4fd5b7c-9077-11e6-9bcf-9edd7ce81c6e.png)

**Comment by kpettinga** [comment]
@elliotarthur this is a content entry issue. More space needs to be given in the WYSIWYG editor.
