### ISSUE TITLE
404 errors on API endpoints

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/cgu#12]

**Comment by kpettinga** [comment]
Hey @davekellam, could you help me out with a bug here?

I've registered a new endpoint to handle getting 'people' posts on the faculty templates. I've flushed the rewrite rules and tried it out in Postman and everything is working fine. But for whatever reason if I try to make a `$.get()` request with it always returns a 404. I can't figure out why it would work in Postman but not the browser. 

For now, in the interest of making it look good to the client for the meeting, ive reverted the faculty template back to just displaying a list of the people pertaining to the current school. The filters don't do anything.

**Comment by davekellam** [comment]
This has been a super-bizarre one to track down, getting close, but not quite there.

Eventually, I realized that despite both programs and people returning data, they weren't getting the same http headers.

![screen shot 2016-05-02 at 1 17 39 pm](https://cloud.githubusercontent.com/assets/60804/14967130/d498bcbe-1083-11e6-8b82-042f76d63740.png)

For some reason, people was returning a 404. I tracked it down to the internal state of WordPress (`$wp_query`) before we even start to try and modify it. First screenshot shows programs, which seems to have something equivalent to the default query. Second shows what state $wp_query is at, which seems to be trying to query people, and also has a weird `AND (0 = 1)` bit, which I'm pretty sure would cause it to return no results. It's possible that it's related to querying across multiple taxonomies.

![screen shot 2016-05-02 at 3 52 29 pm](https://cloud.githubusercontent.com/assets/60804/14967197/298f03fe-1084-11e6-870c-7376f6b17754.png)
![screen shot 2016-05-02 at 3 52 36 pm](https://cloud.githubusercontent.com/assets/60804/14967198/2990335a-1084-11e6-8fc8-bc1a5ca3dc97.png)

There might be some conflict between the functions for programs/people, but it seemed to 404 when I took away the programs too. So, I'm guessing a combination of the tax_query and potentially some conflict. I'm not sure if _programs_ should even be working in the first place, might have been a bug that accidentally worked 😄 . I'll set about reworking how the api functions internally, imagine we can probably keep the endpoints the same or similar (I might add a v1 in at the front).

**Comment by davekellam** [comment]
Here's a hack that should allow you to make use of the data... 

If you put `status_header( 200 )` ahead of `wp_send_json( $data )`, it will prevent the 404. That said, it doesn't technically solve the problem of there being underlying flaws in the api construction. The rest of the headers means that we won't get caching, which is sort of the whole point of custom api endpoints rather than running everything through admin-ajax.

I still think this probably needs a bit of a rewrite to deal with the different data types.

@kpettinga do you have enough stuff that doesn't involve the api to keep working? I imagine the endpoints can stay similar, but we probably want to avoid a messy merge.

**Comment by davekellam** [comment]
I rewrote this today, thinking I'd solve the problem... but it just seems to have allowed me to reveal more weirdness.

If you remove the rewrite, and take a look at the url that it's redirecting to, programs should end up here:  `index.php?schools=all_schools&areas-of-study=all_areas_of_study&degree-types=all_degrees&api-call=programs` and people should take you here `index.php?schools=all_schools&roles=all_roles&expertise=all_expertise&api-call=people`. Therein lies some of the weirdness...

If you visit those urls, the programs one will return you the main page, with no json data, but a 200 ok. Visiting the people url, you actually get json data, but get a 404 not found. It's sort of bizarre. So, both requests are sort of working, but no working... not sure which one is technically wrong at the moment.

Probably need to walk away for the time being, as it's technically "working", but we'll want to revisit before going live, as the people requests won't be getting cached properly.

**Comment by davekellam** [comment]
I'm going to close this out for now. We'll see if there are any sort of issues when it hits testing (as far as caching goes). Can always reopne later.
