### ISSUE TITLE
All-Cap text in paragraphs

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/cgu#123]
@kpettinga I've noticed we're using some All Cap text within drawers and paragraphs which is using Gotham Narrow, rather than Gotham. Here's an example which I've found on the Amitted Students page. If you see the dates JULY 16 – SUMMER MIXER & AUGUST 25 – NEW STUDENT ORIENTATION under Step 3.

![image](https://cloud.githubusercontent.com/assets/12611145/19328801/726bc298-90a3-11e6-931f-921c35ecedfc.png)

**Comment by kpettinga** [comment]
@elliotarthur also a content entry issue. We may want to make the client aware of these.
