### ISSUE TITLE
Home: History module

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/cgu#126]
@kpettinga on the history module, I can swipe using my mouse much like a tablet, yet the dates and arrows don't follow and remain on the last date I clicked via the timeline.

This is using Chrome. Notice the arrow is 1998 and the image is 2001

![image](https://cloud.githubusercontent.com/assets/12611145/19366578/b2b74d3c-9165-11e6-821f-65e4aefccf4d.png)

**Comment by kpettinga** [comment]
@elliotarthur i can't seem to replicate this. can you clear your browser cache and check again? If it persists, describe to me the exact steps you take before seeing the issue.

**Comment by Jessdwilson** [comment]
@kpettinga I'm noticing the same issue if I click on the photo and drag it from left to right or right to left the year in the timeline at the top sticks at 1925 and doesn't adjust based on the photo I drag to. This is happening in Chrome and Safari.

**Comment by holliscooper-cgu** [comment]
Module is displaying weirdly in mobile view (attached image is from Andrea's iphone). 
![v__63f4](https://cloud.githubusercontent.com/assets/18012084/20033975/efbd0d1c-a36b-11e6-8a08-698b650da539.jpg)

**Comment by kpettinga** [comment]
@elliotarthur @Jessdwilson 
I still can't replicate the issue you're talking about. I've followed the steps you said. It always works. 

@holliscooper-cgu 
This was probably a random case of some javascript not loading completely. Shouldn't happen again.

**Comment by elliotarthur** [comment]
@kpettinga @Jessdwilson. I can't replicate that issue anymore. Must had been fixed throughout the process.
