### ISSUE TITLE
Timeline module in Safari

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#127]
@kpettinga Hollis provided the attached screenshot. I think she just needs to clear her browser cache to fix the issue with the images straddling

Not sure why the year is off center, they may not include the years on the photos but it should be adjusted so it aligns with the content below. 

I spoke with Elliot about the use of mercury and he suggested that it remain as it provides a hint of the history/institutional side of CGU. They may fight this so TBD

![timeline-formatting-safari](https://cloud.githubusercontent.com/assets/1680051/19367102/c2d9e204-9167-11e6-8fc1-4dce7912f557.png)

**Comment by kpettinga** [comment]
@Jessdwilson yes she should clear her browser cache to fix that issue. Going to close this issue for now. Feel free to re-open if the client has more requests.
