### ISSUE TITLE
Homepage Claremont feature carousel

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#128]
@kpettinga 

Claremont "feature" is supposed to have more than one option that loads randomly on page load. 

Options can be seen in original mockup set - 'Claremont, the city of trees and PhDs', 'What's an intimate atmosphere?', 'The graduate university of the Claremont Colleges', and Tawni Cranz picture/quote 

![screen shot 2016-10-13 at 5 20 03 pm](https://cloud.githubusercontent.com/assets/1680051/19367462/52a3dc04-9169-11e6-9b85-cdf03cf2aa85.png)

**Comment by kpettinga** [comment]
@Jessdwilson i wasn't aware this is what the design was trying to show. @elliotarthur in the future, if you could make sure to add notes to the illustrator document about functionality that isn't obvious in the design, that would be helpful.

**Comment by kpettinga** [comment]
@Jessdwilson I've refactored this a bit so that you can select a series of modules and on each page load, a random one gets selected. All of the designs shown above can be accomplished with the "image" module type. See the Home Options metabox to select the modules.

**Comment by elliotarthur** [comment]
@kpettinga Sorry for not noting this in the design file.
