### ISSUE TITLE
Homepage hero slider

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#129]
@kpettinga 

On the homepage the top hero image should be a slider.

![screen shot 2016-10-13 at 5 22 00 pm](https://cloud.githubusercontent.com/assets/1680051/19367522/96646de6-9169-11e6-9542-8468f94f5ea3.png)

**Comment by kpettinga** [comment]
@Jessdwilson @holliscooper-cgu, there are now options to add carousels to the home page header and school page headers.

**Comment by holliscooper-cgu** [comment]
@Jessdwilson @kpettinga Can the image header carousels span the width of the browser window, as the image does now on the CGU homepage, and as the carousel does now on Drucker's homepage? http://drucker.cgu.edu/

**Comment by kpettinga** [comment]
@holliscooper-cgu this should be all set.
