### ISSUE TITLE
Program pages adjust placement of modules

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#132]
@kpettinga 

Need to be able to choose location of modules deployed on page.

We would like to control the placement of modules on the program pages. For example, the 6 interdisciplinary concentrations that now apply to 12 different degree programs have been deployed as a module on the page. We would like for this particular module to appear under the Intro, and before "Courses You Might Take." See: http://cgu.wpengine.com/academics/program/ma-english/

**Comment by kpettinga** [comment]
@Jessdwilson @holliscooper-cgu

If we wanted to create the ability to place modules *anywhere* within the content for programs, we would need to make *all* the content blocks into modules, which would be a lot of work. 

So I've created an "Upper Modules" field on Programs which will allow you to place modules directly after the intro and before the other program content elements.

Feel free to re-open this issue if further changes are needed.
