### ISSUE TITLE
Academics page: Link rollover color

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/cgu#133]
@kpettinga I think we should have the areas of study and degree links in a lighter green color like on the homepage AoS column. Currently, it might not comply with 508.

However, I've noticed the hover color on the home page is a saturated green which isn't in the color palette. Can links which are in these green modules be #00A7CE. I believe these are the same as the events hover.

![image](https://cloud.githubusercontent.com/assets/12611145/19367752/740366f2-916a-11e6-8a84-04024c27b97e.png)

**Comment by kpettinga** [comment]
@elliotarthur, the hover colors of sections with a background color are automatically generated based on the background's color. Unless otherwise specified, links become a darkened or lightened version of the background color. 

For blue and dark teal backgrounds I've specified the hover color to be light blue (#00A7CE).

If you have other specifications for what hover state colors should be, I can implement them.

**Comment by elliotarthur** [comment]
Thanks, Kirk. That's awesome we can custom the links to the background color.

**Comment by elliotarthur** [comment]
@kpettinga I've noticed all the modules which are titled Research Centers and Affiliates or use the yellow backgrounds. The link color might need to be changed as the current yellow is rather hard to see. I suggest the orange from the color palette #EC981A. 

![image](https://cloud.githubusercontent.com/assets/12611145/19395074/c16ba46e-9209-11e6-924b-eb971cbb5296.png)


![image](https://cloud.githubusercontent.com/assets/12611145/19394898/13a2acd8-9209-11e6-8b8f-8ef1620e0c48.png)

**Comment by Jessdwilson** [comment]
@elliotarthur on the CGU design site the section colors have changed, see attached screenshot. The text static state is red and the hover state is black, perhaps this should be the opposite? 

![screen shot 2016-11-30 at 6 22 20 pm](https://cloud.githubusercontent.com/assets/1680051/20775652/12482d9a-b72a-11e6-8cac-564560b387f0.png)

**Comment by holliscooper-cgu** [comment]
@Jessdwilson You are correct - links should be black with a red hover state.
