### ISSUE TITLE
Program pages suppress CTA buttons?

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#135]

**Comment by Jessdwilson** [comment]
@kpettinga 

Is there a way to suppress the 'request info', 'visit', and 'apply now' buttons in the sidebar? Some programs do not need them (ex. Drucker Salesforce, Leadership Arc) and will have alternate application/payment methods in place.

**Comment by kpettinga** [comment]
@Jessdwilson if buttons are going to vary across programs, i will just remove the buttons from the code and they can enter them as needed in the editor.
