### ISSUE TITLE
Footer: content issues and social icons appearing

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#136]
@kpettinga 

We should remove upcoming events from News items

http://cgu.wpengine.com/news/2016/01/cheryl-crazy-bull-ceo-of-american-indian-college-fund-to-give-daryl-g-smith-diversity-lecture-on-jan-21/

![news-formatting-safari](https://cloud.githubusercontent.com/assets/1680051/19368402/de261d9c-916d-11e6-979f-2b93bd26c2f8.png)

**Comment by Jessdwilson** [comment]
@kpettinga now there's a weird share icon section in the footer of this page, I cleared my cache and noticed this in Chrome and Safari
![screen shot 2016-10-14 at 11 36 38 am](https://cloud.githubusercontent.com/assets/1680051/19393516/03503630-9203-11e6-9866-4b6a36830317.png)

**Comment by kpettinga** [comment]
@jessica, there was some kind of weird [caption] shortcode being used in the post. it was messing up the html. I've removed it and things should be working now.
