### ISSUE TITLE
Admissions: FAQ module

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/cgu#137]
Firstly can we lighten up the background color here? Looks really dark, maybe the same gray as the main navigation? #edebe9

Also the buttons on the hover, the text changes to the background color which is hard to read and will need to be white. Screen shot of button below.

![image](https://cloud.githubusercontent.com/assets/12611145/19368383/c3eb33ae-916d-11e6-98bd-ab3e7701812a.png)

**Comment by elliotarthur** [comment]
@kpettinga unless this was a client request to have the color of the module this dark. Could we lighten the FAQ module background please? I think #EDEBE9 would be nice.

**Comment by kpettinga** [comment]
@elliotarthur, the module color needs to be changed in the backend.

**Comment by elliotarthur** [comment]
@kpettinga is this something you can do or will we need @davekellam to take a look? Thanks

**Comment by kpettinga** [comment]
@elliotarthur, what I meant by "backend" is just that a different module color needs to be chosen for that module. If you're logged in, you can hover the module and click "edit module". On the next page you can select a lighter gray.

**Comment by Jessdwilson** [comment]
@elliotarthur I updated the FAQs module to a lighter grey, let me know if this works.

![screen shot 2016-10-20 at 6 53 26 pm](https://cloud.githubusercontent.com/assets/1680051/19580780/92c6f1b2-96f6-11e6-96ef-efe6e6759719.png)
