### ISSUE TITLE
Programs: duplicated sidebar info

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#139]
Why is info repeated in the sidebar? I checked the WP program entry and the info is only entered once 

![screen shot 2016-10-13 at 6 05 07 pm](https://cloud.githubusercontent.com/assets/1680051/19368813/d1ab0a4e-916f-11e6-9a59-16ac0c8df786.png)

**Comment by kpettinga** [comment]
These buttons are programmed to automatically appear in the sidebar on programs. They do not need to be entered with a shortcode in the text editor.

**Comment by kpettinga** [comment]
@jessdwilson these buttons DO need to be added with the button shortcode after all because it turns out there are programs where different or no buttons are used.

**Comment by davekellam** [comment]
Is this duplication still and issue? Should automatically generated links be removed, should there be different wording or spacing?
