### ISSUE TITLE
Sidebar: Change the background color

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/cgu#140]
@kpettinga This is more of a question than an enhancement but could be an enhancement after your answer. :)

Did CGU pick this color from your color selector for the background of that right hand sidebar?

![image](https://cloud.githubusercontent.com/assets/12611145/19369130/93b6ade0-9171-11e6-87d3-6e1b03169ad4.png)

If not can we change it to #ccedf5

![image](https://cloud.githubusercontent.com/assets/12611145/19369149/b676dde6-9171-11e6-89a5-8706fae5f214.png)

**Comment by kpettinga** [comment]
They did indeed pick it :) apparently the light blue wasn't showing up on their monitors.

**Comment by elliotarthur** [comment]
Argh! It's so horrible. I'll see what we can do to change it...
