### ISSUE TITLE
General: change color of Video buttons

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/cgu#141]
Change to the CGU red which is #9B1210

Looking specifically at the Drucker school landing page.

![image](https://cloud.githubusercontent.com/assets/12611145/19394679/4a3c1b54-9208-11e6-8b06-a41dfaaf38d8.png)

**Comment by Jessdwilson** [comment]
The red should instead be #af1e27 as it will be for the rest of the design enhancements
