### ISSUE TITLE
Schools: subpages not to appear in navigation

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#145]
There are items that should be included in the footer of school pages, but shouldn't appear in the main navigation. For example - "Contacts" or "Board of Industry Advisors" - would exist in the school footer, but not the main subnav. 

What is the best way to go about adding these?

**Comment by kpettinga** [comment]
You can either add them as child pages of About (or some other school page) or we will have to figure out a way for users to select what shows up in the nav. (code changes)

**Comment by Jessdwilson** [comment]
@kpettinga unfortunately adding these as child pages of About won't work, many About pages have children that should appear in the regular sub-nav (dean's message, FAQ, student life, etc.)

If it's a code change these are the items that will need to appear in the school footers:

**Drucker bottom nav**
Peter F. Drucker
Masatoshi Ito
Accreditation & Membership
Board of Industry Advisors
Financial Engineering Board of Advisors
Staff
News
Events
 
**All the other Schools**
Accreditation & Membership (SCGH only other school that has this - everyone else is covered by CGU accreditation info)
Board of Advisors
Staff
News
Events

**Comment by kpettinga** [comment]
Hey @Jessdwilson,

You can now select menus for the footer AND header of schools. I will go ahead and make the header menus and assign them.
