### ISSUE TITLE
General: Video background color and font 

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#146]
Video group shortcode issues:
- [ ] Doesn't allow you to specify a background color
- [ ] Font weight seems off from mockup 
- [ ] Needs more whitespace at the top of this module
- [ ] Video formatting is off (see screenshot). Compare this to the mockup of the Drucker homepage ([here](https://www.dropbox.com/home/OS%20%26%20CGU/Creative%20Refinements?preview=CGU+Website+Design+Refinements+20160607+B.pdf))

See current implementation on Drucker school page: http://cgu.wpengine.com/school/drucker-school-of-management/

**Comment by kpettinga** [comment]
If a group of videos should have its own background color, please use the short code in a module, give it a color, and add it to the page.

**Comment by Jessdwilson** [comment]
thanks @kpettinga this works, but the module should appear below the Featured Programs instead of lumped in with the other modules (screenshot attached).

Also, the font weight for the video descriptions is bolder than what we have in our mockups (screenshot attached)

![video module test](https://cloud.githubusercontent.com/assets/1680051/19613940/2aed1a6c-97be-11e6-999a-ce8fcf2a3bab.png)
![os drucker video mockup](https://cloud.githubusercontent.com/assets/1680051/19613944/30574cc0-97be-11e6-8709-6df6c4918843.png)

**Comment by kpettinga** [comment]
@Jessdwilson @holliscooper-cgu
The problem here was the video shortcodes outputting extra html.

I've fixed it by changing the `[cgu_video_group]` shortcode which will now accepts a comma-separated list of youtube IDs. So you only need to use 1 shortcode to produce a video group.

**Old way:**
[cgu_video_group]
[cgu_video id="xxxxxx"]
[cgu_video id="yyyyyy"]
[cgu_video id="zzzzzz"]
[/cgu_video_group]

**New way:**
[cgu_video_group ids="xxxxxx, yyyyyy, zzzzzz" title="Drucker Videos"]

**Comment by elliotarthur** [comment]
@kpettinga How can we change the background color ourselves? The Off White is not showing on my screen. Some video modules will need a color background to differentiate itself from the modules above and below. Also, can the video captions be globally set to Body please?

**Comment by Jessdwilson** [comment]
@elliotarthur If a group of videos should have its own background color we can use the short code in a module to give it a color, however, I just tried this and it wasn't working for me. Would you mind taking a look @kpettinga ? I tested it out on the Drucker Videos module

**Comment by kpettinga** [comment]
hey @Jessdwilson, the [cgu_videos_group] shortcode was updated last week to be a bit easier to write. Now you can just specify the list of video IDs in a comma-separated list:

`[cgu_video_group ids="sVHulfDqXv4,KjKkGENKR2w,kCsFWVcwsIA,leFSEhc-n-A"]`

A title can still be specified if you like but if it's in a module, you can just let the module name be the title.

**Comment by elliotarthur** [comment]
@kpettinga How can I change the video descriptions? I'd like those to be set in Body text to align with the mockups.
