### ISSUE TITLE
Homepage: duplicate News "Read" Buttons

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#148]
@kpettinga What is the difference between "Read More" and "Read More News" buttons in the News section on the homepage?

Also, the "Read More" button at the top doesn't link to anything, should we remove this? 

![read-more-vs-read-more-news](https://cloud.githubusercontent.com/assets/1680051/19486503/ad921d9e-952c-11e6-9632-8279a2e1c9e7.JPG)

**Comment by kpettinga** [comment]
@jessdwilson, it's a mistake that the top button doesn't link to anything. I can fix that but should I delete one of the read more buttons or keep both? They're intended to link to the same place

**Comment by Jessdwilson** [comment]
@kpettinga I think we should remove the "Read More" button at the top. thanks!
