### ISSUE TITLE
Schools: Careers page – Request Info

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#150]
@kpettinga we should remove generic "Apply for [School Name]" section on main school pages. See attached example on the Druckers page, http://cgu.wpengine.com/school/drucker-school-of-management/careers/

I didn't see the option to edit this in WP, is this something you will need to fix?

![apply-for-drucker](https://cloud.githubusercontent.com/assets/1680051/19487015/c43e3cce-952e-11e6-9c3d-ef6fce12a45f.JPG)

**Comment by kpettinga** [comment]
@jessdwilson, yes I'll need to amend this.
