### ISSUE TITLE
General: Ability to pull profile photos

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#154]
Hollis would like to have the ability to pull in profile photos and snippets at will - especially on pages where they need to list certain staff members. 

Ex. On this page: http://cgu.wpengine.com/school/drucker-school-of-management/careers/

> I want to pull in the profiles for the Drucker Careers people - Julie Toothacre and Aaron Bennett. We are also missing program contact pages, etc.

**Comment by davekellam** [comment]
Any idea if they were thinking more shortcodes, or some sort of custom fields picker (this could get tricky quickly). Do we have a general sort of card/faculty member template?

Also, "We are also missing program contact pages, etc/". Is that something that should be a different issue?

**Comment by Jessdwilson** [comment]
@davekellam yes, Hollis is thinking a shortcode would be useful. There is a faculty member template

**Comment by kpettinga** [comment]
@Jessdwilson, there is now a [profiles] shortcode which can be used for this as well as in other places where they want to pull in a custom set of people/students.
See http://cgu.wpengine.com/wp-admin/admin.php?page=wp-help-documents&document=5536 for instructions on how to use the shortcode.
