### ISSUE TITLE
General: Contacts pages

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#155]
CGU would like to be able to build out a program contacts page for:
* [ ] schools
* [ ] departments
* [ ] central admin pages

Example: http://drucker.cgu.edu/programs/program-contacts/

**Comment by davekellam** [comment]
To clarify a bit more, where do they want these pages to live? Maybe some url examples? I'm curious if we need specific templates or if this might be doable in conjunction with #154.

**Comment by Jessdwilson** [comment]
I think the program contacts page could be similar to the existing faculty page template: http://cgu.wpengine.com/school/ssspe/faculty/

For schools, Program Contacts should appear in the subnav of Programs pages, like the Drucker site: http://drucker.cgu.edu/programs/

For departments, Program Contacts should appear in the subnav of department landing pages 

For the administration page, Program Contacts will be a child page

**Comment by davekellam** [comment]
This is more complicated than it appears on the surface, and probably needs some thought put into the approach. Right now, the schools faculty template works by pulling in all people that have the school checked off on their people page.

So, what's the best approach to managing this? Do we want to have checkboxes for departments, programs and pages on the person's page? We could add picker type fields to the various departments, programs and pages. A shortcode related to #154 that allows you to specify a group of profiles to pull? For a shortcode, how would it work... a list of ids?

**Comment by kpettinga** [comment]
@Jessdwilson, @davekellam, there is now a [profiles] shortcode which can be used to create these pages.
See http://cgu.wpengine.com/wp-admin/admin.php?page=wp-help-documents&document=5536 for instructions on how to use the shortcode.
