### ISSUE TITLE
Research Centers: revise template to include a sidebar

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#156]
From Hollis:

> Need a revised research center template that has a side column for listing the director(s) of the research center, contact info (email, address, website), and school affiliation(s). 

I built a quick version here:  http://cgu.wpengine.com/center/center-for-supply-chain-and-logistics/

The sidebar formatting should more closely follow the faculty profile sidebar, and if an element is missing (ex. website address), it shouldn't appear. 

There may be more than one director, and more than one affiliated school. All research centers are going to follow this template. If for some reason they have none of the sidebar info, the sidebar space can remain blank.

**Comment by davekellam** [comment]
A few questions:
* Is the director coming from the People listings (i.e. should there be a picker in the backend)?
* Is the contact info from the director, or do we need fields for that?
* The school affiliations are coming from the taxonomy checked in the sidebar?

**Comment by elliotarthur** [comment]
@kpettinga Can we either remove the last stroke on the "Affiliated School" list or remove the lines altogether?

![image](https://cloud.githubusercontent.com/assets/12611145/20078800/0a13d222-a510-11e6-881d-339b662761a3.png)
