### ISSUE TITLE
Faculty: breadcrumbs

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#158]
From Hollis:

> We are breaking out Faculty and Research, so the breadcrumb navigation on the faculty profiles pages needs to reflect this.

example - http://cgu.wpengine.com/people/katharina-pick/

**Comment by davekellam** [comment]
Does this mean they would like a top-level page for Faculty and Research, and no longer want the school in the breadcrumb?

**Comment by Jessdwilson** [comment]
@davekellam no, there's no longer a Faculty & Research page. So in the url example the breadcrumb should be home > Drucker School of Management > Faculty
