### ISSUE TITLE
Faculty: add social media to sidebar

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#159]
From Hollis:

> [N]eed to add section for social media accounts in right sidebar. some faculty have multiple accounts - LinkedIn, Twitter, Facebook

**Comment by davekellam** [comment]
Do they want those three specifically, or more of an open ended list of links? Text links are easy, but it creates issues if they want icons associated with the links (you really need a fixed set unless there's a generic link icon).

**Comment by Jessdwilson** [comment]
@davekellam those are three that faculty will definitely need but they may decide to add to this 

@elliotarthur do you have an opinion if these should be icons? On faculty landing pages when their email is listed it's written out rather than an icon, so maybe social media items should be text links?

ex. http://cgu.wpengine.com/people/gary-gaukler/

**Comment by elliotarthur** [comment]
@Jessdwilson, @davekellam  Icons are fine. As long as the inactive state is a lighter grey than what we're using in the footer.
