### ISSUE TITLE
Academics/Program tool ordering

### ISSUE THREAD

**Issue by davekellam** [ObjectiveSubject/cgu#16]
It seems like ordering has become a bit messed up on the academics tools.

Something like `/academics/?degree_types=masters` will return programs chunked up by concentration, but not by area of study. Similarly, something like `/academics/?areas_of_study=art,economics` seems to return the results as one group.

Not sure if this was the original behaviour, or we've since done something that was had a knock-on effect to the tool.

**Comment by kpettinga** [comment]
Fixed!
