### ISSUE TITLE
Sidebar: option with links to external sites

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#161]
From Hollis:

One more thing that we have realized that we need is a way to create sidebars that don't _only_ pull sibling or child nav elements - for example, on Academic Resources & Support, we need to have sidebar navigation that links directly to external sites, like MyCGU, the libraries, etc. That said, I don't think it would ever be a mix of child pages/non-child pages - it would be either/or.

**Comment by kpettinga** [comment]
@Jessdwilson custom sidebar content can now be added to pages using the Page with Sidebar template.
