### ISSUE TITLE
Administration subnav: should be tabbed nav?

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#162]
On the Administration page we had the [[child_pages]] shortcode which I know was being swapped out in favor of a sidebar, I updated the Administration page with the "Page with Sidebar" template, but this page will also include a staff profile module, so when I preview the page the sidebar appears above the module. I wonder if we can or should keep the option for a tabbed subnav for cases like these?

 http://cgu.wpengine.com/about/administration/

**Comment by kpettinga** [comment]
@jessica, we should use the [profiles] shortcode in this situation.
I've updated the page: http://cgu.wpengine.com/about/administration/
