### ISSUE TITLE
People photo format

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#165]
Andrea and Hollis were wondering if it would be possible to change the photo format for people so photos are square instead of rectangular. They are finding that some photos are less flattering or not professionally shot and that it would help with consistency if the photos could be square for faculty/staff/students

**Comment by davekellam** [comment]
The current `profile` photo size is set to 600px wide x 400px tall. We can set the size to something square, like 600x600, but the images will need to be regenerated. Usually do that with wp-cli, but it's not available for most people on wp engine, there is a plugin that should work though. Another note, it will do an autocrop in the centre of a photo that's wide/tall. So, they may want to go into the image editor to reposition people in the frame.

**Comment by Jessdwilson** [comment]
thanks! @davekellam 

Can we add the plugin to generate the square photos for faculty and staff? CGU is looking to add additional photos asap and want to make sure the new photos fit in the square format.

**Comment by kpettinga** [comment]
@davekellam mind handling this?

**Comment by Jessdwilson** [comment]
@kpettinga Dave has updated this on the site, but the 3x2 graphics still appear for placeholder profiles. Can you update with a revised graphic? 

http://cgu.wpengine.com/school/school-of-community-and-global-health/faculty/

http://cgu.wpengine.com/wp-content/themes/cgu/assets/images/placeholder_people.svg
