### ISSUE TITLE
Request Info: Hobsons connect to forms

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#166]
@davekellam I spoke with Kirk briefly about this, on the current site if a visitor clicks Request Info it takes them to this page: https://cguall.askadmissions.net/emtinterestpage.aspx?ip=gradrequest

We don't necessarily need an iframe though, and Kirk suggested the Request Info button could link to a separate page in a new tab. We need to make sure the "Learn More" fields connect to Hobsons, can you research this?

**Comment by kpettinga** [comment]
@Jessdwilson My impression was that the askadmissions.net link you referenced IS ALREADY a form hooked up to Hobsons. Is that wrong? 

@davekellam If Hobsons has an API, I wonder if we could just create a custom form of our own that posts data to CGU's Hobsons database. Then we could essentially just recreate that askadmissions.net page on our site, thereby not making the user open a new tab on a new site.

I think we may all need to pow-wow on this.

**Comment by Jessdwilson** [comment]
@kpettinga that's correct, the link I posted above is connected to Hobsons. We'll need to recreate this for the new site so it's on-brand. 

Let me know if it would be best to schedule a call sometime Monday to discuss. thanks!

**Comment by davekellam** [comment]
I'm a bit confused by this. Right now this is like a white-label thing on askadmissions? They want to bring it into the site, or try to bring the white label up speed and link out to those like they're currently doing? 

Any idea how many of these there are? I'm assuming the `?ip=***` request is the bit that actually directs them to the appropriate place. Likely not relevant, but doesn't hurt.

**Comment by kpettinga** [comment]
@Jessdwilson @davekellam: Just to recap our plan after today's call:

*Our plan*:
Embed each Hobsons request info page into a series of request info pages we'll create on the new site (ie. */request-info/*, */request-info/ssspe/*, etc ). We've requested a list of all the Hobsons pages they current use for request info submissions.

*Next Steps*:
Once we have the full list of Hobsons URLs, we'll create our own series of request info pages and direct users to them accordingly. We will probably need to figure out a way to conditionally direct users to the right page based on where they're coming from. For instance, if someone is viewing the Positive Health Psych program, clicking "request info" in the sidebar will bring them to */request-info/ssspe/* (or similar).

**Comment by Jessdwilson** [comment]
@davekellam @kpettinga Hollis pointed out that the Drucker Request Form is being handled the way we've described: http://drucker.cgu.edu/request-info/

**Comment by kpettinga** [comment]
@Jessdwilson that is correct, they are embedding the form with an iFrame.

**Comment by Jessdwilson** [comment]
Hayley with CGU who manages the Hobsons account replied about the URLs: 

Below is the list of all info pages and their links.
 
1.      Math: https://www.cgu.edu/landing/ims.asp
2.      SSSPE: https://cgu.edu/landing/ssspe.asp
3.      SAH: https://www.cgu.edu/landing/sah.asp
4.      SES: https://cguall.askadmissions.net/emtinterestpage.aspx?ip=ses
5.      CISAT: https://www.cgu.edu/landing/cisat.asp
6.      Drucker: http://drucker.cgu.edu/request-info/    https://cguall.askadmissions.net/emtinterestpage.aspx?ip=drucker
7.      CGH: https://www.cgu.edu/landing/scgh.asp
8.      All Programs: https://cguall.askadmissions.net/emtinterestpage.aspx?ip=gradrequest
9.      Start App: https://cguall.askadmissions.net/emtinterestpage.aspx?ip=startapp
10.   https://cguall.askadmissions.net/emtinterestpage.aspx?ip=default (not currently in use)

**Comment by kpettinga** [comment]
@davekellam, please get these setup in iFrames on their own child pages under Request Info.

**Comment by davekellam** [comment]
I've created a shortcode that we can use to embed Hobsons forms, which takes the form `[hobsons_form id='']` where `id` is the value found at the end of the url string for the iframe. I based it on the drucker iframe.

| School | id |
| --- | --- |
| Math | `instituteofmathematicalsciences`|
| SSSPE | `schoolofsocialsciencepolicyevaluation` |
| SAH | `schoolofartsandhumanities` |
| SES | `ses` |
| CISAT | `centerforinformationsystemstechnology` |
| Drucker | `drucker` |
| CGH | `communityandglobalhealth` |
| All Programs | `gradrequest` |
| Start App | `startapp` |
| Default | `default` |

Note: it currently falls back to `default` if nothing is selected.

Should I go ahead and create child pages or leave it to someone else?

**Comment by kpettinga** [comment]
@Jessdwilson @davekellam 

I've created pages for all the hobsons request info forms. For each school form I've create a child "Request Info" page under each school (example: http://cgu.wpengine.com/school/school-of-arts-and-humanities/request-info/).

The global request info page (http://cgu.wpengine.com/request-info/) I've embedded the `gradrequest` hobsons form. 

The `startapp` and `default` forms I have not embedded anywhere. The client can embed those where they see fit.

**Comment by kpettinga** [comment]
@Jessdwilson I'll leave this to you to close or keep open if there's anything else.

**Comment by Jessdwilson** [comment]
thanks! @kpettinga and @davekellam 

On school landing pages the Request Info button in the header should link to the school form instead of the general form, I'm not sure how to set this up
![screen shot 2016-11-09 at 12 38 42 pm](https://cloud.githubusercontent.com/assets/1680051/20148472/cb3e9d54-a67a-11e6-93c1-08f1ad3a0ae0.png)

**Comment by Jessdwilson** [comment]
also, Andrea sent the following. Can this be added to the forms?

Before we start testing with Hayley, we need to add some fields in the Request Info module that match up to the back end. The fields we need are:

**Required:**
First Name 
Last Name
Email Address
Verify Email Address
Program of Interest (drop down menu)
Anticipated Start Term (drop down menu)

**Optional:**
Zip
Phone
Country (drop down menu)
Degree of Interest  (drop down menu)
Current undergraduate student at one of The Claremont Colleges Y/N

You can see this form in action here: https://cguall.askadmissions.net/emtinterestpage.aspx?ip=gradrequest

Once those fields are in place on the form we can create some dummy test profiles so Hayley will be able to map them to the fields she has in the CRM and ensure that they’re coming through accurately. 

![screen shot 2016-11-09 at 4 12 54 pm](https://cloud.githubusercontent.com/assets/1680051/20160500/53376260-a6b5-11e6-92ff-6abca4f5fa5f.png)

**Comment by kpettinga** [comment]
@Jessdwilson 

The request info button in the headers of schools is just a regular link in that school's header menu. All you have to do is remove the current request info link and replace it with the one relevant to that school. Request info pages for each school are children of their respective schools (ie. /ssspe/request-info).

**Comment by kpettinga** [comment]
@Jessdwilson regarding adding fields to the hobsons forms, I think there's been some confusion about this.

**We have absolutely no power to add fields to any hobsons forms**. I'm assuming that CGU works together with their contact at Hobsons to create/manage their forms. They need to be the ones to add these fields.

**Comment by holliscooper-cgu** [comment]
@kpettinga @davekellam @Jessdwilson 

I have a few questions, and I'm assuming this is the spot to ask them:
- How are the request info fields at the bottom of the program pages being handled?
- If you're using an API, do you have more styling control over the appearance of the form fields? It looks like fonts can't be controlled on our end, but background colors can? 
- Is having the form in a narrow column the safest way to deal with responsive display issues?

And yes, you're correct that we have to request Hobsons to add any fields to the form. I think there's been some confusion about who is on point for this, but we'll get it done. That shouldn't affect much on your end (except for, perhaps, the height of the iframe).

**Comment by kpettinga** [comment]
Thanks for the clarification @holliscooper-cgu !

In regards to your questions:

- The request info fields on programs pages are gravity forms. Gravity Forms is a plugin we've used often in the past and allows you to create forms in wordpress and display them on your pages. When a user fills out the form, the response gets logged in wordpress (http://cgu.wpengine.com/wp-admin/admin.php?page=gf_entries&id=1).
- The API does not let us give style to any component of the forms. The reason the background color is editable on some forms is because the content in the `<iframe>` does not have a background color set, so it's transparent. You're not really editing the background of the form, just the iframe's container.
- The forms seem to be _somewhat_ responsive and I haven't noticed any cases where a field is hidden because the container wasn't wide enough. If you'd like to have the forms in the main content area it's easy to move them as they're just loaded with a shortcode.
