### ISSUE TITLE
Admissions: Financial Calculator

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#167]
We'll need to setup the Financial Calculator found on the Admissions page: http://cgu.wpengine.com/admissions/

This can be found on the current site here: http://www.cgu.edu/pages/5263.asp

Hollis said we should take the existing code from the current site, let me know if we need to request code files from CGU

**Comment by kpettinga** [comment]
@Jessdwilson just copying the html from the current site won't get us there. We need the script that processes the form and does the calculation.

**Comment by Jessdwilson** [comment]
@kpettinga Greg with CGU replied:

The problem is that the Financial aid calculator is done in ASP, as it turns out, rather than Javascript. So it should probably be converted. 

It could be pulled into an iframe as is done now but eventually converted depending on what Andrea wants to do.

In case it helps, the link to the standalone calculator page is:
http://www.cgu.edu/custom/finaid/pages/calc.asp

I'm attaching the ASP page zipped in case it helps. Saved to Dropbox here: https://www.dropbox.com/s/h6zay8zrze4e9w0/calc.asp?dl=0

**Comment by kpettinga** [comment]
@Jessdwilson thank you! We can just embed the standalone calculator in an iframe.

**Comment by kpettinga** [comment]
@Jessdwilson @holliscooper-cgu

I've created a [financial_calculator] shortcode so that the calculator can be placed on any page. 

[See the documentation for instructions](http://cgu.wpengine.com/wp-admin/admin.php?page=wp-help-documents&document=5994).

**Comment by Jessdwilson** [comment]
Is there anything we can do to make the financial calculator more on brand? Also, if you click the Reset button it loads the Student Services homepage, can this be fixed? 

![screen shot 2016-11-09 at 7 36 19 pm](https://cloud.githubusercontent.com/assets/1680051/20160289/dae9f15c-a6b3-11e6-9310-619b3cfc4111.png)

**Comment by kpettinga** [comment]
@Jessdwilson the only way to customize the design and/or keep the page from reloading on reset would be to edit the code on the source page that the iframe is referencing. Unfortunately we can't do those things.

In the long term they may want to think about bringing the calculator natively into the site. The calculator would then be able to take on the styles of the site. However it would also require someone to convert the ASP code, which it currently runs on, into Javascript, which we don't have the expertise for.

**Comment by holliscooper-cgu** [comment]
This will be an issue because as soon as the new site goes live, that asp page will be going away. I'll talk to Greg and see if he has any thoughts about converting it (it's going to have to happen sooner rather than later).

**Comment by holliscooper-cgu** [comment]
Greg is working on converting it. I'll update here when he's done.

**Comment by Jessdwilson** [comment]
From Greg: 

Please find attached my stab at a conversion, from asp to php, of the Financial Aid Calculator. 

The attached zipped file is the fragment that I inserted in the shortcodes.php of a clone of cgu.wpengine.com:

http://cgudev3.wpengine.com/admissions/cost-aid/financial-calculator/

I've hardcoded the url for the form action and the reset button which you could change and so on.

Absolutely please modify at will (including css to suit the template). 

[calc-html-body-only.zip](https://github.com/ObjectiveSubject/cgu/files/594576/calc-html-body-only.zip)

**Comment by kpettinga** [comment]
@holliscooper-cgu @Jessdwilson I've implemented Greg's solution into the [financial_calculator] shortcode. I've also added some javascript so that a page reload is not necessary when you click Calculate or Reset buttons.

See the [Financial Calculator shortcode Docs](http://cgu.wpengine.com/wp-admin/admin.php?page=wp-help-documents&document=5994) for help using it.
