### ISSUE TITLE
Filter availability on school program pages

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/cgu#17]
On school-specific program pages, only the filters and degree types specific to the current school's programs should be available for selection.

**Comment by kpettinga** [comment]
@davekellam can we just provide a field on top-level school posts for this?

**Comment by davekellam** [comment]
Hmm, that's a possibility, but it's a pretty poor experience if they have to go in and add all the degrees and areas of study for each school on the school's page. I imagine there's some way to pull just the ones needed, but not sure at the moment. Might need to use some complex queries or logic and then cache the results in a transient.

**Comment by kpettinga** [comment]
Cool. Let me know if you need help implementing that.

**Comment by davekellam** [comment]
💥 ✌️
