### ISSUE TITLE
Adjunct and Affiliated Faculty

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/cgu#171]
From Hollis:

We will need to display adjunct and affiliated faculty on the new website. However, this adds a lot of content to the faculty lists, so we were thinking that an additional display mode might be good for the adjuncts - something like the "previous lectures" under the visiting artist lecture series on this page: http://cgu.wpengine.com/departments/art/
 
Basically, we'd want their name, title, email, and link to website. (no photo, no profile page that would be displayed, although if one needs to be created on the backend for this to work, that's fine.)
 
In terms of where these faculty would be displayed, we'd want the following:
- Program pages - just core faculty, with a link at the bottom of the module to View All Faculty (for schools with departments, this would link to the department faculty page; for schools without departments, this would link to the school faculty page)
- Department pages - core faculty and visiting/adjunct/affiliated faculty (core first with profile pics, the others after in list format)
- School pages - Same as department, except for the entire school. If a school has departments, we'd like the ability to filter faculty by department.

**Comment by kpettinga** [comment]
@Jessdwilson, this can be achieved in the same way that the previous lectures list was built, using the [column_group] and [column] shortcodes inside a module. Refer to the Previous Lectures module for an example.

**Comment by kpettinga** [comment]
@Jessdwilson 

If the ability to organize/filter by department on school faculty pages is A MUST, adjunct and affiliated faculty will need to be created in the backend like every other faculty member.

If that ability is *not required*, adjunct and affiliated faculty can just be listed in a module and attached to the school's faculty page.

**Comment by kpettinga** [comment]
@holliscooper-cgu could you please provide feedback for this so we can estimate a timeline? Thanks!

**Comment by holliscooper-cgu** [comment]
Hi Kirk, since we've gotten feedback from the schools, we've ended up using the shortcodes to display faculty pages instead of the template, so we can tweak the order and group them under subheadings.

While adjuncts will uniformly be at the bottom of faculty lists, I would imagine that we'd still use this method to organize. I'm okay with creating profile pages for them on the backend.

The main functionality change is that even if they have a profile page, we don't want the "view profile" link to show. We would like the ability to link out to an external website, though, instead (although all may not have this option).

**Comment by kpettinga** [comment]
@holliscooper-cgu 

**Question**: Will "adjunct/affiliated" be one role type or is it going to be separated into "adjunct" and "affiliated"?

Go ahead and create the adjunct/affiliated faculty in the backend and assign them to their appropriate role(s) and school(s). You can continue to use the [profiles] shortcode to display these faculty. In the includes field just write email and website. **Example**:

`[profiles ids="{IDs of faculty}" includes="email, website"]`

I will start editing the program, school, and department templates so that when faculty are listed, the adjunct/affiliated will show up underneath the primary ones.

**Note**: Even though a link will not be provided to these adjunct/affiliated faculty, a url will still exist for them because you're creating them as a post in the backend. Just making you aware.

**Comment by holliscooper-cgu** [comment]
@kpettinga Adjunct and affiliated will most likely be separated.

**Comment by kpettinga** [comment]
@holliscooper-cgu there is now an "Adjunct/Affiliated Faculty" field on programs which you can use to add secondary faculty. They will appear in a separate list underneath the primary faculty.

As for the other instances of faculty profiles, they're all created with the [profiles] shortcode. I've added a new `link_to_profile="false"` option to the shortcode so that you can omit the "View Profile" link. [See the docs for more info](https://cgu.wpengine.com/wp-admin/admin.php?page=wp-help-documents&document=5536).
