### ISSUE TITLE
Programs: not loading

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#172]
Hollis reported having an issue being unable to load the program listing pages under Academics > Programs and under the schools' program pages, she is just seeing the red loading circle. She cleared her browser cache but says it continues to occur. 

Viewing the site in Chrome 54.0.2840.87 m - PC, and her phone IE on Win phone 8.1.  It's also happening to Andrea on Safari 10.1 - Mac, Chrome 54.02 - Mac, and Firefox 49.02 - Mac.
 
Is there a WP cache that needs to be flushed?

**Comment by kpettinga** [comment]
@Jessdwilson it looks like the programs template on the live site isn't the most up-to-date one. I'm trying a redeploy of all site files now.

**Comment by kpettinga** [comment]
@Jessdwilson the redeploy seems to have worked. let me know if you're they're still seeing issues.

**Comment by Jessdwilson** [comment]
@kpettinga I found this to still be an issue this morning when I viewed it in Chrome: http://cgu.wpengine.com/academics/

**Comment by kpettinga** [comment]
@Jessdwilson have you cleared your browser cache? This is working for me.

**Comment by Jessdwilson** [comment]
@kpettinga yeah, I cleared my browser cache and still get a spinning wheel when viewing the programs page in Chrome... it is working fine for me in Safari, though

**Comment by kpettinga** [comment]
hmm weird. @davekellam has confirmed that it is also working for him.
