### ISSUE TITLE
People/Admissions: Display locations

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#180]
[Edited to remove duplicate issue]

- people tagged as 'admissions' on the backend and and have programs assigned to them aren't showing up on those program pages (as shown in the mockups - see attachment).
Ex. Alice Liu has Art Business attached in her profile, but she doesn't show up on the Request info module on the Art Business page: http://cgu.wpengine.com/academics/program/art-business/

![request-info-admissions-specialist](https://cloud.githubusercontent.com/assets/18012084/19950296/d17bc76c-a113-11e6-9c75-92782e10b630.JPG)

**Comment by kpettinga** [comment]
@holliscooper-cgu

Recruiters for programs need to be selected on the program edit pages themselves. See the "Recruiter" field in the sidebar. 

![image](https://cloud.githubusercontent.com/assets/1746410/19954119/c6d692da-a1a7-11e6-9acd-3686961d8b7a.png)

This works the same for faculty that show up on program pages. They are assigned on the program edit pages.
