### ISSUE TITLE
Program filter pages

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#183]
When I scroll down on program filter pages the program header (degree or area of study) scrolls with the page. I noticed this happening in Chrome and Safari 

![screen shot 2016-11-04 at 4 33 52 pm](https://cloud.githubusercontent.com/assets/1680051/20021530/91b4c058-a2ac-11e6-9071-e9b0d7ef1b1a.png)
![screen shot 2016-11-04 at 4 34 06 pm](https://cloud.githubusercontent.com/assets/1680051/20021541/9b87f014-a2ac-11e6-9d00-daa3b01f4783.png)

**Comment by kpettinga** [comment]
@Jessdwilson this isn't a bug. I made it do this so user would always know what section they're in. Sort of like when you scroll through contacts on your phone.
