### ISSUE TITLE
Resources & Support: Photo scrim option

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#184]
On the Resources & Support page the client has added photos with text overlaid but has found that some of the text is not quite legible, is there anything we can we do to improve the legibility? could there be a photo scrim option? 

![screen shot 2016-11-04 at 6 41 08 pm](https://cloud.githubusercontent.com/assets/1680051/20024637/474adcac-a2be-11e6-89a5-517b89cfdfbc.png)

**Comment by elliotarthur** [comment]
@Jessdwilson This is a little intense and we don't have a module with this much text over an image. Can this be a regular text module with an image of the library between the paragraphs or after? 

Similar to the mock up here - 

![image](https://cloud.githubusercontent.com/assets/12611145/20077798/dff390e4-a50b-11e6-910c-6ccb14db356a.png)

**Comment by Jessdwilson** [comment]
@elliotarthur yes, that might be best for this instance, but it may still be helpful to have a photo scrim option for other contexts when CGU wishes to use text over an image, for instance on the SAH Art Gallery pages

**Comment by kpettinga** [comment]
@Jessdwilson I've darkened the scrim on image modules a bit.

**Comment by Jessdwilson** [comment]
@kpettinga would it be possible to have the _option_ to add a photo scrim to a photo? It does feel a little heavy when every photo has the darker scrim

**Comment by kpettinga** [comment]
@Jessdwilson yes, option now available.
