### ISSUE TITLE
Editing menus

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#188]
In the WP admin view, "School" isn't an option for a post-type to add to a menu. For example, I added an "FAQ" (school) page to CISAT, which I'd like to add to the top CISAT menu. When I go to edit the menu, "school" isn't a type that appears on the left. 
![menus](https://cloud.githubusercontent.com/assets/18012084/20033634/832bfbc6-a362-11e6-8453-b828419120e5.JPG)

**Comment by kpettinga** [comment]
@holliscooper-cgu 

Go to the "options" tab at the very top of your browser window. Click it and a drop down will appear that allows you to select other post types.
