### ISSUE TITLE
Submit Your Event: calendars appear at bottom of page

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#191]
Viewing this in Chrome and Safari

http://cgu.wpengine.com/events/community/add

![screen shot 2016-11-06 at 9 34 17 am](https://cloud.githubusercontent.com/assets/1680051/20038599/80e36834-a404-11e6-8921-8354dd7ac75b.png)

**Comment by kpettinga** [comment]
Duplicate of #187
