### ISSUE TITLE
Why CGU Alumni Stories: order and photo centering

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#192]
We have added order numbers for each story but it's not being reflected on the Why CGU > Alumni Stories landing page. Also, would it be possible to reposition the photos that appear on each "card" 

http://cgu.wpengine.com/why-cgu/alumni-stories/

**Comment by kpettinga** [comment]
@Jessdwilson it is not possible to reposition the photos for each card. The cards need to be flexible in their width and height in order to accommodate the text content inside them. Please upload another image or edit an existing one to get the better crop you're looking for.
