### ISSUE TITLE
Alumni Stories: individual landing page

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#193]
- [x] When we add a featured image for a story the image appears in the header, can this be edited so a different photo or no photo appears? 
- [x]  We should have the option to include a full-width image as we have in our mockups 
- [x] The bottom quote should be full-width, right now it's 3/4

http://cgu.wpengine.com/stories/bill-anderson/

![story full-width photo](https://cloud.githubusercontent.com/assets/1680051/20076394/3ca96e54-a506-11e6-8563-0ecc3aca82d2.png)
![story bottom quote](https://cloud.githubusercontent.com/assets/1680051/20076396/3de9ca3e-a506-11e6-841a-9833d0a2f2e6.png)

**Comment by kpettinga** [comment]
@Jessdwilson there are now two new fields on Stories:
1. a "Large Image" field to apply the full width image
2. a "Lower Content" field to apply content below the large image.

Please use those to complete the content.
