### ISSUE TITLE
MFA Students Portfolio: text over images

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#199]
The text over the Portfolio images appears grey, can we have the option to select black or white text? 

http://cgu.wpengine.com/gallery/mfa-2016-students/

**Comment by kpettinga** [comment]
@Jessdwilson I had to update the code here so that the card labels and titles would appear on top of the scrim. We can't have the option to select the color of the text. It will always be white with a scrim darkening the image behind it.
