### ISSUE TITLE
Program Fields

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/cgu#20]
Hey Dave, see these files about the new program pages.

**Mockup**: https://www.dropbox.com/s/obwzi3g21yja6ph/CGU%20Website%20Visual%20Design%2020160504%20EWA.pdf?dl=0
**Content map from client**: 
[Program Page Modules 20160504.docx](https://github.com/ObjectiveSubject/cgu/files/251749/Program.Page.Modules.20160504.docx)

Could you create a set of fields for the current student section? We need a name, picture, and a set of repeatable fields for questions and answers. The clients reference for this part is the "Why Art History?" section on this page: http://www.conncoll.edu/academics/majors-departments-programs/majors-and-minors/art-history/

**Comment by davekellam** [comment]
Before we create them... are these meant to be reusable in any way or are they unique to each individual program?

**Comment by kpettinga** [comment]
Good question, I wonder the same. I've inquired to @jalbertgagnier about it in the #cgu_web channel

**Comment by kpettinga** [comment]
I think we've worked out what needs to happen here. Students are going to be their own post type and referenced on program pages.

**Comment by kpettinga** [comment]
@davekellam reopening this issue with some additions to the Program template.

See page 12 of the design doc:
https://www.dropbox.com/s/4idwnkbugtdiz3f/CGU%20Website%20Design%20Refinements%2020160523%20EWA.pdf?dl=0

There's a module called "Curriculum Breakdown" which consists of a table documenting courses needed every semester of the program. 

Can you figure out the best way to create fields for this? Nested repeaters would be one way but I know that got a little hairy with WS. I'll work with whatever you can put together.

**Comment by davekellam** [comment]
I'm thinking we don't need nested repeaters. The year could be a repeater field (Year 1, Year 2) and then there could be three sections within the year (Fall, Spring, Summer) where the two additional fields for each could be stored (Courses, Units). I'll implement it and see what you think.

**Comment by davekellam** [comment]
Ok, so I've pretty much added what I said I would... a repeater field for years with rows for each semester. I added some admin css to tighten things up (was sort of gross without it), feel free to tighten up if you want. Added in the front-end logic with each year as a table. I figured each one should get the column headers, to keep things solid for accessibility, imagine it's smarter to hide via styling, so they're still visible to screen readers, etc. Passing over to you for styling.

**Comment by kpettinga** [comment]
@davekellam Looks good. thanks!

We need to account for the "Both Years" rows though. Maybe that's just an ever-present group of fields below the list of years?

**Comment by davekellam** [comment]
Not sure what you're talking about with the "both years" bit, doesn't seem to be in the layout you showed me. That said, there could easily be some more fields below if needed... could spin the section out in to it's own metabox too, if it would help.

**Comment by kpettinga** [comment]
@davekellam what if each repeater just had the ability to define a custom title (e.g. "Year 1", "Year 2", "Both Years", "Something Random")?

**Comment by davekellam** [comment]
I've added in a custom title override for the years.

Going to close this out. In the future, can we use new tickets for new issues? Can prefix the issue title with things like "Programs: " to make them a bit easier to find later.
