### ISSUE TITLE
Subdomains: Social Media icons

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#202]
The social media icons in the subdomain footers are linked to Drucker's social media, instead of CGU's.

**Comment by kpettinga** [comment]
@holliscooper-cgu we're still working on implementing customizable social media icons for scholar sites. The new theme we have for research and arts currently allow you to customize this.

**Comment by Jessdwilson** [comment]
@holliscooper-cgu when you're logged in you'll see a customize button on the top, click that then Social Media, add a url then save and publish and social media icons will appear in the footer 

![screen shot 2016-11-08 at 10 49 50 am](https://cloud.githubusercontent.com/assets/1680051/20105892/5b5f8e00-a5a1-11e6-95c4-694cf2f9a05b.png)
![screen shot 2016-11-08 at 10 48 26 am](https://cloud.githubusercontent.com/assets/1680051/20105893/5cdbc7c6-a5a1-11e6-87c8-269a1a10a1b8.png)

**Comment by kpettinga** [comment]
@holliscooper-cgu you can now do the same thing for social media on the cgu.wpengine.com
