### ISSUE TITLE
Recruiters: Associated program display

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#203]
Can the "Programs" section displayed under a recruiter's name include both programs and areas of study (in a single display, not separated out)? For some recruiters, using the area of study ("Psychology" or "Mathematics") makes more sense than the program name(s). However, for some recruiters, the program names are required (e.g. Alice Liu - Art Business and Arts Management). Recruiters can already be tagged by area of study on the backend.

**Comment by kpettinga** [comment]
@holliscooper-cgu in which page(s) are you referring to here? Programs? The recruiter's own page? Admissions?

**Comment by holliscooper-cgu** [comment]
I mean wherever a recruiter's profile info is displayed (whether on a school page, program page, or contacts page). Right now, under the header "programs" under the recruiter's name, it displays the programs that have been attached to their profile. For some recruiters, though, this becomes an unwieldy list, and so displaying the area of study that the recruiter is tagged with would make more sense. However, for a few recruiters, displaying the programs they are associated with is necessary, so I'm asking if this displayed list could pull from both programs and areas of study attached to the recruiter's profile.

**Comment by kpettinga** [comment]
Thanks for clarifying @holliscooper-cgu.

What we can do is add the option to show areas of study with the `[profiles]` shortcode. Programs is already an option to show so, if you wanted a profile to display areas of study, just omit 'programs' from the 'includes' attribute and use 'areas of study' instead.

For pages where profiles are baked into the page template (i.e. a program page), we'll have to dictate whether it should show the programs or the areas of study. 

For the pages where the profiles are baked into the template, let me know which profiles should show programs and which should show areas of study.

**Comment by holliscooper-cgu** [comment]
I wonder if it would be easier, then (since it's always going to be a mix of programs and areas of study for the recruiters), to add a text-input field on the 'people' template (where we could enter what we wanted to display under the recruiter's name) and only display that field on someone's profile if the person is tagged as 'admissions' - similar to the way that faculty profiles use the "Areas of Expertise" field to display "Research Interests."

We wouldn't need these items to link to a program page or anything else, so it would just be a text display under their name/contact info. To be clear, this would replace the part of the recruiter profile (under the heading "Programs") that currently displays the tagged programs assigned to that recruiter.

**Comment by kpettinga** [comment]
@holliscooper-cgu that sounds fine to me. We'll implement a text field for "custom program/area of study content". If there's text in the field, it will override the selected programs and areas of study and the custom text will display on that person's profile under a "Programs" heading.

**Comment by kpettinga** [comment]
@holliscooper-cgu this should be all set. There's a new field on people edit pages called "Custom Program/Area of Study Content". If you enter text in this box, it will override the Programs and Expertise fields and display the custom content under a "Programs" heading (see screenshot). 

**Note**: If you're using the [profiles] shortcode you shouldn't need to change anything. As long as "programs" or "expertise" is specified in the `includes="..."` parameter, it will first check for content in the "Custom Program/Area of Study Content" field and use that.

![image](https://cloud.githubusercontent.com/assets/1746410/21129951/d259bb50-c137-11e6-8366-92a99f29c7c2.png)
