### ISSUE TITLE
Faculty Experts Guide page

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/cgu#208]
@kpettinga I have a few comments regarding this page. Most of them are to do with spacing. I'll create a check-list to help make these comments digestible. Also, I created a screenshot of what I'm referencing too, to try and help you.

- [x]  Remove the line above each area of study. I don't think this pattern is used elsewhere.
- [x]  Add more space between experts name and profile. Maybe the same as the gutter width?
- [x]  Add loads more maybe 4x more space between each row of faculty experts.
- [ ]  ~~The links "VIEW PROFILE" can they be red and the text change to Body [strong].~~

![faculty experts](https://cloud.githubusercontent.com/assets/12611145/20115048/c1f64244-a5c4-11e6-922a-e78f7ad9d04c.png)

**Comment by elliotarthur** [comment]
Not sure whether this was a client request, but the red search bar is rather intense. Could this be the same grey as the Academics filter?

![image](https://cloud.githubusercontent.com/assets/12611145/20115080/ef5bf922-a5c4-11e6-89ce-cf93dedce882.png)

**Comment by elliotarthur** [comment]
Back to the View Profile links. I've noticed with these links on pages like Meet our Team and Faculty pages they need to be the same as the above comment.

http://cgu.wpengine.com/school/school-of-arts-and-humanities/faculty/
http://cgu.wpengine.com/admissions/meet-our-team/

**Comment by holliscooper-cgu** [comment]
The design changes take care of some of these issues, but we have some requests:

- Find an Expert box should be separate from the navigation and tan, similar to the program filter box on the Academics page. 
- We want to add a short amount of intro text in that intervening space
- Remove the lines under the area of study headings
- Make sure all areas of study appear in the dropdown
- Areas of study headers should match the Academics/program page (Mercury)

**Comment by kpettinga** [comment]
@holliscooper-cgu @elliotarthur this should be taken care of. A lot has changed in the design which affected some of the above mentioned items.

- The line under each area of study heading has been removed
- each area of study heading is now congruent with other section headings (H2 size in Mercury).
- intro text can be added to the page and it will be shown above the Find an Expert select field.
- Areas of study that have Faculty Experts will appear in the dropdown and the list below. Showing ALL areas of study wouldn't make sense if there aren't a faculty experts to go along with them.
