### ISSUE TITLE
10 Reasons: Large numbers

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/cgu#209]
@kpettinga Some of the large white numbers are overlaying the content and should be behind instead. Those numbers are 2 & 8.

Also, I'm not sure we need the scrim hover state on the large full-screen modules. Those ones are 4 & 9.

http://cgu.wpengine.com/why-cgu/10-reasons/

**Comment by Jessdwilson** [comment]
@elliotarthur regarding the numbers overlaying the content that was a client request, so please disregard.
