### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by davekellam** [ObjectiveSubject/cgu#21]
We haven't talked a ton about the implementation of the Events section yet, but I think we were both leaning towards [Events Calendar](https://theeventscalendar.com/product/wordpress-events-calendar/). It's already proven on higher ed sites.

- [x] Install Events Calendar Plugin

**Comment by kpettinga** [comment]
Starting in on this area of the site. I was just browsing the Events Calendar site wanting to know the difference between Core and Pro versions. Below is a screenshot of the comparison. I think the biggest draw to the pro version is the **recurring events** feature. But for now we can just go with the core version and upgrade later if needed.

![image](https://cloud.githubusercontent.com/assets/1746410/15384836/a111b1ba-1dc7-11e6-95c0-3964dc45ab33.png)
