### ISSUE TITLE
Side navigation: Red links

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/cgu#211]
@kpettinga, A few of the side navigations are using red text. Can this revert to black and hover on red?

I've noticed it here - http://cgu.wpengine.com/about/administration/

![image](https://cloud.githubusercontent.com/assets/12611145/20116338/de35a5bc-a5c9-11e6-8c44-429a619f3bde.png)

**Comment by holliscooper-cgu** [comment]
This is still valid post-navigation changes - we want any links that might appear in the sidebar to be black with a red rollover state.

**Comment by Jessdwilson** [comment]
@holliscooper-cgu should the categories and schools on News pages also be changed to black text with a red rollover state? 

Also, on some program pages affiliated schools and institutes are currently red text 

![screen shot 2016-12-21 at 11 15 08 am](https://cloud.githubusercontent.com/assets/1680051/21396599/c25c3308-c76e-11e6-8c64-ce712a04e148.png)
![screen shot 2016-12-21 at 11 17 23 am](https://cloud.githubusercontent.com/assets/1680051/21396698/1529e83c-c76f-11e6-93c5-120ca7fd0eb2.png)

**Comment by Jessdwilson** [comment]
@kpettinga just confirming that I spoke with Hollis and the text should be changed to black with a red rollover hover. 

For the news items, items under Categories and Schools, can we also adjust the text so it's upper/lower case instead of all caps?
