### ISSUE TITLE
Application checklist: checkboxes appearing with bullets

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#212]
See screenshot. Should these checklists not be set up as unordered lists?
![app-checklist-bullets](https://cloud.githubusercontent.com/assets/18012084/20121611/646e0370-a5c7-11e6-9430-ae6c1c8434c5.JPG)

**Comment by kpettinga** [comment]
@holliscooper-cgu 

You are correct. You should **not** set them up as unordered lists. You can use the `shift + return` keys if you want single line breaks. Also, if you want to maintain an indent like a list would have, you can use the indent buttons in the text editor:
![image](https://cloud.githubusercontent.com/assets/1746410/20133465/473e4a20-a69a-11e6-8015-9cd5b41352d4.png)
---

![image](https://cloud.githubusercontent.com/assets/1746410/20133539/861a08a6-a69a-11e6-9823-71beaaafff26.png)
