### ISSUE TITLE
School Footer: News and Events redirect

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#214]
We have News and Events pages in each school footer that need to be populated with the associated school info. For example this page: http://cgu.wpengine.com/school/school-of-arts-and-humanities/news/
should redirect to the filtered school news page: http://cgu.wpengine.com/news/school/school-of-arts-and-humanities/

**Comment by kpettinga** [comment]
@Jessdwilson there's no redirect that needs to happen. Just need to link to the already existing archive pages. I will set it up in the menus.
