### ISSUE TITLE
Bullets: Align to main body text

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/cgu#216]
@kpettinga Could we modify the paragraph styles to align with the main body text? Is this a front end solution or something we can do in WP with the content?

I've saved a screenshot for you to reference. Taken from: http://cgu.wpengine.com/academics/program/art/

![cgu bullets](https://cloud.githubusercontent.com/assets/12611145/20152626/f39ab834-a68c-11e6-916e-ac86ce086cbd.png)

**Comment by elliotarthur** [comment]
Can we change bullets to Guillemet "›"? 

No biggy if not

**Comment by Jessdwilson** [comment]
@kpettinga per the client's request we should use square bullets and make them tan

**Comment by holliscooper-cgu** [comment]
Also from Andrea:
We've been using 5pt Zapf Dingbat square with 9.5pt Gotham to give you sense of scale.
