### ISSUE TITLE
Courses: Can't attach to program page

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#217]
It looks like we've hit some sort of cap on number of courses (200?) that will display in the course selection box on a program page. The list goes up to (in alpha-order) 'The Origins and Influences of the Zoroastrian Tradition' and no further. You also can't search for course names that fall after that one, which means that you can't attach those courses to the program display.

**Comment by kpettinga** [comment]
Hey @holliscooper-cgu, this cap is set in the theme code for database performance reasons. 

I've increased the cap to 500. Let me know if you think there are going to be more courses than that.
