### ISSUE TITLE
Program Feature Poster

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/cgu#218]
@kpettinga, just checking with you to see if the proportions on the Program Feature poster are the same as the posters we're using on departments and events etc...? 

Looks like it's a little shorter than the smaller posters.

I've noticed it on the Arts Program: http://cgu.wpengine.com/academics/program/art/
Also, noticing it on the Art Department page: http://cgu.wpengine.com/departments/art/

![screen shot 2016-11-09 at 3 45 48 pm](https://cloud.githubusercontent.com/assets/12611145/20154050/9e7c8092-a693-11e6-9990-562fe3f7fd01.png)

![cgu posters](https://cloud.githubusercontent.com/assets/12611145/20154138/05055ef6-a694-11e6-803d-f7976f5341be.png)

**Comment by kpettinga** [comment]
@elliotarthur cards need to be flexible because their width and height is dictated by the browser width and the content that appears inside of them. I will do my best to finesse this where I can.
