### ISSUE TITLE
Student Post Type

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/cgu#22]
Hey @davekellam 

Can you create a `student` post type?
(See "Current Student" module on page 8 of **CGU Website Visual Design Extension 20160518 EWA.pdf**)

**Requirements**
- [x] Student Post Type
- [x] Repeatable fields for question/answer carousel
- [x] Text field for major
- [x] Should support featured image field as well
- [x] Student post selector on Programs

**Comment by davekellam** [comment]
Fields added to backend, implemented the query and loops on the front end
