### ISSUE TITLE
Carousels: Scrim customization 

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/cgu#220]
@kpettinga A question regards carousels and the text which overlays the image. I think some of the images are suffering from too much scrim transparency especially on the History Module on the homepage. 

In the design mockups, I had a solid black box which the text would be contained in. Would including this to the carousel be a major issue? 

Also on the Art Department page, the carousel for Facilities, I think the light grey module should be a container for the supporting text and move with each image.

Here are screen shots of the mockups.

![image](https://cloud.githubusercontent.com/assets/12611145/20157331/66001ad0-a6a2-11e6-8587-45c5da99ad8a.png)

![image](https://cloud.githubusercontent.com/assets/12611145/20157340/7c81eb08-a6a2-11e6-9851-16eaac7ed62b.png)

**Comment by Jessdwilson** [comment]
@kpettinga just adding a note to this thread, the client has also inquired about having a text container for carousels. They are also concerned about the carousel on the homepage header, see attached screenshot, in this photo with the scrim the person on the left-hand side appears much darker while the person on the right seems overly illuminated. Maybe the scrim should be more evenly consistent across the image? 

![screen shot 2016-11-30 at 5 03 57 pm](https://cloud.githubusercontent.com/assets/1680051/20773434/bc2071f2-b71f-11e6-9052-f904071a55e5.png)

**Comment by kpettinga** [comment]
@elliotarthur @Jessdwilson I feel like we need to pow-wow about what to do with scrims. We have a bunch of different contexts for them: header carousels, regular carousels, history carousels, "image" module types...

I feel like I need some design guidance on how to approach all of them.

**Comment by Jessdwilson** [comment]
@kpettinga just following up on this since we last discussed. We need to be able to have more control over when a scrim is included and when it's not. 

The client asked if we could remove the scrims on carousel headers.
If there isn't a scrim, can we have the option to select black or white overlay text?
We discussed that if there is a scrim then the text will automatically be white.

**Comment by kpettinga** [comment]
@Jessdwilson yes that all sounds good. I will implement according to that logic. 👍

**Comment by kpettinga** [comment]
@Jessdwilson this _should_ be all set. There is a scrim option for all pages now as well as an option for black or white text.
