### ISSUE TITLE
Program page: School associations not appearing on programs that span schools

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#225]
For programs that span schools (ex. Arts Management - SAH & Drucker), the school affiliations are no longer appearing on the page.  They used to appear under the sidebar area.

**Comment by kpettinga** [comment]
@holliscooper-cgu the only affiliations that have been programmed to show up in program sidebars are for Centers. I think you're thinking of schools that show up in the sidebar on Center pages (http://cgu.wpengine.com/center/advanced-gis-lab/).

Would you like Schools to show up in the sidebar on **programs** when there is more than one school?
