### ISSUE TITLE
Display issue: list items

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#227]
2 issues:

1. bullets and numbers don't display when "default template" is chosen as the page template

2. When they do display, can we have some additional space built in between list items? Right now, there's none.
![list-items](https://cloud.githubusercontent.com/assets/18012084/20190161/2eb545e4-a735-11e6-93fb-63065c7d6849.JPG)

**Comment by kpettinga** [comment]
@holliscooper-cgu this should be all set
