### ISSUE TITLE
Resources and Support: Change dropdown module

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/cgu#228]
@kpettinga. I think the dropdown module on the Resources & Support page could benefit with being 2 columns like the dropdown module on Admissions. Is that possible?

Resources & Support - http://cgu.wpengine.com/academics/resources-support/
Admissions - http://cgu.wpengine.com/admissions/

**Comment by kpettinga** [comment]
The column and column_group shortcode should be used to achieve this.

cc: @holliscooper-cgu

**Comment by holliscooper-cgu** [comment]
Done.
