### ISSUE TITLE
Siteimprove accessibility: search icons

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#229]
From Andrea:

We asked Siteimprove why we were getting an accessibility flag on the magnifying glass that denotes the search. Can you please see their suggestion below for the addition of a WAI-ARIA role button.

##

Not sure why this would flag if there are other examples of similar links. My guess is it's the way the CSS is structured. I can tell you why it IS flagged, though.

Since there is no distinguishing visible characteristic stating that the magnifying glass is a link, we need to rely on color as that distinguishing characteristic. The colors used, dark red and black/grey should meet 3:1 color ration guidelines, so when you do hover, it's a distinct change in the visible state.

The colors, dark red #B72029, and grey, #696969 only have a ratio of 1.18 so do not meet that criteria. Now this is really important for low-vision or colorblind users, so you should probably make some visual adjustments. 

But then what about a screen reader? My suggestion here would be to add a WAI-ARIA "role=button" to the link so it is identified as a button by assistive technology. since it is designed to act like a button and trigger something versus acting like a link, let's tell the screen reader that it is supposed to be a button. This would be a better solution than the current <span> text, "search toggle", purely for semantic coding value.****

**Comment by kpettinga** [comment]
I've tweaked the hover state colors a bit to comply with the 3:1 color ratio. 

I've also added `role="button"` attributes to the search and menu icons
