### ISSUE TITLE
Show School Taxo column on posts and events

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/cgu#23]
@davekellam I've added the `_school` taxo to the default `post` type as well as the 'tribe_events' type. Can you make it show up in an admin column? 
(**cherry on top**: remove the categories and event categories columns);

**Comment by davekellam** [comment]
Sorted it out how to override the Events Calendar columns (c146ab74cbe3f93d8bf9fad1a658a2b8c987303f), may need to keep an eye out for any unintended consequences (think we'll be okay though)
