### ISSUE TITLE
h6 on Programs page

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/cgu#230]
@kpettinga. Can we change the ALL CAP text below each program to an h5, h6 is rather small and looks better especially on the Drucker page. If it comply's with 508 change the color to #b3b1ae. I think it's slightly dark at the moment and is a little distracting from the program.

Here's a screenshot of me playing with the inspector.
![image](https://cloud.githubusercontent.com/assets/12611145/20192905/d3bdfbe8-a759-11e6-83af-c35f316f3007.png)

**Comment by kpettinga** [comment]
hey @elliotarthur, unfortunately the contrast isn't enough for accessibility standards. I will go ahead and increase it to the h5 size though.
