### ISSUE TITLE
Affiliated school sidebar

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/cgu#231]
@kpettinga @Jessdwilson I'm not sure the side-bar for the Affiliated Schools is the best solution here. Can we remove the black box and revert positive logo's here? 

Not sure whether this was a client request, but it's really distracting and different from anything else. 

Link: http://cgu.wpengine.com/center/quality-of-life-research-center/

**Comment by holliscooper-cgu** [comment]
We were actually going to request just writing out the name of the school (in text) as a link to that school as opposed to using portions of the logos split from the CGU logo -- similar to the way that affiliated research institutes are displayed on the program pages.

**Comment by kpettinga** [comment]
@holliscooper-cgu 

i've refactored the sidebar on programs so that affiliated schools appears in the same way as affiliated research centers.

cc: @elliotarthur

**Comment by elliotarthur** [comment]
@holliscooper-cgu That makes it easier. However, in regards to this solution here should we revert to the single line School logo on the School footers? All the footers are on 2 lines however, in our mock-ups and design guidelines, we do have single line variants for situations like this.
