### ISSUE TITLE
Profile shortcode: Profile order display

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#232]
When multiple profiles are used in the profile shortcode (ex. [profiles ids="4461,4454,4464" includes="image"]) - can the display respect the order of profiles entered? That shortcode is used on this page: http://cgu.wpengine.com/departments/division-of-politics-and-economics/

The way the IDs are entered, the display should be Paul Zak, Heather Campbell, Yi Feng

**Comment by kpettinga** [comment]
all set @holliscooper-cgu
