### ISSUE TITLE
header image height

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/cgu#233]
@holliscooper-cgu @Jessdwilson @davekellam 

I'm opening up this issue so we can discuss the issues Hollis is experiencing with header heights.

**Hollis**:
I double checked for header size changes by pulling an earlier version of our code from last week wednesday (11/2). I made a comparison screenshot and it doesn't indicate any changes:
![comparison](https://cloud.githubusercontent.com/assets/1746410/20203821/345016c8-a7fd-11e6-9012-e70e98a0ecce.png)

You've done everything right in terms of formatting your hero images. 👍 

What I think is happening, however, is that some hero images have their focal points very close to the top of the image. In the MFA in Art program for instance, the subject's head is very close to the top and the CSS for the header dictates that hero images should scale from their **center points**.

It's important to remember that _some level_ of extra cropping is going to occur around the edges of hero images because of the responsive nature of the page headers. They need to respond to the width of the browser but the hero image also needs to make sure it covers the entire header area. Those two things work against each other so we try to find a happy medium.

The only way to ensure no cropping under any circumstance would be to take off the max-height property for the page header. But we don't want to do that because users would need to scroll past a large header on wide monitors. Thus, we institute a cap of 700px.

**Solution**: 
I've tweaked the hero image settings a bit so that the image's anchor point is at the top. So when it scales it will scale from that point, preventing any heads from getting cut off. 
Let me know if this solves your problem.

**Comment by kpettinga** [comment]
P.S. please give the site about 10 minutes to refresh with the new settings. Make sure to clear your browser cache as well.

**Comment by holliscooper-cgu** [comment]
Hi Kirk, thank you! Andrea has been working on uploading the headers, so I'll get any additional feedback from her as soon as she's in.

**Comment by kpettinga** [comment]
Sounds good @holliscooper-cgu!

If you encounter more issues, please hold back from installing any image formatting plugins. We can solve 99.9% of issues with the current tools at our disposal.
