### ISSUE TITLE
IE: Bugs

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/cgu#234]
- [x] Select field styling - **IE 9,10,11** 
- [x] Expanded sub nav in - **IE9** 
- [x] Heros: Text Shadow - **IE9** (reinstate hero scrim?)
- [x] Program: Course boxes width - **IE9**
- [x] Home: Area of Study and News layout - **IE9**
- [x] Image Module: translate text in when no Flexbox? (Modernizr?)
- [x] Program results: pushState bug
- [x] Program results: programs not appearing - **IE9**
- [x] Video group: Videos not rendering - **IE9**
- [x] Page Header default image - **IE 9,10,11**
- [x] Why CGU graphics not displaying - **IE 9,10,11**
- [x] Select field displaying incorrectly - **IE11**

**Comment by houmym** [comment]
Hey Kirk,

I have been looking at the site on IE 11 and saw that the animations for the Why CGU are not working 

Thanks! 

H

![cgu_ie](https://cloud.githubusercontent.com/assets/6404113/20323066/5ac8d2dc-ab49-11e6-8d54-5546a18020d9.png)

**Comment by houmym** [comment]
The drop down in the footer of the school pages seems to be slightly off in IE 11 compared to Safari, Chrome, Firefox and Opera

![cgu_ie_4](https://cloud.githubusercontent.com/assets/6404113/20324274/e1d97714-ab4d-11e6-9030-51689c978573.JPG)

**Comment by houmym** [comment]
Small glitch where where the word "search" does not appear in the search field in IE 11.

![cgu_ie_2](https://cloud.githubusercontent.com/assets/6404113/20324674/5ebed106-ab4f-11e6-976b-bb0f4e4817a6.JPG)

**Comment by kpettinga** [comment]
@houmym thanks for catching these.

**Search text**
in IE, placeholder text is hidden when a field has focus. When you open the search box the text field automatically receives focus so that a user can begin typing without having to click the field.

**Dropdown field**
the website wasn't detecting IE11 properly. this is fixed.

**Why CGU**
Fixed! Needed to downgrade the animations a bit because not everything is supported in IE.
