### ISSUE TITLE
Gap between modules.

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/cgu#238]
@kpettinga Had a look in WP as I thought there might have been a content issue. But there's a gap between two modules in Chrome. See screenshot.

http://cgu.wpengine.com/school/drucker-school-of-management/research/

![image](https://cloud.githubusercontent.com/assets/12611145/20226361/ce971fb6-a815-11e6-9a22-4a0a90f7160e.png)

http://cgu.wpengine.com/school/institute-of-mathematical-sciences/
![image](https://cloud.githubusercontent.com/assets/12611145/20226708/21ff7684-a817-11e6-965a-461c2102abac.png)

http://cgu.wpengine.com/school/school-of-community-and-global-health/
![image](https://cloud.githubusercontent.com/assets/12611145/20226731/3c0af756-a817-11e6-8afd-2107efda9b9d.png)

**Comment by kpettinga** [comment]
@elliotarthur @holliscooper-cgu
