### ISSUE TITLE
Repetition of buttons

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/cgu#239]
@Jessdwilson Do we need the repetition of buttons on the How to Apply page?
Maybe we can remove the button in the middle?

http://cgu.wpengine.com/admissions/how-to-apply/#

![image](https://cloud.githubusercontent.com/assets/12611145/20227799/118cc450-a81c-11e6-9416-0b93a8e735b9.png)

**Comment by Jessdwilson** [comment]
@elliotarthur this doesn't seem necessary, is this how we had it in the mockup?

**Comment by elliotarthur** [comment]
It is, but looking at it, it seems odd. Remove the middle one?
