### ISSUE TITLE
Center pages: Sidebar order and add option for logo

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#242]
Some of the research centers/institutes will have their own logo (ex. Sotheby's). Can there be an option on the research center templates to upload a logo, which would then appear at the top of the right column (above the director and the website URL)? It won't need a display header of any sort.

As for the order in the sidebar, it should be:
- logo
- director
- website
- affiliated schools (display this as a text link, not as the school logo image)

**Comment by kpettinga** [comment]
@holliscooper-cgu this is all set and ready to use.
