### ISSUE TITLE
Rogue subnavs

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/cgu#243]
@kpettinga We have a random sub nav on the research page on School of Community & Global Health and Institute for Mathematics Sciences.

http://cgu.wpengine.com/school/school-of-community-and-global-health/research/
![image](https://cloud.githubusercontent.com/assets/12611145/20228554/b3db5c64-a81f-11e6-82ac-57d67de62f4b.png)

http://cgu.wpengine.com/school/institute-of-mathematical-sciences/research/
![image](https://cloud.githubusercontent.com/assets/12611145/20228966/daf5af78-a821-11e6-8f63-255f901d016d.png)

**Comment by Jessdwilson** [comment]
@elliotarthur we can fix this on the individual pages in WordPress by checking off "Hide parent menu item". I'll go ahead and update

![screen shot 2016-11-11 at 3 27 46 pm](https://cloud.githubusercontent.com/assets/1680051/20229316/ba208c8a-a823-11e6-8a87-2333fc77b1bb.png)
