### ISSUE TITLE
Featured Program: layered text

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#244]
On this program page: http://cgu.wpengine.com/academics/program/computational-and-applied-mathematics/

The content text is layered over the title text, is the only solution to cut back on the text length? Viewing this in Chrome 

![screen shot 2016-11-11 at 3 43 18 pm](https://cloud.githubusercontent.com/assets/1680051/20229746/26046d48-a826-11e6-9b4f-13473e13940e.png)

**Comment by kpettinga** [comment]
@Jessdwilson yes I believe all we can do now is adjust the text length or move some of it to the column on its left. @holliscooper-cgu asked me to adjust the space between list items in another issue #227. I noticed this issue as well and have given list items the smallest amount of space I can while having them still be visually separated.
