### ISSUE TITLE
Module (or shortcode modification): Create Featured Programs module type

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#248]
We need to be able to display program lists in places other than their existing locations. For example, in SSSPE, we need to display featured programs on the Division of Behavioral and Organizational Sciences and the Division of Politics & Economics pages. These will be different featured programs than the ones on the main SSSPE page (so they can't just pull from that page). DBOS and DPE likewise cannot be built as departments - they actually are containers for departments (ex. DPE contains the Dept of Politics, Dept of Economics, and Dept of International Studies).

Another acceptable option would be to call specific program IDs in the current Featured Programs shortcode, instead of calling in an entire school's featured programs.

**Comment by kpettinga** [comment]
@holliscooper-cgu there's now an option on the `[featured_programs]` shortcode to specify program IDs. Use it like this:

For Programs with IDs **3456**, **1907**, & **4025**
`[featured_programs programs="3456, 1907, 4025"]`
