### ISSUE TITLE
SCGH: Missing Request More Info module

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#249]
SCGH is missing the red Request More Information module with the recruiter name on all of its main school pages - is there a reason why this is happening? Program pages seem to be fine.

http://cgu.wpengine.com/school/school-of-community-and-global-health/

**Comment by kpettinga** [comment]
@holliscooper-cgu there are no "admissions" people tagged with the SCGH school. The school templates look for people with the "Admissions" role and the current school assigned to them. If it finds them, the request info module is displayed; if not, we have no backup information to show there so it hides the module.

**Comment by holliscooper-cgu** [comment]
Thanks, I found it. She'd been tagged with the school, but not tagged as admissions.
