### ISSUE TITLE
Tribe Events Templates

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/cgu#25]
@davekellam 

I've created the tribe_events directory and pasted in the the template files we'll be needing. So far just the "list" view is required. I may end up including "month" view as well, though.

The Events Calendar plugin automatically sets up an events archive for you at /events/. Trouble is, when I go to that page, it seems to use the page.php template even though it's supposed to be a post-type archive. It also uses the page.php template if I go to a single event. I've tried removing the tribe_events directory but it doesn't change anything.

I've imported some events from Drucker to play around with. Below is a copy of my DB if it will help.
[pettinga-cgu-db-20160524.zip](https://github.com/ObjectiveSubject/cgu/files/279138/pettinga-cgu-db-20160524.zip)

**Comment by davekellam** [comment]
I think this may be an unintended consequence of trying to add the _school taxo as an admin column (mentioned [here](https://github.com/ObjectiveSubject/cgu/issues/23#issuecomment-221086015])).

**Comment by davekellam** [comment]
Hrmm, that doesn't seem to be the problem. Imagine there's a conflict somewhere 😕

**Comment by davekellam** [comment]
Bit of a weird one. I've tried stripping out almost all other functionality. Can clearly see the various tribe_events queries being made, not entirely sure why it's getting the wrong template.

**Comment by davekellam** [comment]
Grr, it's an internal setting! 😠 

Make sure you've got `Default Events Template` selected, rather than `Default Page Template`:

![screen shot 2016-05-24 at 3 23 34 pm](https://cloud.githubusercontent.com/assets/60804/15517018/962fb080-21c3-11e6-94b8-02febf78ce4b.png)

**Comment by davekellam** [comment]
@kpettinga reopening this, just to make sure you see it. Close it out when you have :)

**Comment by davekellam** [comment]
Also, I think the folder is `tribe-events` rather than `tribe_events`.
