### ISSUE TITLE
Opera: Areas of study module

### ISSUE THREAD

**Issue by houmym** [ObjectiveSubject/cgu#252]
The Areas of study module on the homepage seems to be centered in Opera.

![screen shot 2016-11-14 at 10 40 07 am](https://cloud.githubusercontent.com/assets/6404113/20271793/ecc88cfe-aa59-11e6-9419-bbb7fe858097.png)

**Comment by kpettinga** [comment]
@houmym i think you need to clear your cache or update your browser. I'm using version 41.0.x and it is working fine.

**Comment by houmym** [comment]
That worked, thanks Kirk!
