### ISSUE TITLE
Image and footer alignment in news article

### ISSUE THREAD

**Issue by houmym** [ObjectiveSubject/cgu#253]
The alignment of images and the footer on the _Why Marketing to Women Doesn’t Work: A New Book By Drucker School Prof. Jenny Darroch_ seems to be off. (http://cgu.wpengine.com/news/2014/08/why-marketing-to-women-doesnt-work-a-new-book-by-drucker-school-prof-jenny-darroch/). 

This seems to be the case on Safari, Chrome, Opera and Firefox

Also should the title here be in italic and bold, i'm thinking that maybe just italic?

![screen shot 2016-11-14 at 11 11 30 am](https://cloud.githubusercontent.com/assets/6404113/20272516/1c7797ae-aa5c-11e6-9cad-f0c2044f90b2.png)
![screen shot 2016-11-14 at 11 11 26 am](https://cloud.githubusercontent.com/assets/6404113/20272517/1c7955a8-aa5c-11e6-8f4b-61ee75276771.png)

**Comment by kpettinga** [comment]
bad shortcode issue
