### ISSUE TITLE
News items on non-news pages

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#255]
@kpettinga Is there a way to pull in news items on a page? For example, I'm working on the main Research page, and we want to pull in news items (similar to the school sites, although not with that blue background) that are tagged "research" and with the 'read more news' link going to http://cgu.wpengine.com/news/category/research/

**Comment by kpettinga** [comment]
@holliscooper-cgu 

Not currently. We would need to build out a new shortcode or module for this.

**Comment by holliscooper-cgu** [comment]
We will need this - the most pressing use-case will be the main Research page.

**Comment by kpettinga** [comment]
@holliscooper-cgu this should be all set. You can use the `[news]` shortcode like so:

`[news categories="research"]`

By default, the list will show 6 news posts. Change that by adding the `number` parameter like so:

`[news categories="research" number="3"]`

[See the docs for more help »](http://cgu.wpengine.com/wp-admin/admin.php?page=wp-help-documents&document=8521)
