### ISSUE TITLE
School program listing pages: Remove accelerated degrees

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#256]
Accelerated degree programs are only supposed to appear on the accelerated degree page (http://cgu.wpengine.com/academics/accelerated-bachelor-masters/). Right now, they also show on all program pages at the school level - they should be removed from here.

![accelerated-degree](https://cloud.githubusercontent.com/assets/18012084/20287824/ccd7c0de-aa83-11e6-85ee-ed558aa1a838.JPG)

**Comment by kpettinga** [comment]
@holliscooper-cgu this is all set.
