### ISSUE TITLE
Hobsons event integration

### ISSUE THREAD

**Issue by davekellam** [ObjectiveSubject/cgu#258]
Use Hobson's webservices SOAP API to import events from Hobsons into The Events Calendar.

**Comment by davekellam** [comment]
Noting here that I don't think it will be possible to bring in the time zone, what Hobsons provides does not mesh with php's time zones. It will need to be adjusted manually after the event is added to the WordPress backend.

**Comment by davekellam** [comment]
The `event_type` taxonomy probably needs some massaging. They've been using plurals for things like "Information Sessions", but the API provides the singular "Information Session". So, we probably need to rename the current one to singular.

**Comment by kpettinga** [comment]
Thanks @davekellam. Renaming the term shouldn't be a problem. Would you mind going in and doing that and re-tagging any events if necessary?

cc: @holliscooper-cgu

**Comment by davekellam** [comment]
Merged in with #272. Will add instructions to the Help section of the site.

**Comment by holliscooper-cgu** [comment]
The Hobsons link in the WP admin is blank:
https://cgu.wpengine.com/wp-admin/edit.php?post_type=tribe_events&page=hobsons

**Comment by Jessdwilson** [comment]
@holliscooper-cgu apologies, this has been fixed
