### ISSUE TITLE
Gotham not appearing on site

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#259]
Gotham is not being served to the main cgu.wpengine.com. It is working correctly on the subdomains (served from the same project on the Cloud Typography end.) Also, I just checked Cloud Typography, and we haven't hit our bandwidth cap for a development project.

**Comment by davekellam** [comment]
There was a `SCRIPT_DEBUG` flag turned on in `wp-config.php`, which was used to determine whether or not to load the type stylesheet. Not entirely sure why it was turned on in a production site, maybe @kpettinga was debugging something and forgot to turn it back off. Should be working now, he can reopen if there's something else behind it.

**Comment by holliscooper-cgu** [comment]
Seems to be working for us! Thanks!

**Comment by jalbertgagnier** [comment]
Resolved it for me too!

**Comment by kpettinga** [comment]
yep my bad here. Was debugging in IE9 and forgot to switch it off.
