### ISSUE TITLE
General: Accessibility

### ISSUE THREAD

**Issue by davekellam** [ObjectiveSubject/cgu#26]
_Edit_ - From a [comment](https://github.com/ObjectiveSubject/cgu/issues/26#issuecomment-271943653) further down in the thread:

[Siteimprove](https://my2.siteimprove.com/QualityAssurance/367467/Overview/Index?msgId=919050976) found there are some color contrast issues on a few pages, can we recommend/implement alternate colors to improve the contrast?

- [x] On the Academics and program pages the "All areas" and "All degrees" in the Areas of Study dropdown: http://cgu.wpengine.com/academics/?

- [x] The school name grey text on the grey background for News: http://cgu.wpengine.com/research/

- [x] The grey on white text on this page ("Required" etc.): http://cgu.wpengine.com/events/community/add

- [x] The grey on black text for the Art gallery carousels: http://cgu.wpengine.com/students/jenny-ziomek/
<hr>

This was one of the requirements for the site. The university may want to look at using a tool to evaluate, the two that come to mind are [Site Improve](http://siteimprove.com/) and [Monsido](http://monsido.com/). Both can be quite pricey, although probably less so than running afoul of 508a and getting fined or sued or whatever.

**Comment by Jessdwilson** [comment]
@davekellam the client just informed us that they need to be level AA compliant instead of A, not sure if this changes anything or your recommendation for tools to evaluate compliance, but wanted to make you aware. Thanks!

**Comment by kpettinga** [comment]
Resource I've been using to brush up on my accessible HTML practices: http://accessibility.parseapp.com/

**Comment by kpettinga** [comment]
http://www.508checker.com/best-practices

**Comment by kpettinga** [comment]
Other Scanning tools
http://wave.webaim.org/
http://achecker.ca/checker/index.php

**Comment by kpettinga** [comment]
A 508 Checklist:
http://webaim.org/standards/508/checklist#standardo

**Comment by kpettinga** [comment]
https://t.co/aPOzHywB5p

**Comment by Jessdwilson** [comment]
@kpettinga I took a look at the [Siteimprove](https://my2.siteimprove.com/QualityAssurance/367467/Overview/Index?msgId=919050976) account CGU setup and found there are some color contrast issues on a few pages, can we recommend/implement alternate colors to improve the contrast?

On the Academics and program pages the "All areas" and "All degrees" in the Areas of Study dropdown: http://cgu.wpengine.com/academics/?

The school name grey text on the grey background for News: http://cgu.wpengine.com/research/

The grey on white text on this page ("Required" etc.): http://cgu.wpengine.com/events/community/add

The grey on black text for the Art gallery carousels: http://cgu.wpengine.com/students/jenny-ziomek/

**Comment by kpettinga** [comment]
@Jessdwilson for the "All areas" and "all degrees" text on the Academics page, black on teal is an acceptable contrast according to the Web Aim contrast checker (webaim.org/resources/contrastchecker/).

**Comment by Jessdwilson** [comment]
@kpettinga for "All Areas" I checked webaim and got the attached results, also attached is a screenshot from Siteimprove 
![screen shot 2017-01-19 at 12 48 41 pm](https://cloud.githubusercontent.com/assets/1680051/22118419/ae5aaf36-de45-11e6-8b98-9f61f151ae79.png)
![screen shot 2017-01-19 at 12 48 15 pm](https://cloud.githubusercontent.com/assets/1680051/22118553/4c6ad818-de46-11e6-8179-629e7601d2fd.png)

I took another look at the Siteimprove account for remaining color contrast issues: 

- [ ] under Current Student, Kerri Dean, "History" is a contrast issue: http://cgu.wpengine.com/academics/program/phd-history/  
![screen shot 2017-01-19 at 12 59 03 pm](https://cloud.githubusercontent.com/assets/1680051/22118789/1bd14bf0-de47-11e6-805f-d158b523b469.png)

**Comment by Jessdwilson** [comment]
@kpettinga regarding the above, had a chat with David about the "All Areas" and he suggested the active selected state should be teal text in a white box and the hover state should be 80% opacity white text

**Comment by davekellam** [comment]
Going to close this out. When further accessibility issues arise, we can create a new issue or reopen the thread.

**Comment by Jessdwilson** [comment]
@davekellam we do still need Kirk to address the "all areas" text above

**Comment by davekellam** [comment]
Ahh, I missed this because of the checklist in the middle. I tend to move things like that up to the top/main area of the issue, so it's more noticeable.

**Comment by kpettinga** [comment]
closing this out. further issues will be addressed through SiteImprove.

regarding the aforementioned "all areas" text color contrast issue, black on teal is an acceptable combo for "large" text (anything above 14px).
