### ISSUE TITLE
Breadcrumb. Have the option to switch between black and white

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/cgu#260]
@kpettinga Can we have the option to switch the breadcrumb on pages to either black or white? I know we can for the headers and feel this would benefit the legibility of the breadcrumb.

Here's an example of where it would be beneficial. 

http://cgu.wpengine.com/academics/program/continental-philosophy/

**Comment by kpettinga** [comment]
@elliotarthur yes. I had actually implemented that but it seems to have been overwritten at some point.. I'll dig into it.

**Comment by kpettinga** [comment]
Breadcrumbs will now be congruent with the Title/Subtitle Color setting
