### ISSUE TITLE
WP Plug-in to organize media library

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#263]
Have you guys ever used one of these? I can tell our media folder is going to get unwieldy, quickly. If you have suggestions on something that would work and not break existing functionality, we'd love to hear it. A few that I found that look interesting at first glance:

https://wordpress.org/plugins/enhanced-media-library/
https://www.joomunited.com/wordpress-products/wp-media-folder
https://wordpress.org/plugins/media-library-plus/

**Comment by kpettinga** [comment]
@davekellam any thoughts here?

**Comment by Jessdwilson** [comment]
@holliscooper-cgu after looking into the options we went ahead and installed the Enhanced Media Library plugin as this option seems to be the most reliable. You should now be able to add media categories. Let us know if you have any questions about this
