### ISSUE TITLE
Admissions fact module

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/cgu#264]
@kpettinga Can we make the subtitles on this module black instead of the red we're using for the large numbers? Similar to the Why CGU page. I've noticed this on a few other pages too. Making the subtitles black will highlight give more prominence to the facts

http://cgu.wpengine.com/admissions/

![image](https://cloud.githubusercontent.com/assets/12611145/20410402/cf0b2ecc-acea-11e6-8759-25850444e379.png)

**Comment by Jessdwilson** [comment]
@elliotarthur  on the CGU design site the subtitles are black, is this what you had in mind? 

![screen shot 2016-11-30 at 6 17 49 pm](https://cloud.githubusercontent.com/assets/1680051/20775517/56f8bffa-b729-11e6-9328-a520e777c843.png)

**Comment by elliotarthur** [comment]
Yes it is!
