### ISSUE TITLE
Support for tag parameters on [events] shortcode

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#265]
The Art Department VALS module is showing all events tagged Arts & Humanities, not just the Visiting Artist Lecture Series:
http://cgu.wpengine.com/departments/art/

What's the best way from a labeling perspective to fix this? Can we use a tag instead of a category/type/school? I put a "visiting artist lecture series" tag on a past VALS lecture (Sarah Cain), if you want to see what I mean.

**Comment by kpettinga** [comment]
@holliscooper-cgu, 

The shortcode was using a "terms" attribute to try and grab lecture events. That isn't a valid way to use it.
❌  `[events terms="lectures" color="teal"]`

You will want to use it like so:
✅  `[events schools="school-of-arts-and-humanities" type="lectures-and-speaker" color="teal"]`

**Comment by holliscooper-cgu** [comment]
If we want to pull it in by a tag, can we do that? There will be SAH lectures (even art department events) that aren't part of the visiting artist lecture series.

**Comment by kpettinga** [comment]
We don't have that ability yet. It can be implemented though. I'll update this issue to reflect that.

**Comment by kpettinga** [comment]
@holliscooper-cgu this is all set. Use the "tags" parameter to specify tags in a comma separated list.
