### ISSUE TITLE
Ability to include a YouTube channel

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#267]
The current Drucker site includes the option to display YouTube channel. Is this functionality available in the current site? It will make video management a little easier for some departments/schools.

http://drucker.cgu.edu/videos/

**Comment by kpettinga** [comment]
@holliscooper-cgu there is now a new shortcode [cgu_video_playlist] that can be used to pull in playlists from Youtube.

Just provide the youtube username and playlist ID, along with an optional title.

**Example**:
`[cgu_video_playlist title="The Drucker Experience" user="theDruckerSchool" playlist="PL92471900CE49C9DA"]`

[See the docs for help »](http://cgu.wpengine.com/wp-admin/admin.php?page=wp-help-documents&document=3203)
