### ISSUE TITLE
Admissions: Remove accelerated degree listings from the dropdown

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#268]
We need to remove the accelerated degree listings from the dropdown in admissions - the admissions data being pulled up is for the MA program, and is not necessarily what an accelerated student would need to do.

http://cgu.wpengine.com/admissions/how-to-apply/application-checklist/
http://cgu.wpengine.com/admissions/cost-aid/

**Comment by kpettinga** [comment]
@holliscooper-cgu this is all set.
