### ISSUE TITLE
Schools: Request Info button

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#269]
I started updating the Request Info links so they're school specific, when I remove the current, general Request Info and add the school specific links to the menu they don't appear as the red Request Info button. Can you fix? 

![screen shot 2016-11-21 at 12 41 01 pm](https://cloud.githubusercontent.com/assets/1680051/20493674/cfa8860e-afe7-11e6-84d2-4b9088dda382.png)

**Comment by kpettinga** [comment]
@Jessdwilson they need to have a "cta" class attached to them. I'll go ahead and update them. In the future, you can do this in the menu editor like so:

- Hit the screen options tab at the top of the page and make sure CSS Classes is checked.
![image](https://cloud.githubusercontent.com/assets/1746410/20508132/0085e17c-b092-11e6-98ac-d2dc0fc24bcf.png)

- Now when you edit a menu item you'll have the option to input a CSS class. 
![image](https://cloud.githubusercontent.com/assets/1746410/20508149/1c15b52a-b092-11e6-9bf1-f421c351ebde.png)

- Give each Request Info link a css class of "cta".
