### ISSUE TITLE
Navigation: Breadcrumbs

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/cgu#27]
@davekellam can you help out with building the breadcrumbs for the different areas of the site. Basically conditionals just need to be put into the function for the necessary pages.

- [x] Event and News landing/single pages.

If you spot another area where the breadcrumbs aren't filled out, please add them. You can refer to the design PDF if you're not sure how things should look.
Design: https://www.dropbox.com/s/4idwnkbugtdiz3f/CGU%20Website%20Design%20Refinements%2020160523%20EWA.pdf?dl=0
Wireframes: https://www.dropbox.com/s/ps3aepht7wjovvg/CGU%20Wireframes%20Central%2020160524%20EWA.pdf?dl=0

**Comment by davekellam** [comment]
I've added in conditionals to create the breadcrumbs for News and Events. They both link to their respective root at the moment, but could link to the News & Events combo page. Haven't noticed anything missing yet, but it's entirely possible.

**Comment by kpettinga** [comment]
Hey @davekellam can you look into the breadcrumbs for the gallery taxonomy archive. It's a unique situation because we essentially just need to grab two specific posts, the **school of arts and humanities** and the **art department**. the `get_post_by_slug()` helper doesn't seem to want to play though...

**Comment by davekellam** [comment]
@kpettinga missed this earlier, is it still a problem, or working as expected? Should we close this out, or leave it open?

**Comment by kpettinga** [comment]
@davekellam yes, still need to figure this one out for gallery taxonomy archives. The breadcrumbs should go:
Home > School of Arts & Humanities > Art Department

**Comment by davekellam** [comment]
Should be there now. Figured it could be added in as a specific case.

**Comment by davekellam** [comment]
Ahh, I totally missed the commented out implementation earlier in the code. I see that you were trying to make it a little more robust. It's still reliant on slugs, so I think maybe our best bet is to just code this in there, and it can be updated manually if need be. Assuming the galleries only ever get used for the Art Department
