### ISSUE TITLE
Home page: replace Areas of Study sidebar with new module

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/cgu#271]
spinoff from #175 

---

@kpettinga following feedback from faculty, Andrea and Hollis brought up a couple additional design changes that need to be made: 

On the homepage, remove the Areas of Study sidebar. We will need to replace this with a module on the homepage along the lines of the attached screenshot from UC San Diego with a link to Schools and a link to Programs

On the Academics page the Filter By sections for Areas of Study and Degrees should remain open by default 

![screen shot 2016-11-18 at 9 42 48 am](https://cloud.githubusercontent.com/assets/1680051/20503444/86415a62-b010-11e6-8012-e670b934d385.png)

**Comment by kpettinga** [comment]
@Jessdwilson @holliscooper-cgu a module now can now be added to the "upper modules" area on the home page. The old areas of study list has been removed.

**Comment by kpettinga** [comment]
I've created a placeholder module on the home page with dummy content for academics and schools. I see in the UC San Diego example that they have some sort of scrolling stats on the right. Is that something that we should try to replicate? Please provide details if something custom is desired that cannot currently be achieved with existing module options.

**Comment by holliscooper-cgu** [comment]
No scrolling stats - just an "academics" module that has two columns: One with the "schools" intro and link on one side and "programs" intro and link on the right. It could actually be built using the basic module template, assuming we can assign the style we want to it.
