### ISSUE TITLE
Header navigation changes

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#277]
School header mockup attached (CGU central will be posted tomorrow).

![school-homepage](https://cloud.githubusercontent.com/assets/18012084/20736028/d5b051d6-b658-11e6-8acc-15b7a63c7166.jpg)

**Comment by holliscooper-cgu** [comment]
Here's the CGU central navigation
![cgu-homepage-new-header](https://cloud.githubusercontent.com/assets/18012084/20844225/b689f9d4-b873-11e6-91a9-78f330e92949.jpg)

**Comment by Jessdwilson** [comment]
@kpettinga we will need to change Community to Info For > as seen on the school page mockup, could this be a dropdown that includes the child pages?

**Comment by Jessdwilson** [comment]
@kpettinga see attached, approved header navigation changes

[CGU Navigation Refinements 20161213 EWA.pdf](https://github.com/ObjectiveSubject/cgu/files/650027/CGU.Navigation.Refinements.20161213.EWA.pdf)

**Comment by Jessdwilson** [comment]
@kpettinga there are few issues with the updated navigation, Community should be replaced with Info For > which should be a dropdown with the child pages (The order should be: Apply | Give | News | Events | Alumni | Info For >)

Request Info is listed under the main navigation (screenshot attached) but should only appear as a button 

![screen shot 2016-12-14 at 10 23 28 am](https://cloud.githubusercontent.com/assets/1680051/21187922/a4e05f0c-c1e7-11e6-9a9d-509f0316c9bd.png)

**Comment by elliotarthur** [comment]
@kpettinga Good start on solving the takeover and stacking the global CGU nav underneath the school nav. However, I've tweaked the desktop and tablet breakpoints to match align with the mobile and combines everything together nicely.

Basically, we're adding a module below the CGU nav to contain the global nav.

[CGU Navigation Refinements 20161214 EWA.pdf](https://github.com/ObjectiveSubject/cgu/files/652104/CGU.Navigation.Refinements.20161214.EWA.pdf)

**Comment by Jessdwilson** [comment]
Kirk, you'll notice that we revised the takeover navigation in the design Elliot posted. The client would prefer that we maintain the list of all schools in the menu

**Comment by kpettinga** [comment]
Spinning this out into #307
