### ISSUE TITLE
Spark Blog added to site

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#279]
@holliscooper-cgu can you confirm where the Spark blog should live on the site? Our sitemap has been adjusted since we last worked on it over the summer, we had the blog located under Campus Life, should it still be found here?

**Comment by holliscooper-cgu** [comment]
Yes, still found under Campus Life.

**Comment by kpettinga** [comment]
Hey @holliscooper-cgu, just want to chime in here.

My understanding is that the spark blog will be a fully functioning "blog" in the traditional sense where you have pages of posts with the newest showing first and archive templates if any taxonomies are used. Is that correct?

I would strongly suggest that we host the spark blog on a new subdomain of cgu (spark.cgu.edu?) and use the cgu core theme to build out a new theme. The reason for this is because we'd need to create a new post type and all the templates that go along with it.

Having a fully functioning blog tucked away inside a nested page (campus life) just seems like we're trying to fit something very large into a small space. There's already a wide array of content types on the main site.

**Comment by kpettinga** [comment]
From Andrea:

---

Holls, Jessica, 

I understand Kirk’s point of view on a subdomain blog but having it separated out doesn’t help CGU with our SEO strategy. I want the blog on the main site so the site gets the credit for having ongoing content. It seems like we have the format of the archive and the categories with the News page. Couldn’t we just use that logic?

Thoughts?

**Comment by kpettinga** [comment]
@Jessdwilson @holliscooper-cgu,

Andrea's suggestion will be fine as long as everyone is aware how it affects the backend content structure. 

We'll create a new post type for the spark blog ("spark post", or something similar) where posts should be entered. 

With taxonomies like categories and tags, we can have spark posts use those as well BUT both spark posts _and_ news news posts will show up on archive pages. So if you have a spark post and a news post both using the same category term (e.g. "the arts"), they will both show up on that term's archive page.

If your desire is to keep news posts and spark posts separate in every context, then we'll need to create new taxonomies which will only be utilized by sparks posts. In turn, their archive pages will only show spark posts.

Also, the archive page urls will most likely not be able to have the same url as the spark blog itself (`/campus-life/spark-blog/{term-name}/`). It will be something more along the lines of `/spark-blog-archive/{taxonomy-name}/{term-name}/`

As long as everyone's aware of these implications, we can go ahead and build out page templates for the spark blog.

**Comment by Jessdwilson** [comment]
@kpettinga Andrea and Hollis are aware of how this will affect the backend content structure and would like us to move forward with building out the pages templates for the blog

**Comment by kpettinga** [comment]
@holliscooper-cgu what kinds of taxonomies, if any, should spark posts have available to them? We can create new taxonomies called "categories" or "tags" (or anything else), that are specific to spark posts. 

If you want spark posts to share a taxonomy (like categories) with another post type, bear in mind that both spark posts AND the other post type(s) will show up on the archive pages. Which I'm assuming you _don't_ want.

cc: @Jessdwilson

**Comment by Jessdwilson** [comment]
@kpettinga CGU would like to include the following categories for the Spark blog:

- Student Life
- CGU Happenings
- Opinion + Voices
- Faculty + Staff
- Student Spotlight
- The Short List

**Comment by kpettinga** [comment]
@holliscooper-cgu the spark blog is setup and ready for use. There is now a new Spark Blog template, Spark Post type, and a Spark Categories taxonomy. I've gone ahead and created a Spark Blog page here: http://cgu.wpengine.com/student-life/campus-life/spark-blog, and assigned it the "Spark Blog" template.

You can move or rename the spark blog page to whatever you like **but you must declare the page in the customizer options** (Appearance > Customize). There you'll find a new tab called "*Spark Blog Options*". There is a field where you can declare the page for the spark blog.
