### ISSUE TITLE
Why CGU: 10 Reasons adjustments

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#280]
- [x] The headline text size is a smaller size when placed over a photo, could this be adjusted so it's the same size for all numbers?

- [x] Could number 8 be the same format as number 10 where the photo is on the right-hand side? The large numbers work better when layered with text than with an image alone  

- [ ] For number 5, programs, we need to be able to control how the cards look as it's problematic to have these pull in the hero image from the program page. Can these be adjusted so they are treated like a department card?

**Comment by kpettinga** [comment]
@holliscooper-cgu 

Regarding:
> For number 5, programs, we need to be able to control how the cards look as it's problematic to have these pull in the hero image from the program page. Can these be adjusted so they are treated like a department card?

I've removed the featured image from the card. Now it's a plain teal card. Is that what you wanted?

cc: @Jessdwilson

**Comment by holliscooper-cgu** [comment]
Actually, we'd like the ability to add images to these cards, like we do on other pages with cards.

**Comment by kpettinga** [comment]
@holliscooper-cgu we're going to have to change the field type here in order to assign an image to each program card. We have 2 options. Let me know which you'd prefer:

1. Use a WYSIWYG editor so that the [card] shortcode can be used. **Upside**: Full control over look of the card. **Downside**: Text for each card will need to be input manually. 

2. Create a repeater field where, for each item, you enter the ID of a program and choose an image for the card background. **Upside**: Text for the card automatically pulls from program. **Downside**: Less control over the look. Also, in the backend, each program will be represented as its ID, not title. That might be annoying when you revisit it in the future because it's not very semantic.

**Comment by holliscooper-cgu** [comment]
@kpettinga Thanks for the option summary - #1 sounds best to me - inputting the card text manually isn't a big deal.

**Comment by kpettinga** [comment]
@holliscooper-cgu a wysiwyg field is now in place for you to enter card shortcodes. Remember to specify a `size="small"` and wrap all the cards in the `[column_group]...[/column_group]` shortcodes.

**Comment by holliscooper-cgu** [comment]
@kpettinga Using size="small" for the cards shrinks them both width and height-wise. Is there another way to make the cards not as tall (as they were before on this page), but still be able to control the width?

**Comment by kpettinga** [comment]
@holliscooper-cgu There is not an option to make a card's height agnostic no matter the width. In all other instances, a card's height is proportional to its width.

I took a look at your shortcodes and noticed you're not using the size attribute. The card size you specify will determine the width of each card. Also, you don't need to use the **[column]** shortcode, only the **[column_group]** one. [column_group] simply adds a container around elements that are floated. 

The shortcodes should end up looking like this:
```
[column_group]
[card size="small"]...[/card]
[card size="small"]...[/card]
[card size="small"]...[/card]
[/column_group]
```
Of course, size, isn't the only attribute you'll use for each card, but hopefully you get the idea.
Sorry if my first message was confusing.

**Comment by holliscooper-cgu** [comment]
@kpettinga - Thank you. Removing the column shortcode actually fixed everything (I had tried the size=small previously with the column shortcode in place, and the aspect ratio was off). When you get a chance, can you add the size attributes to the publishing help section in WP admin?

**Comment by kpettinga** [comment]
@holliscooper-cgu glad it worked out. I'll add the size attribute to the docs. Sorry that slipped through the cracks.
