### ISSUE TITLE
Academics: Resources & Support page layout

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#281]
@elliotarthur Andrea and Hollis are using modules on the Resources & Support page: http://cgu.wpengine.com/academics/resources-support/ but aren't happy with how things are laid out, they feel the whole page is pretty clunky and have asked that we provide recommendations on how to better display the page content. 

In particular, they think the text above the Student Success Center module, "The Student Success Center (SSC)..." feels lost and not ideal. Also, the text block just below the Student Study Spaces carousel, "There are many places around campus..." is associated with the carousel above but it feels separate and accidental. Happy to discuss possible solutions.

**Comment by kpettinga** [comment]
@Jessdwilson I have some ideas about what we can do. My concern right now though is that we are considering things in the context of the old design. With the new design changes that are on cgudesign.wpengine.com, design decisions might change.

We should figure out when to merge the design changes into the main site.

**Comment by kpettinga** [comment]
@Jessdwilson @holliscooper-cgu I've made a few adjustments to this page

- moved text for student success center into it's own module just above the SSC carousel. 
- gave more space around top and bottom of "Important Offices" dropdowns
- made the background of the student study spaces black so the text better connects with the carousel.
- adjusted the column width of the "CUC RECORDS CENTER" text block, gave it some space and added a header.

I hope these changes are getting it closer to what you're hoping for. Bear in mind that with the new design changes things will feel a bit different. So, we should probably wait to fine tune this layout until those are changes are merged with the main site.
