### ISSUE TITLE
Homepage: History of CGU timeline CTA link

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#284]
For the timeline module on the homepage can we add a "more>" link (see design mockups from client) to the end of the timeline (2016 slide) that takes the visitor to the History of CGU page http://cgudesign.wpengine.com/about/

**Comment by Jessdwilson** [comment]
@holliscooper-cgu just wanted to confirm if you still want the "more>" link added to the timeline carousel and that it should link to http://cgu.wpengine.com/about/cgu-history/

**Comment by holliscooper-cgu** [comment]
Yes, we do.

**Comment by kpettinga** [comment]
@holliscooper-cgu there is now an option to specify a url for a "more" link in the history carousel. You'll find it below the list of years/images.
