### ISSUE TITLE
Admissions>How to Apply/Application Checklist/FAQs pages

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#287]
http://cgu.wpengine.com/admissions/how-to-apply/
http://cgu.wpengine.com/admissions/how-to-apply/application-checklist/
http://cgu.wpengine.com/admissions/how-to-apply/application-faqs/

2 things:

- [ ] We need to be able to edit the sidebar on these pages

- [x] The horizontal nav (Steps to Apply/Application Checklist/FAQ) on Steps to Apply isn't updating to reflect page name changes (it does change on Application Checklist and FAQ) - for example, we've changed the name of Application FAQ to just 'FAQ' (the display name for the page is still Application FAQ) - and this is the one page where it doesn't update. Compare to http://cgu.wpengine.com/admissions/how-to-apply/application-checklist/ (which is the correct display)

**Comment by kpettinga** [comment]
@holliscooper-cgu can you tell me more about what you need in terms of editing the sidebar on these pages? (custom menu items?, custom text?, etc...)

**Comment by holliscooper-cgu** [comment]
I'm closing this issue because I think the new nav display will make it irrelevant. We were going to remove the sidebar nav elements on this page (except for the buttons) entirely.
