### ISSUE TITLE
News and Event pages

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/cgu#29]
Hey @davekellam 

Could you help me get the News page and Events page wired up? Right now I have a landing page called "News & Events". It has 2 children, "News" and "Events". The News page is to be the blog page and the Events page is, obviously, to be for events.

**News Page:**
I've set this page to be the "Posts page" in settings. Works fine except that the page sub-nav doesn't show up. It needs to maintain the same sub-nav as its parent "News and Events" (which was possible before setting News to be the posts page).

**Events Page:**
This one's a bit more tricky. We need to somehow get the Events list (as currently seen at the default events url '/events/') to live on this Events Page. Maybe there's a way to tell the events plugin to use that page? The page subnav will also need to be present on this page like the "News" and "News & Events" pages.

**Comment by davekellam** [comment]
Under the Events > Settings page, there's an option to change the slug of the events archive page:

![screen shot 2016-05-28 at 6 44 24 pm](https://cloud.githubusercontent.com/assets/60804/15630334/689b9e74-2504-11e6-969f-7f895af41243.png)

That would probably work. The sub navigation here could be edge cases, we might just need to roll something custom if we can't get the standard one working with the url changes.

Personally, I think it would be easier to just keep them separate, `news` and `events`. In places, where they need to appear as the same (another page on the site), we could query both post types. It seems like a bit of an arbitrary combination that adds a lot of unneeded complication. Is there a reason to do this, other than that's how they've perceived this in the past?

**Comment by kpettinga** [comment]
@davekellam I see your logic. Lets keep things simple then and just have each at their own top-level pages (`/news/` and `/events/`) and we'll figure out a way to maintain the sub navigation on those pages. "News & Events" will continue to aggregate both post types but not have child pages (save for "Faculty Experts Guide" and "Media Contact" which I assume to use default page templates).
