### ISSUE TITLE
News page display

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#293]
The current news display is not working for us. (http://cgu.wpengine.com/news/) We would like to use 3-column formatting from the original mockups. I've attached a new mockup using that design in combination with the sidebar (= 2 columns of news, 1 column of sidebar, instead of the 3 columns of news in the original design). The only design element not noted in the mockup is that there should always be a line break between the school name and the date (as there currently is on the site).

![news-mockup](https://cloud.githubusercontent.com/assets/18012084/20942455/49cca4aa-bbb0-11e6-9bdf-65af7899bc18.jpg)

**Comment by Jessdwilson** [comment]
@kpettinga this looks great, we just need to make sure there is always a line break between the school name and the date.
![screen shot 2016-12-21 at 11 01 15 am](https://cloud.githubusercontent.com/assets/1680051/21396121/10f5a5dc-c76d-11e6-8dbc-484f42b2b769.png)

**Comment by holliscooper-cgu** [comment]
Also, I just noticed that the news page returns 9 news items on each page - can it return 10 instead (so the columns are equal in height)?

**Comment by kpettinga** [comment]
@holliscooper-cgu adjusting the news items that get returned can be adjusted in Settings > Reading in the backend. I've set it to 10.
