### ISSUE TITLE
Order of Faculty Members

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/cgu#294]
@kpettinga, @Jessdwilson, I'm noticing the order of the faculty members differ per page. For instance, on the **faculty** page they're chronological, however, the faculty members on the department page seem to be in hierarchy order.

I feel this should be the same. Thoughts?!

http://cgu.wpengine.com/school/school-of-arts-and-humanities/faculty/
http://cgu.wpengine.com/departments/art/

**Comment by holliscooper-cgu** [comment]
Just confirming from our end that what Elliot is describing is the correct behavior.
