### ISSUE TITLE
Search: items in modules not searchable

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#295]
@kpettinga @davekellam the client noticed that items within modules were not found when doing a search on the site. For example, The Honnold/Mudd Library on the Resources & Support page: http://cgu.wpengine.com/academics/resources-support/

Can we force the search function to also search within modules?

**Comment by kpettinga** [comment]
@Jessdwilson @holliscooper-cgu the problem here is not that we can't include modules in search. It's that when module content is returned in the search results, the link for it will be to the module itself, not the page or post it is attached to.

@davekellam do you have any suggestions about how to address this?

**Comment by davekellam** [comment]
Offhand, I'm not sure if there's a solution. As you mentioned @kpettinga, technically the module post type could be included in search, but it would end up taking to a module page (which doesn't currently exist, and likely wouldn't be useful). 

There isn't really a way to search for anything that happens to use that module. The first major obstacle is that attached modules are stored inside a serialized array, so not easily searchable. The second is that it would involve a lot of expensive meta queries, which WP Engine, would probably flag us for.

The built-in WordPress search is notoriously on the weak side. In the original specs, we were going to maintain the Google search that CGU had been using. I believe that would've given us full page searching, but is reliant on the site being indexed. Some times people who need a lot more power for searching go with ElasticSearch, but that adds a whole other level of complexity, which typically requires an extra server and might not be possible with WPE.

I'll spend some more time looking into it, to see if there's any possibility of it working in an efficient manner.

**Comment by kpettinga** [comment]
@Jessdwilson @holliscooper-cgu I've updated the code to reflect the implementation @davekellam and I have worked out. Modules will get returned in search results and the pages they're attached to will be listed out below each. 

If any content is available in the module, an excerpt of it will be shown, just like the other pages/posts in the search results.
