### ISSUE TITLE
Music department: WP music player

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#297]
Part of the original site spec was to have special content for the Art and Music departments. We handled art, but never really turned our attention to music. Most of music's needs are taken care of by the YouTube video shortcodes, but they also have a set of MP3 files that currently use a JS player (and allow downloading as well).

Any ideas on a plugin or other solution for this? It's possible that we might want this on more than one page.

http://www.cgu.edu/pages/8686.asp

**Comment by kpettinga** [comment]
@holliscooper-cgu support for audio and audio playlists comes built into wordpress. So all you have to do is upload your audio files to the media library and then include them on a page or post of your choosing. 

To create an audio playlist, select "add media" above the wysiwyg editor and in the popup that appears, select "create audio playlist" from the links on the left. You'll then be able to choose your audio files and they will appear in a playlist on the page.

Here's an article that gives more detailed instructions if you need help: http://www.wpbeginner.com/beginners-guide/how-to-add-audio-files-and-create-playlists-in-wordpress/

**Comment by kpettinga** [comment]
Here's a preview of an audio playlist with some sample tracks:
![image](https://cloud.githubusercontent.com/assets/1746410/21379385/23a4f10c-c780-11e6-843a-1ecbbbfb5876.png)
