### ISSUE TITLE
School and program page footers: small text change

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#299]
On the pages where the Request More Info/Recruiter/Admissions Specialist info lives, we need to change both the words "Recruiter" (Program pages) and "Admissions Specialist" (School pages) to "Admissions Representative"

**Comment by Jessdwilson** [comment]
@kpettinga Both Recruiter and Admissions Specialist need to be changed to **Admissions Representative**, it looks like you have changed all of these to Admissions Specialist

**Comment by kpettinga** [comment]
My bad! all set now.
