### ISSUE TITLE
General: login customization

### ISSUE THREAD

**Issue by davekellam** [ObjectiveSubject/cgu#3]
We can add a logo and/or change the colour scheme, similar to Drucker.

**Comment by kpettinga** [comment]
Can we just add the main CGU logo to the login page? Should be available in the assets/images/ folder

**Comment by davekellam** [comment]
@kpettinga I've added the functionality in here. For now I duplicated `emblem.png` over to `login-logo.png`. Don't know if we need something with words, but having the CGU emblem is a bit nicer than the WP logo.

Going to close it out.
