### ISSUE TITLE
School Footers: adjust link placement add school logo

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#304]
@kpettinga With the design changes merged on the staging site the school footer alignments are off on desktop and mobile and the school logo is missing from the footer 

![drucker footer](https://cloud.githubusercontent.com/assets/1680051/21191978/e4a0fc02-c1f4-11e6-84d7-ce93e8b44324.png)

![school footer mobile](https://cloud.githubusercontent.com/assets/1680051/21191982/ec75680a-c1f4-11e6-9aa5-2df2f4d3bca1.PNG)

**Comment by holliscooper-cgu** [comment]
Also, the footer text should not be in all caps - it should be upper/lower, same size as the elements in the CGU footer below it.
