### ISSUE TITLE
Site Header updates

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/cgu#307]

**Comment by Jessdwilson** [comment]
@kpettinga It looks like we just need to update the takeover nav so that all schools are listed 

![screen shot 2016-12-15 at 5 20 30 pm](https://cloud.githubusercontent.com/assets/1680051/21244270/da4892aa-c2ea-11e6-801d-f2f45f53069c.png)

**Comment by Jessdwilson** [comment]
Also, the client requested that Info For > include a dropdown upon hover with the child pages, is this possible to implement?

**Comment by kpettinga** [comment]
@Jessdwilson @holliscooper-cgu 

I've updated the site header so that schools are listed when the menu icon is clicked. The menu icon is now available in all all contexts so that the list of schools is readily available.

**Comment by Jessdwilson** [comment]
Regarding the site navigation, the hamburger menu should only appear on school pages as it was previously and should be displayed as a takeover navigation. 

The client has also requested that we increase the size of the CGU logo, and asked if it could be about the size as the Connecticut College logo on their site: http://www.conncoll.edu

**Comment by Jessdwilson** [comment]
@kpettinga we should update the hamburger menu so it's a takeover navigation, when the hamburger menu is clicked it should be similar to what we had previously (screenshot seen in issue #224 ) 

The takeover nav should just have the CGU logo, and we should remove the request info button and utility nav (apply, give etc.) from the takeover nav. The schools listed should be in a single line and be in the same order as seen on the Schools landing page (SSSPE, Drucker, SAH, CGH, SES, IST, MS)

**Comment by kpettinga** [comment]
@Jessdwilson I'm confused what you mean by "schools listed should be in a single line". Elliot's mockup, and the way they are right now, shows them in 2 columns and each school name is a single line. Is that what you mean, that school names shouldn't break to 2 lines? Do we maintain the 2 column layout?

**Comment by kpettinga** [comment]
@Jessdwilson @holliscooper-cgu the new takeover nav is implemented. I'll leave to you guys to close this if there's nothing else.

**Comment by Jessdwilson** [comment]
thanks @kpettinga 

Can we also update the order of the schools in the hamburger nav so they appear in the same order as on the Schools page? (SSSPE, Drucker, SAH, CGH, SES, IST, MS) 

On desktop, the schools should be listed in a single column instead of two columns

For mobile and tablet, I wonder if the hamburger nav for schools should also be neutral with just the CGU logo instead of the school lockup. @elliotarthur what do you think?

**Comment by kpettinga** [comment]
@Jessdwilson the schools can be ordered in Wordpress using the menu order field.

**Re: mobile menu and takeover nav**:
The mobile menu encompasses more than just CGU central menu items. It also has to include things for schools if you're on a school page. So switching to the main CGU logo when the mobile menu is open doesn't make sense. 

The whole thing got more complicated with the addition of the takeover nav. Part of the complication is that the hamburger icon has to take on 2 separate responsibilities depending on what size your browser is. If, on desktop, it opens the takeover nav. If you're on mobile, it needs to open the mobile menu to reveal all the other links that have been hidden. 

The solution we had before was streamlined both visually and programmatically.

So anyways, I don't want to complicate it more than it already is.

**Comment by kpettinga** [comment]
@holliscooper-cgu here's a screenshot of the school list in 1 column in the takeover nav
![pasted_image_at_2016_12_23_08_12_am](https://cloud.githubusercontent.com/assets/1746410/21445176/559d8b6a-c8e8-11e6-8d3f-61d06ba9f725.png)

We strongly suggest keeping it at 2 columns to make it feel more balanced.
