### ISSUE TITLE
Alumni Events: card image size

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#309]
Do you know why the event card on the alumni page is so narrow? I looked at the page in WordPress and it's not clear to me why this would occur

http://cgu.wpengine.com/alumni/

![screen shot 2016-12-16 at 12 02 49 pm](https://cloud.githubusercontent.com/assets/1680051/21271166/d7703cca-c387-11e6-9cb0-b83a14c8a971.png)

**Comment by kpettinga** [comment]
@Jessdwilson this block needs to be a module. Right now the [section] shortcode is being used to create the full width gray section but the content area is still limited to the same width as the other text on the page. So this card, which is set to span about 33% of it's container, is contained within an element that is already narrower than the page.

Put this into a module and the container will be the full width of the page, setting the card to the correct width.
