### ISSUE TITLE
Grandchild pages and tab navigation

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/cgu#31]
Hey Dave,

Could you come up with some functions that will let us achieve the tab navigation we talked about earlier today? Our conclusion was that we would create grandchild pages and they could be aggregated into a tabular navigation like shown below. If you can just get them spitting out into a list, i can take care of styling. 

![image](https://cloud.githubusercontent.com/assets/1746410/15603344/5d221540-2424-11e6-9883-47748ec0ff0e.png)

**Comment by davekellam** [comment]
I started writing a `tertiary_navigation( $id )` function today. Just revisited the issue, and noticed you had referenced a commit, where you created the navigation using a shortcode. What I came up with quite similar to what you created. Do you still need a function for templating? If so, I'd probably take what you've done in the shortcode, spin it out into a function and then reference the function in the shortcode.

**Comment by kpettinga** [comment]
@davekellam lets keep the function you created and use it to spit out the shortcode content. Thanks!
