### ISSUE TITLE
typeface on the timeline should mirror the typeface in the homepage modules

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/cgu#312]

**Comment by Jessdwilson** [comment]
@kpettinga the timeline headline text should be same size as the headline text in the module above 
![screen shot 2016-12-21 at 12 57 38 pm](https://cloud.githubusercontent.com/assets/1680051/21400300/757b5744-c77d-11e6-8825-c5dcdd7d88dd.png)
