### ISSUE TITLE
Text position in carousel and image modules

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/cgu#315]
From Andrea:

Can we have the text in the cards be at the bottom by default but also editable with a designation for top/bottom/right/left?

I mean the cards in carousels—[timeline here](http://cgu.wpengine.com/) (see 1999 for the most obvious reason why), but I also mean the [student success center and interdisciplinary concentrations modules here](http://cgu.wpengine.com/school/school-of-arts-and-humanities/) and when you get down to it, I suppose I mean back on the headers on pages. [Take a look at this job listing](http://cgu.wpengine.com/employment-opportunities/staff-jobs/job-849/). The new two column headline serves many program pages well but sometimes we do the need the option of a single column. If push comes to shove and that’s just not possible, I’d rather have the two column as an option but ideally we’d have both. 

---

- [x] One option where the text is on the left side and wraps 50% of the header/carousel
- [x] Another where the text is on the right and wraps 50% of the header/carousel
- [x] and an option to have a single line of text that spans the header/carousel

**Comment by Jessdwilson** [comment]
@kpettinga just adding to this, we should have three options for the position of the text. 

[ ] - One option where the text is on the left side and wraps 50% of the header/carousel
[ ] - Another where the text is on the right and wraps 50% of the header/carousel
[ ] - and an option to have a single line of text that spans the header/carousel

**Comment by kpettinga** [comment]
@Jessdwilson thanks for the update here. Should those be the only three options in terms of positioning? Andrea's original message made it sound like they wanted top/bottom/right/left options as well...

**Comment by Jessdwilson** [comment]
@kpettinga that's correct, we should also have options for top/bottom as well as left/right and single line

**Comment by kpettinga** [comment]
@Jessdwilson @holliscooper-cgu there are now options to specify text position, width, and color for carousels, image modules, and headers.
