### ISSUE TITLE
Increase CGU logo size

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/cgu#317]
The client has also requested that we increase the size of the CGU logo, and asked if it could be about the size as the Connecticut College logo on their site: http://www.conncoll.edu

**Comment by kpettinga** [comment]
@holliscooper-cgu the Connecticut College logo is very large. Should the CGU logo only be that big on non-school pages? My fear on school pages is that would be forced to upscale the school logos as well in order to maintain proper proportions. But that would make for some extremely large, awkward, headers I think. Especially for a school like Drucker, which already has a larger sized logo.

**Comment by holliscooper-cgu** [comment]
You are correct - this should happen only on non-school pages.
