### ISSUE TITLE
update sub-domain themes

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#318]
to align with the revised designs on the main site

**Comment by holliscooper-cgu** [comment]
We have a few additional requests related to this:
- the subdomains arts.cgu.edu and research.cgu.edu need the "People" post type added to the theme.
- the CGU logo in the footer should link to cgu.edu, not the homepage of the subdomain
- the logo in the header can remain the way it is

**Comment by holliscooper-cgu** [comment]
@Jessdwilson When you guys send the new files to Greg, will you cc: me so that I know he has them?

**Comment by kpettinga** [comment]
@holliscooper-cgu @Jessdwilson I have updated the sub domain themes and you were both cc'd in an email to greg.

**Comment by holliscooper-cgu** [comment]
The new theme seems to now be missing the header carousel option - some of the subdomain sites were using it, and how it is gone.

**Comment by davekellam** [comment]
I imagine this is now part of [cgu-core](https://github.com/ObjectiveSubject/cgu-core), issues are probably better raised there.

**Comment by holliscooper-cgu** [comment]
@davekellam -- sorry, I meant to say it's missing ONLY from the subdomain theme since you pushed through the new design changes - nothing to do with the main CGU theme.

**Comment by davekellam** [comment]
Yup... I believe @kpettinga has spun out the main functionality we created for the CGU theme into a separate them called [CGU-Core](https://github.com/ObjectiveSubject/cgu-core). 

I think that's the one being used on sub-domains. So, that's why I was saying any sub-domain issues should probably be posted to that repository. It's very possible there were unintended side-effects with the migrations, it's pretty typical!

**Comment by holliscooper-cgu** [comment]
@davekellam Ok, makes sense. However, I can't label or assign people to issues in CGU-Core, so should I continue to post issues here?

**Comment by davekellam** [comment]
Ahh, weird... but sort of makes sense. I created a new CGU group, while should allow you the ability to create issues and and whatnot. Let us know if there're problems.

At some point, we should probably transfer the repositories over to a CGU github account, so you folks can manage. We can then create clones, add pull requests, etc., and execute workflows that haven't mattered as much while the project wasn't live.

**Comment by holliscooper-cgu** [comment]
Thanks, Dave. I created an issue here: https://github.com/ObjectiveSubject/cgu-core/issues/1 but I can't assign anyone to it, nor can I label it.

**Comment by Jessdwilson** [comment]
@holliscooper-cgu I added you as a collaborator to cgu-core so you can add labels and assignments
