### ISSUE TITLE
Sub Navigation for News/Event-related pages

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/cgu#32]
@davekellam 

Picking up where #29 left off: 
We need a sub navigation bar containing "News", "Events", and child pages of the "News & Events" page. I took a stab at writing a function for this but need to focus on other front-end stuff (see my commit referenced below). Could you help me get a function working that will pull in those pages and highlight the ones necessary in the right contexts (outlined below)?

You may also want to just roll this into the existing sub_navigation helper function, your call.

**News and Events sub nav menu items:** 

| Name  |      Links to      |
|----------|:-------------:|
| News |  the blog posts page ('/news') |
| Events Calendar |    the events page ('/events')   |
| [ child of "News & Events" page ] | itself |

**Contexts**

| Context | Highlighted menu item |
|----------|-------------|
| News & Events page | none |
| [ News & Events child page ] | itself |
| News (blog post page) | News |
| Single News post | News |
| Events | Events Calendar |
| Single Event post | Events Calendar |

**Comment by davekellam** [comment]
Think I have the function working properly at the moment. The one thing left, is _how_ the menu appears on children of the News & Events page. If you were planning on using a custom template for those children (i.e. select from the dropdown), than it's pretty straight-forward, just include the function in the template. If you were thinking it should use the default `page.php` template, then I'll need to add in some logic there to check if the page is a child of `news-events` and use the different nav. Let me know how you want to approach the templating here.

Thought about wiring it into the `sub_navigation()` function, but that's already pretty complex.

**Comment by kpettinga** [comment]
@davekellam I think we should go with putting it on the `page.php`. Easier for users to not have to select  a template.

**Comment by davekellam** [comment]
Think we're good here.
