### ISSUE TITLE
Stats module: Text color options

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#322]
The Stats module on the admissions page has black text.
http://cgu.wpengine.com/admissions/

It should have the black/red text combo, as seen here:
http://cgu.wpengine.com/why-cgu/at-a-glance/

**Comment by kpettinga** [comment]
@holliscooper-cgu stats modules will now show the large numbers in red by default. Here's a table of each background color available to modules and how the stats color will change depending on the selection:

background color | stat color
--- | ---
_default_ | red
light-gray | red
lighter-gray | red
lightest-gray | red
tan-50 | red
tan-30 | red
light-yellow | red
red | white
black | white
dark-gray | white
tan | white
blue | white
teal | white
dark-teal | teal
light-green | green
