### ISSUE TITLE
Event listing page: Previous/Next events display bug

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#326]
On an event listing page, at the bottom, the previous/next event listings are displaying the date/time from the current event page (instead of their respective dates and times).

Ex:
http://cgu.wpengine.com/event/drucker-school-class-preview-and-information-session/

**Comment by holliscooper-cgu** [comment]
This is still not working correctly for me. 

Ex. http://cgu.wpengine.com/event/public-safety-leaders/
The previous event is showing as the upcoming event, and the displayed past event is actually the event before the real previous event

http://cgu.wpengine.com/event/drucker-school-class-preview-and-information-session/
Is grabbing the exact same events as the one above, so the past displayed event is correct, but the displayed upcoming event is the event you're actually on.

**Comment by davekellam** [comment]
Thanks for the update. We often have different data locally and sometimes errors aren't apparent. 

Think I have the queries fixed up and working properly here now.
