### ISSUE TITLE
Event listing page: Add location name

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#327]
On an event listing page, under "Location," the name of the venue should also be displayed, along with the address. Also, if you can break the country onto the next line, that would be great.

Ex. http://cgu.wpengine.com/event/drucker-school-class-preview-and-information-session/
Under "Location," it should say:
Burkle Building
1021 N. Dartmouth Ave.
Claremont, CA 91711
United States

**Comment by kpettinga** [comment]
@holliscooper-cgu this should be all set
