### ISSUE TITLE
News items: photo treatment

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#328]
We need to standardize the dimensions of the featured image display attached to a news item. We'd like the following:

- on news aggregate pages, the featured image display should have a 3:2 aspect ratio (in the xlarge view, currently 360px wide by 240px tall). We will format news images accordingly, but that should be how the image is cropped, regardless.

- on news item pages, featured images currently don't appear at all. We'd like the same featured image to appear under the news title, before the news body. It should have the same aspect ratio as the thumbnail version (3:2), but be scaled up to fit the width of the column. We need the news item to use the featured image here because that's what social media feeds will auto-pull if the item is shared.
See the formatting here as an example (just the news article): https://www.hmc.edu/about-hmc/2016/12/02/algorithms-and-avocados/

The display order for us should be: 
1. date
2. news article title
3. featured image (full column width)
4. featured image caption (small text)
5. news article body

**Comment by kpettinga** [comment]
@holliscooper-cgu this should be all set.
