### ISSUE TITLE
Program Page: need "alumni careers" field

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/cgu#33]
**On Programs**:
- Need a text field for the section title and a repeater with "company name" and "job title" fields.
- If you can then wire up the fields to this section of the program template that would be helpful. https://github.com/ObjectiveSubject/cgu/blob/master/partials/program-top-level.php#L189-L228

---
![image](https://cloud.githubusercontent.com/assets/1746410/15698816/5069d3d4-27f2-11e6-9b06-51b0d21364b7.png)

**Comment by davekellam** [comment]
This should be wired up and functional now.
