### ISSUE TITLE
Profile pages: website link display/functionality

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#330]
Two things:

1. On profile pages, under the "Website" field, we'd like to be able to choose what that display text says, rather than just displaying the URL on the page. This is better for accessibility. It's okay if we have to go back into everyone's profile to add that information manually - we want to be able to customize that link text on a per-profile basis.

2. We would also always like the link entered under website (on a profile) to open in a new window.

**Comment by kpettinga** [comment]
@holliscooper-cgu there is now a Website Display field where you can enter the display text for the person's website.
