### ISSUE TITLE
Events: allow for HTML in titles

### ISSUE THREAD

**Issue by davekellam** [ObjectiveSubject/cgu#338]
For a [specific event](http://cgu.dev/event/public-safety-leaders/), a stakeholder requested a line-break in the title. 

Generally, putting HTML in the WordPress title field isn't a great idea, because it's used in many places, including ones that don't display styling (`<title>`, og tags, etc). It was one of the earlier WordPress debates (see [12 year old bug report](https://core.trac.wordpress.org/ticket/1371) 😄).

One approach in this instance would be to use some sort of regex to replace `<br>`s found when displaying the `<title>` tag, etc. That said, I can see potential down the road for things like `<b>` and `<i>` getting requested for things like referencing a publication.

We do have a "Display Title" custom field on other post types, that allows for this type of visual override. It might be possible to do something similar with the Events Calendar plugin. Adding a custom field should be easy enough. Sorting out if it's possible to override Event titles with a custom field, without having any knock-on effects through-out the plugin might prove trickier.

**Comment by kpettinga** [comment]
Yeah I think providing a field for a custom title that would parse html would be fine. I think the cgu_get_title helper we have now would work for it...

**Comment by davekellam** [comment]
The current helper function wraps it an `<h1>`, although there is a before/after override. Think that'll be fine for display purposes (if we can get the custom field showing up on events)?

**Comment by kpettinga** [comment]
yeah that will be fine.
