### ISSUE TITLE
School footer: recruiter order

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#339]
We need to be able to control the order of the recruiters at the bottom of school pages (ex. http://cgu.wpengine.com/school/drucker-school-of-management/). Right now, I'm not sure how the order is being determined. I tried using the "order" field in the admin interface, but the site doesn't pick it up.

**Comment by kpettinga** [comment]
@holliscooper-cgu I added a parameter to the query so that these will be ordered by the numbers you set in the "order" field. If 2 posts have the same order number they will be ordered by name.
