### ISSUE TITLE
Scrim options

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#340]
After using the [scrim tester](http://objectivesubject.github.io/cgu/scrim-tester.html)

Andrea and Hollis think it would be ideal to have an on/off option and among the “on”options there would be three scrims available: 25%, 35%, and whatever percentage we have now.

**Comment by kpettinga** [comment]
There are now options for 25%, 35%, and 45% scrim values. The on/off option is still available as well.

**Comment by Jessdwilson** [comment]
Thanks @kpettinga 

I don't see the values, where are the options listed? Should they appear with the Scrim on/off option?

![screen shot 2017-01-17 at 11 15 00 am](https://cloud.githubusercontent.com/assets/1680051/22028928/e334fc8e-dca6-11e6-9c32-c64555a79926.png)

**Comment by holliscooper-cgu** [comment]
@Jessdwilson I see the options on the Programs and Pages (after clicking "on"), but I don't see it on modules (carousels, image).

**Comment by kpettinga** [comment]
@holliscooper-cgu @Jessdwilson sorry guys! Just added the scrim value options modules as well.

**Comment by Jessdwilson** [comment]
@kpettinga would it be possible to reset the scrim default on all pages to 25%? This would save us the time of going back through each instance and adjusting

**Comment by kpettinga** [comment]
@Jessdwilson  all set.

**Comment by Jessdwilson** [comment]
@kpettinga the client noted they found some scrims that were still set to 45%, is it possible to double-check that all default to 25%?

**Comment by kpettinga** [comment]
@Jessdwilson if any pages were created or saved while we had the previous 45% default, then 45% was saved as their value whether they selected it or not. 

The pages that ARE going to take hold of the new 25% are any pages created from now on, OR any pages that were not edited/saved while we had the 45% default.
