### ISSUE TITLE
Button shortcode: Add aria-label parameter

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#344]
We are getting flagged by SiteImprove/AA compliance for using "Read More" or "Learn More" as button text (especially on pages with multiple buttons). Rather than make exceptionally long button names, can we add the aria-label parameter to the shortcode, so that it spits out something like this?
< a class="button" href="somepage.html" aria-label="Read more about Career Development" >Read More< /a >

**Comment by davekellam** [comment]
So, something like `area-label="Read more about <post title>"`?

**Comment by holliscooper-cgu** [comment]
@davekellam - or adding a modifier into the shortcode, so we can specify - 
ex. [button text="Read More" aria_label="Read more about this thing" new_window="true"] ... etc. -- if that makes sense.

**Comment by davekellam** [comment]
Yup, sounds good. I've added a default parameter like I suggested above. To override, you can use the additional parameter you suggested, `aria_label`. Hope that works!
