### ISSUE TITLE
Why CGU page

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#345]
@kpettinga 

- [x] can we remove the hover state from number 9 on the Why CGU page? Since number 4 is similar and doesn't have a hover state we want these to be consistent  

- [x] For number 4 can the text be adjusted so it's aligned to the bottom?

**Comment by Jessdwilson** [comment]
hi @davekellam for #4 can the text be bottom aligned?

**Comment by holliscooper-cgu** [comment]
@Jessdwilson - you mean the number, headline, and text moved to the bottom, correct? This is what Andrea wants.

**Comment by Jessdwilson** [comment]
@holliscooper-cgu correct, those items should be moved to the bottom of the photo

**Comment by davekellam** [comment]
Ahh. I took it to mean just the paragraph text aligned at the bottom.
