### ISSUE TITLE
School pages: Admissions rep profile snippets

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#347]
The custom program/area of study content is not showing up here under the recruiter names.

Ex, http://cgu.wpengine.com/school/drucker-school-of-management/
All of these people should have a "Programs" listing under their names, which should pull from the "Custom Program/Area of Study" field in the admin interface (overriding any tagged programs, etc.)

![recruiter-display](https://cloud.githubusercontent.com/assets/18012084/22215758/6ac8ef80-e151-11e6-86de-f028b006e189.JPG)

**Comment by davekellam** [comment]
Need some clarification here. They currently seem to be pulling from the person's profile. What else should be happening here? Where is the custom program/aos that it should be pulling from if there's nothing?

**Comment by Jessdwilson** [comment]
@davekellam For Patrick Latimer, for instance, Executive MBA should display. See attached screenshot found under People > Patrick Latimer

Does that help? 

![screen shot 2017-01-26 at 2 49 52 pm](https://cloud.githubusercontent.com/assets/1680051/22347712/fa192632-e3d6-11e6-848f-2d4563ea538e.png)

**Comment by davekellam** [comment]
Yes, totally! Had a very derp moment, was looking for a different type of field and glossing over this. Imagine it's fine.

**Comment by davekellam** [comment]
Think we're good now.
