### ISSUE TITLE
News breadcrumb: Old News & Events page still being linked to

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#348]
The breadcrumb nav on some of the items under News still links to the old News & Events page:

![news-breadcrumb](https://cloud.githubusercontent.com/assets/18012084/22223786/f8d3eaea-e170-11e6-884e-876b76ea0274.JPG)

Where "News & Events" appears in the breadcrumb structure, this should be changed to "News" (and link to the current news page). I see it on the following pages/templates:

http://cgu.wpengine.com/news-events/faculty-experts-guide/
http://cgu.wpengine.com/news-events/media-contact/
http://cgu.wpengine.com/news-events/the-flame/
http://cgu.wpengine.com/news-events/social-media/

If I move these pages under "News" in the navigation, they effectively disappear. That said, ideally, their breadcrumb nav would be http://cgu.wpengine.com/news/faculty-experts-guide/ - etc. This may just be an issue with News and Events still being co-mingled on these pages. I think it's okay to split them totally - so News would have these sub-nav elements: Faculty Experts Guide, Media Contact, The Flame, Social Media

Events could be split out totally, so it would just have the Events sidebar on its pages (View Events by, Filter Events, etc.)

**Comment by davekellam** [comment]
Not sure what we can do here at the moment. I think it made sense when news & events was its own vertical. It was relatively easy to have subpages, because they were also each their own thing.

Things under "News" are a blog post, so it's harder to have custom pages exist. It also may not make sense. I can investigate further to see if we can keep them in the same vertical. Is there a place under "Pages" where these might make more sense?

**Comment by Jessdwilson** [comment]
@davekellam I'm not sure if it helps, but looking under pages I see **News - Posts Page** 

![screen shot 2017-01-26 at 5 08 50 pm](https://cloud.githubusercontent.com/assets/1680051/22352467/43766b10-e3ea-11e6-8b26-ce1057d08af4.png)

**Comment by davekellam** [comment]
I might have misunderstood the "effectively disappear" bit. So, they're not actually gone, they just don't bubble up in any fashion that people could click on them. Alright, imagine that it's mostly a nav fix.

**Comment by davekellam** [comment]
@holliscooper-cgu when I update these locally to be under News rather than News & Events, the breadcrump at the top changes to reflect there parent page. Curious what you meant by "effectively disappear". Are you talking about the links appearing the sidebar to the right?

**Comment by davekellam** [comment]
@holliscooper-cgu @Jessdwilson can I get clarification here ^^ ?

**Comment by Jessdwilson** [comment]
@holliscooper-cgu I discussed with Dave, we see that the items aren't appearing in the News sidebar and are working to rectify

**Comment by Jessdwilson** [comment]
@davekellam as Hollis mentioned, can we separate out Events from News? So News would have these sub-nav elements: Faculty Experts Guide, Media Contact, The Flame, Social Media

Events could be split out totally, so it would just have the Events sidebar on its pages (View Events by, Filter Events, etc.)

**Comment by davekellam** [comment]
I've removed this from the Events sidebars in particular. The sidebar does appear in a bunch of places around the site. Both News and Events are hardcoded and the other links are the child pages of News. The two hardcoded links could be removed.
