### ISSUE TITLE
Art Department Gallery pages: breadcrumb incorrect

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#350]
For some reason, the breadcrumb for the Spark is showing up in random places. See: 

http://cgu.wpengine.com/gallery/mfa-2016-students/
http://cgu.wpengine.com/gallery/mfa-2017-students/
http://cgu.wpengine.com/gallery/recent-mfa-graduates/
http://cgu.wpengine.com/gallery/faculty/

![art-gallery-breadcrumb](https://cloud.githubusercontent.com/assets/18012084/22228156/20073d2a-e184-11e6-9f55-de2f8e4c128f.JPG)

**Comment by kpettinga** [comment]
Merging this into #349 Breadcrumb Issues
