### ISSUE TITLE
Art Gallery individual pages: arrows missing

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#351]
The arrows seem to be missing from the image carousels on the individual gallery pages:

ex. http://cgu.wpengine.com/students/adrienne-devine/

Swiping works, but the arrows are missing.

**Comment by holliscooper-cgu** [comment]
Just realized that they aren't missing - you just can't see them because they are black on black. Anyway the arrow outlines can be white on this template instead of black?

**Comment by holliscooper-cgu** [comment]
This is also occurring on faculty profiles with galleries.

Ex. https://www.cgu.edu/people/carmine-iannaccone/

**Comment by Jessdwilson** [comment]
@kpettinga I'm still not seeing the arrows even after I cleared my browser cache

**Comment by kpettinga** [comment]
@Jessdwilson sorry, the code wasn't pushed. All set now.
