### ISSUE TITLE
Art Gallery: Control artist order

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#352]
I'm trying to control the order of the students on this page:
http://cgu.wpengine.com/gallery/mfa-2017-students/

When I use Students>Edit Order in the admin interface, it doesn't seem to do anything. I will need to arrange the order for all galleries.

**Comment by davekellam** [comment]
This should be respecting the `menu_order` parameter that the Edit Order plugin sets.
