### ISSUE TITLE
Events: Multi-day event display

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#354]
When an event spans multiple days (like an exhibition), only the first day shows up in the events calendar.

Ideal functionality would have the event listing show the date/time range (both on the card and on the listing itself), and be persistent on the calendar (as a single event listing - not one for every day) until the event is over.

Ex. http://cgu.wpengine.com/event/mfa-graduate-exhibition/
On the backend, this event spans May 1 - May 13.

![event-multiday](https://cloud.githubusercontent.com/assets/18012084/22260368/dbc20d94-e21d-11e6-966a-a7df1df920ee.JPG)

**Comment by davekellam** [comment]
Adding the end date to the sidebar was relatively easy. Should be there now. Creating one entry for a multiday event is trickier. I can see the relevance though, the calendar gets pretty cluttered with the repeats.

One issue with the current setup, is that it loops through all the days, and on each day only set the date once. I'm not sure if that will still be possible, _each card might need its own separate date_. I'll continue to work through the logic and see what works. There's also events spanning over a month divide, but that's simpler.

**Comment by holliscooper-cgu** [comment]
I was most concerned about the event display on the homepage (and when the events shortcode is used) - the event "card" view. It looks like, though, the behavior is what I wanted - the event stays persistent in that view, without appearing more than once. I'll talk to Andrea about the display on the actual calendar page - there might just need to be some design tweaks there to make it more readable (without changing that behavior).

We do still want the end date set on the card view:
![image](https://cloud.githubusercontent.com/assets/18012084/22477951/d955489e-e79c-11e6-986e-19473d19ca6b.png)

That first event is an exhibition that lasts until Feb 15. However, since the end date isn't shown in this view, it looks like an old event that's still showing up for some reason.

We have pretty constant art exhibitions here, so this will almost always be an issue.

**Comment by davekellam** [comment]
Cool, updating those cards should be fine. We can leave the general calendar card approach for a bit. 

What should the formatting on the card be like `Start Date - End Date > Start Time - End Time`, `Start Date > End Date` or something else?

**Comment by holliscooper-cgu** [comment]
Start Date > End Date (no time for multi-day events)

**Comment by davekellam** [comment]
The single cards should now reflect that format for multiday events, like on the main CGU page.

We can probably close this out and create a specific issues for changes to the main events calendar.
