### ISSUE TITLE
Events: Event card text color

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#355]
When "gray" is chosen as the event card color, the type on it is red - it should be white.

Ex. http://cgu.wpengine.com/departments/art/
![event-cards](https://cloud.githubusercontent.com/assets/18012084/22262343/6a8ad41e-e225-11e6-9123-fb53e657f3dd.JPG)

**Comment by davekellam** [comment]
I've tracked this down to a conflict between the modules background color, the events shortcode background color and the styling for carousels (which override cards). Some background colors will yield white links at the moment. Will pick it up later.

**Comment by holliscooper-cgu** [comment]
For launch (and as a workaround), I'm going to change the color of the events on the page above to teal so that the text is white. This can be fixed later.

**Comment by holliscooper-cgu** [comment]
This is still an issue - all text on the gray background should be white, just like it is on the teal cards.

Incorrect:
![image](https://cloud.githubusercontent.com/assets/18012084/25757615/0e44d074-3180-11e7-851b-b409556f1ae7.png)

Correct:
![image](https://cloud.githubusercontent.com/assets/18012084/25757638/28713334-3180-11e7-85a8-2b291b1be416.png)

**Comment by holliscooper-cgu** [comment]
This is also happening with the red background - the text here should also be white:
![image](https://cloud.githubusercontent.com/assets/18012084/25762159/845619aa-3192-11e7-80d0-e501c3cee66e.png)

**Comment by kpettinga** [comment]
@holliscooper-cgu this should be all set. One thing to note is that `dark-gray` needs to be used instead of just `gray`. That was a documentation glitch ill make sure to fix.
