### ISSUE TITLE
Events: Event listing sidebar tweaks

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#356]
2 things: 

- [x] Can elements under sidebar headings always use upper/lowercase instead of the h5 formatting? See Date/Time as a correct example.

- [ ] The categories/types/labels in the sidebar should always be links to more of that category/type/label, etc. 

Ex. 
![event-listing](https://cloud.githubusercontent.com/assets/18012084/22307945/d8adace4-e2f9-11e6-82b9-fa20fe9984f5.JPG)

- Information Sessions under Event Type should be a link to other Information Session-type events, just like Admissions under Category should be a link to other Admissions events.
- "Admissions" and "Information Sessions" should be in upper/lowercase under their respective headers.

**Comment by davekellam** [comment]
The upper/lowercase is doable. Imagine it was trying to be consistent with the sidebar displays on the filterable events page. @Jessdwilson @elliotarthur any thoughts here?

We were unable to create an event type listing that integrated with the plugin, url structure and kept the same feel (see #86). The plugin only really works with one taxonomy properly, event types are tacked onto a certain extent, we were only able to make them work with the filter part of events. The issue could be reopened as something to keep any eye on, but not doable at the moment.
