### ISSUE TITLE
WP migration plugin

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#357]
This is more of an FYI for you guys. This is the plugin that WPEngine wants us to use to help find/replace absolute links currently going to cgu.wpengine.com to instead go to cgu.edu when the DNS changes get pushed through. 

https://wordpress.org/plugins/wp-site-migrate/
https://wpengine.com/support/wp-engine-automatic-migration/

Unless you know of any issues with this plugin, we'll follow WPEngine's instructions on using this during the migration.

**Comment by davekellam** [comment]
If WPEngine is suggesting this, it's probably fine. I think it mostly deals with replacing any internal linking for the beta site. Like you mention, anything internally pointing to cgu.wpengine.com will get redirected to cgu.edu. This won't redirect any current cgu.edu urls.

**Comment by holliscooper-cgu** [comment]
Thanks @davekellam - good to hear. We're using a different plugin to handle the current CGU.edu redirects. I'll close this out.
