### ISSUE TITLE
Spark blog: Ability to show latest post on another page

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#358]
Is it possible to show the most recent Spark post on the Campus Life page? Shortcode is fine, or something built into the admin interface or as a module, etc.

**Comment by kpettinga** [comment]
@holliscooper-cgu I've added a new shortcode `[spark]`.

You can use it in the following ways:

1.
`[spark]`  
Grab the most recent spark post

2.
`[spark number="2"]`  
Grab the **2** most recent spark posts

3.
`[spark number="2" span="6"]`  
Grab the 2 most recent spark posts and display them side by side.

4.
`[spark number="2" span="6" categories="cgu-happenings"]`  
Grab the 2 most recent spark posts tagged with the _CGU Happenings_ spark category and display them side by side.
