### ISSUE TITLE
Redirect Issues

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/cgu#36]
Hey Dave,

I've set up the gravity form on the Request Info page. It has some select fields for Program, Degree Type, and Starting Semester. I'm anticipating the client wanting the possibility for these to be dynamically populated, which Gravity Forms make pretty easy. You can set a parameter name for a field and if it's present with a value in the url's query string, the field will be pre-populated. 

So, for the Request Info form, I've setup the select fields with parameter names (`program`, `degree_type`, and `semester`, respectively) that can be use to pre-populate the values. 

Here's an example:
`http://cgu.local/request-info/?degree_type=Masters&semester=Spring%202017`

But if I try to include a program name:
`http://cgu.local/request-info/?program=Positive%20Health%20Psychology&degree_type=Masters&semester=Spring%202017`
**It just redirects me to the Positive Health Psychology page**.

Can we make that not happen? If it's complicated, ill just think of a different parameter name. Just thought 'program' really makes the most sense.

**Comment by davekellam** [comment]
Not entirely sure why it's happening. Try using something like `program_name` instead and see if you get the same result. If it does the redirect still, there's probably a larger issue/conflict.

**Comment by kpettinga** [comment]
yeah we'll just use `program_name`
