### ISSUE TITLE
Admissions - Programs tagged with two degree categories are displayed separately in dropdown

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#362]
On this page: http://cgu.wpengine.com/admissions/how-to-apply/application-checklist/
and this page: http://cgu.wpengine.com/admissions/cost-aid/

if a program is tagged with 2 degree types, each program/degree type combo shows up as a separate item in the dropdown. 

Ex. PhD in Education, joint program with SDSU, shows up twice in the dropdown:
![image](https://cloud.githubusercontent.com/assets/18012084/22408774/85bed962-e633-11e6-94f2-ed4545adee6c.png)

The highlighted program and the one below it are the same thing. This causes problems, too, because there's no way to distinguish (in this case) between the Education PhD and the Education PhD that is a joint program with SDSU. If it was displayed this way, there'd be no confusion:
Education - Doctoral, Joint Degree

**Comment by davekellam** [comment]
Should avoid the duplication now, and append the joint degree at the end. Caches may need to be cleared.
