### ISSUE TITLE
Events: change filter text to mixed case

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#363]
We want to make the Event Types, Event Categories, and School options (just the checkbox options, **not** the headers themselves) to be upper-lower case. This same display style should also be reflected in the individual event listing pages (mentioned already here: #356 )

So, the display would look like (for example):

EVENT TYPE
:white_small_square: Class Preview
:white_small_square: Exhibitions and Performances
:white_small_square: Information Session
:white_small_square: Lectures and Speakers
:white_small_square: Special Event
:white_small_square: Workshop

etc.

We've been alerted by some of our student services staff that all uppercase is extremely difficult to read for those with dyslexia, so we're trying to break it up a little.

**Comment by davekellam** [comment]
Try clearing cache? I updated the theme/css version number. I find WP Engine is very aggressive about caching CSS on live sites.

<img width="1477" alt="screen shot 2017-02-03 at 1 07 08 pm" src="https://cloud.githubusercontent.com/assets/60804/22602584/d64df386-ea11-11e6-9ee6-3fe215c6e486.png">
