### ISSUE TITLE
Homepage: Slider in mobile view

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#366]
When the homepage is in the "small" view, the captions move above the slider, and appear on the default supergraphic background. If the text can't stay on the slider when it gets this small, then it should appear under the images (as it does in the carousel module), and should have a white or very pale gray background.

Current behavior:
![image](https://cloud.githubusercontent.com/assets/18012084/22495619/18359d20-e7f7-11e6-923c-68d750e849f4.png)

**Comment by kpettinga** [comment]
this should be all set.
