### ISSUE TITLE
Reminder to remove browser breakpoint overlay

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#367]
Just a reminder to remove the breakpoint overlay (small, medium, large, xlarge) that appears in the lower left corner of the browser window before we go live Thursday morning.

**Comment by davekellam** [comment]
The way that was setup, it should only be appearing for people with a certain debug flag set in their install, but that's clearly not the case. East to remove.

Question though... currently Usabilla seems to be setup with the same parameters. Should it be visible on the live site?

**Comment by holliscooper-cgu** [comment]
We do want Usabilla on the live site, but we may want to set up a new feedback campaign. I'll check with Andrea and get back to you ASAP.
