### ISSUE TITLE
School Sub nav

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/cgu#37]
hey @davekellam can you take a look at http://cgu.wpengine.com/academics/program/positive-health-psychology/ ?

the header is spitting out a ton of different links when it should just be showing the children of the current school. Works fine on my local install (attached). Not sure what's up. thanks. 

[cgu_db_20160609.sql.zip](https://github.com/ObjectiveSubject/cgu/files/307128/cgu_db_20160609.sql.zip)

**Comment by davekellam** [comment]
Was a school slug/taxo slug mismatch. Fixed.

There might be a way to error trap it, like checking to make sure the term existed or something before performing the query. Or trying to figure out a way get the cpt/taxo slug rename to match up. But it might not be worth the time sorting it out when there are really only 5 schools that likely won't change much.
