### ISSUE TITLE
Search: Academic result refinement issue

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#370]
This might be a result of #362 - but when a program is tagged as 2 things, both ALWAYS show up in the results, regardless of search filter. 

ex. we have a bunch of programs tagged joint and doctoral, or joint and dual degree. if you search for **just** "Joint" - you get search results like these. Basically, the heading of "Dual Degree" shouldn't also show up.
http://cgu.wpengine.com/academics/?degree_types=joint-degree
![image](https://cloud.githubusercontent.com/assets/18012084/22527958/061c7912-e886-11e6-8c8f-92acbc348f88.png)

If there's a way to fix this without breaking the fix in issue 362, that would be ideal.

**Comment by davekellam** [comment]
It's not a result of #362, but might be related. It's a result of original decisions to break everything apart by degrees, rather than eventual endpoints.

**Comment by holliscooper-cgu** [comment]
It's fine with us if that duplication occurs before any filters are selected, but once you select a degree filter, it's confusing if other degree categories show up.

**Comment by davekellam** [comment]
Sorry, might be wrong... I don't entirely know what's going on with the search templates at the moment. I probably need a deeper dive into the functionality.

**Comment by holliscooper-cgu** [comment]
That's fine - this is important, but not a show-stopper.

**Comment by davekellam** [comment]
Oh, I totally misinterpreted this... I thought it was search results, didn't realize it was the academics vertical/tool. Explains why I was having trouble figuring out what was going on. I imagine one of the sets can be hidden when joint degrees is selected. It's a bit of edge case.

**Comment by davekellam** [comment]
Think I've sorted out a fix here to avoid the duplication.

**Comment by holliscooper-cgu** [comment]
@davekellam  I'm still seeing the duplication (I cleared my cache):

![image](https://cloud.githubusercontent.com/assets/18012084/22572582/99ffd0b0-e959-11e6-9728-ac4cf1c1dd38.png)

**Comment by davekellam** [comment]
Ok. I only dealt with the case where if "Joint Degrees" was selected (try the link you posted above). You also want this to happen when "Dual Degrees" is selected? I should be able to deal with that case as well. 

That duplication is always going to be there on the page, it's necessary to achieve the layout already separated by degrees. I imagine filtering by Dual Degree and Joint Degree are the two main cases where that becomes noticeable.

**Comment by holliscooper-cgu** [comment]
Definitely Joint and Dual.

**Comment by davekellam** [comment]
Hmm, this is starting to get a bit dicey. I don't think my solution to exclude joint degrees works for dual. All of the joint degrees had a double, so it was easy to exclude. The dual's don't necessarily have a double, so the exclusion was affecting single entries too.

Back to the drawing board.

**Comment by kpettinga** [comment]
@holliscooper-cgu this should be all set. We implemented a check that will guard against duplicates of other degree types from showing up.
