### ISSUE TITLE
Event pages: Google map not working

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#372]
I'm seeing 2 issues now that the site is live:
- the Google map no longer works - is this an issue because we're now forcing SSL?
- If I try and remove the Google map by unchecking the box on the backend, the map still appears on the event page. Is this hard-coded into the template?

Ideally, we'd like the map there, but if it won't work, we need the ability to pull it.

**Comment by davekellam** [comment]
I don't think it's an SSL issue. It appears to be wanting at API key now, maybe there was blanket coverage on the wpengine subdomain. If you goto Events > Settings > API tab, a key can be added there. There's a link there that shows you where to get a key.

There's logic in the code that should've prevented the map from appearing, but it doesn't seem to be working properly at the moment.

**Comment by holliscooper-cgu** [comment]
Thanks! That worked. 

I'm leaving this open because of the other issue, but dropping the priority to low.
