### ISSUE TITLE
Search: Overall search refinements

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#373]
We can already foresee that we'd like to make some refinements to the WP search - such as being able to suppress certain custom post-types, or being able to give weight to certain types of content (in terms of relevance, etc.).

This is a plugin that we're looking at: https://searchwp.com/features/

Any thoughts you have on how this might affect the stylesheets and whatever else is in the backend would be great.

**Comment by davekellam** [comment]
Yeah, the built-in WordPress search is a notorious shortcoming. I hadn't heard of that plugin before, but it looks interesting. We can setup a staging site on WP Engine that mirrors the live site, and test out things like this without impacting the production site.

**Comment by holliscooper-cgu** [comment]
Sounds good to us.

**Comment by holliscooper-cgu** [comment]
We've been testing this plugin on a clone of the current site, and it seems to be doing a decent job of doing what we need it to do. We were planning on adding it over the weekend, but Lorraine had to make some tweaks to the wp-config.php and functions.php files to make it work better. Can you guys add this to the code whenever you do your next push to productions? Also, let us know if you think any of these edits will impact the site negatively in other ways.

**Add to wp-config.php:**

define( 'WPE_GOVERNOR', false );


**Add to functions.php:**

// pause the indexer for 1s in between passes
function my_searchwp_indexer_throttle() {
                return 1;
}

add_filter( 'searchwp_indexer_throttle', 'my_searchwp_indexer_throttle' );

 
// only process 3 posts per indexer pass (instead of the default of 10)
function my_searchwp_index_chunk_size() {
                return 3;
}

add_filter( 'searchwp_index_chunk_size', 'my_searchwp_index_chunk_size' );


// only process 200 terms at a time
function my_searchwp_process_term_limit() {
                return 200;
}
add_filter( 'searchwp_process_term_limit', 'my_searchwp_process_term_limit' );

**Comment by davekellam** [comment]
I don't see a problem with any of the functions, they're just adjusting internal settings in the plugin. 

It's possible that WP Engine could have a problem with disabling the governor. You could notify them in advance or wait and see if they have any issues. We usually try to optimize queries and/or store expensive ones in transients, don't think we've bumped up against killed/long queries so far.

**Comment by davekellam** [comment]
Yeah, I came across that article. It was the note at the end that mentions potentially reaching out to WP Engine.

I've added the search filters in, and added the governor code to `wp-config.php`.

**Comment by holliscooper-cgu** [comment]
Did you update the functions.php file yet? We see the wp-config.php changes.

**Comment by davekellam** [comment]
Yeah, that's what I meant by "added the filters". If you were looking for it in `functions.php`, I added a [search include](https://github.com/ObjectiveSubject/cgu/blob/master/includes/search.php) with the filters. We try to keep the main functions file pretty clean and separate out concerns into different files.

**Comment by holliscooper-cgu** [comment]
We see it now - thanks!
