### ISSUE TITLE
Pages: Navigation display issue

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#375]
On the admin interface, there's an option to uncheck a box for Visibility. We've created a page that we don't want to display in the sidebar nav. However, checking/unchecking that box doesn't seem to make a difference.

See:
https://www.cgu.edu/student-life/diversity/diversity-graphics-text/

Admin side:
![image](https://cloud.githubusercontent.com/assets/18012084/22703621/ad11eabc-ed19-11e6-8d1a-94bf532ede7d.png)

**Comment by kpettinga** [comment]
@holliscooper-cgu, that option was never meant to integrate with the sidebar nav. It's a new field that's used by the BU Sections plugin. We'll have to see about how we might take advantage of it to show/hide pages in the sidebar. 

@davekellam, can we implement a Walker class on the `wp_list_pages` function in partials/nav-sidebar.php which will check to see if this BU field (`_bu_cms_navigation_exclude `) is checked and display it in the sidebar nav accordingly?

**Comment by davekellam** [comment]
Sorry, missed the follow-up here. We could implement a walker class, but I tend to try and avoid them if it all possible. I wonder if there's another approach. I can look into it (will also poke around the plugin to see how they make it work).

@holliscooper-cgu @kpettinga One aside here... it looks from that page like you're trying to provide an accessible version of the diversity charts. Is there a better way to do this inline? Like use actual text and create the graphs using svg, or something? Or is that too complicated?

**Comment by holliscooper-cgu** [comment]
@davekellam We are going to create it another (better) way - this was a quick fix for launch.

**Comment by davekellam** [comment]
I figured out a way to do this without a walker class, `wp_list_pages` has an exclude parameter. So, I run a query to grab all excluded posts, and feed the ids into the exclude. The data is stored in a transient, and should update every five minutes or so.

@holliscooper-cgu I've gone ahead and published that page you mentioned above. It no longer appears in the sidebar nav.
