### ISSUE TITLE
Events calendar: Community plugin not working correctly

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#376]
We want to allow anonymous users to submit events to the calendar. However, the site tries to force them to log in, regardless of whether the "allow anonymous submissions" box is checked. This was working correctly at some point in the past (we tested it).

**Comment by kpettinga** [comment]
@davekellam can you look into this? I didn't get a prompt to login like Hollis said but when i try to submit the event, it doesnt go through and the following text is displayed above the form:

```
Event Start Time is required
Event End Time is required
```

**Comment by kpettinga** [comment]
@holliscooper-cgu this should be working now
