### ISSUE TITLE
Why CGU: At a Glance animation not appearing

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#377]
The third animation on this page isn't showing up:
https://www.cgu.edu/why-cgu/at-a-glance/

For these stats:
GRADUATE STUDENTS
2,136
FULL TIME
67%
STUDENT TO FACULTY RATIO
16:1

There should be an animation with graduation caps.

Also, I know we killed the clock hand animation, but the location animation (the first graphic) isn't working either - Claremont is supposed to appear on the map, along with Los Angeles. The university mace also used to have a bounce effect, and that isn't working.

**Comment by davekellam** [comment]
Hmm, yeah... I think it's the same issue affecting everything here. I've traced it back to commit d5329a343b410af9985c5c41a98b47fe552cc585 on Jan 16, when there was a bunch of separation for `cgu-core`. There are a lot of changes there, but we should be able to track down what broke it. Yea version control!

**Comment by kpettinga** [comment]
@holliscooper-cgu all set here!
