### ISSUE TITLE
Usabilla Feeback: button 

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#379]
@davekellam the client would like to adjust the placement of the Feedback button on the site and has sent the attached Combi-code javascript snippet for the new Feedback buttons from Usabilla. Can you update? 

[CGUCombi-code-DesktopVsMobile.txt](https://github.com/ObjectiveSubject/cgu/files/764822/CGUCombi-code-DesktopVsMobile.txt)

**Comment by davekellam** [comment]
The Usabilla code in the footer has been updated.
