### ISSUE TITLE
All Browsers: View calendar button missing

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#381]
From Andrea:  In Firefox, Chrome and Safari in any size screen, the View Calendar button is missing the bottom line but in hover state, it completes the box. 

![screen shot 2017-02-09 at 3 46 03 pm](https://cloud.githubusercontent.com/assets/1680051/22808477/1a4cce80-eefa-11e6-9bd7-5b09cdfc2c43.png)

**Comment by kpettinga** [comment]
@Jessdwilson this should be fixed. can you confirm?

**Comment by Jessdwilson** [comment]
@kpettinga it's displaying correctly for across Safari, Firefox and Chrome. Thanks!
