### ISSUE TITLE
Footer: hover state

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#382]
From Andrea: the hover state in the school footer is red on black and becomes illegible. I was watching a colleague click on a link and I could see she got a little confused by the experience. Maybe this needs to not be black anymore? What if it was the same gray as the CGU footer but with the lightest diagonal line? Or something like that? 

![screen shot 2017-02-09 at 3 48 09 pm](https://cloud.githubusercontent.com/assets/1680051/22808520/58a0e1a8-eefa-11e6-83c6-200e16598542.png)

**Comment by kpettinga** [comment]
Using a pattern as the background could further compromise accessibility because of the small text links. My suggestion would be to make it a slightly darker shade of the CGU footer.

![image](https://cloud.githubusercontent.com/assets/1746410/22816639/c60d9a38-ef95-11e6-9ebc-acefe619ecf1.png)

**Comment by Jessdwilson** [comment]
@kpettinga the client agrees this is a good solution, thanks!

**Comment by davekellam** [comment]
Believe this was pushed live. Going to close it out.
