### ISSUE TITLE
Request Info form: start term added

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#384]
Could we add Anticipated Start Term (drop down options: Summer 2017, Fall 2017, and Spring 2018) to the per program request info form? This could go under the Country with the submit button moving to the right. 

For instance, the one on the bottom of this page: https://www.cgu.edu/academics/program/islamic-studies/

**Comment by davekellam** [comment]
Added in now

**Comment by holliscooper-cgu** [comment]
@Jessdwilson What's the first choice, second choice, third choice dropdown? Is that something we requested? If so, it probably needs a header above it to label it.

**Comment by davekellam** [comment]
@holliscooper-cgu Sorry about that, seemed to have slipped in when I added the anticipated start date field.

**Comment by holliscooper-cgu** [comment]
@davekellam - Can you change Winter 2018 to Spring 2018? So the choices should be: Summer 2017, Fall 2017, Spring 2018 (we don't have a winter session)

**Comment by davekellam** [comment]
Done. Muscle memory... summer > fall > winter. I live in Canada 😄
