### ISSUE TITLE
Events calendar - limit on number of events shown per day

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#385]
It looks like there's a 3-event per-day limit on the display on this page (month view):
https://www.cgu.edu/events/

For example, Feb 16 has 4 events, but only 3 show. By clicking the "make event sticky" button, I can control which 3 of those 4 events show, but there shouldn't be a limit on the number of events anyway.

Also, the sticky button doesn't seem to be working quite correctly. I made the Laurel Thatcher event sticky on the 16th (since it was the 4th event getting dropped off), but it looks like it just put the times out of order - it's not first, but now it's not last, either.

**Comment by davekellam** [comment]
Think I've sorted out the issue with only 3 events showing up per day. 

You mentioned the sticky issue in #359. We didn't take any sticky behavour into account. Assuming the plugin is using the builtin WordPress sticky feature, we can probably make it work. Sticky posts are a bit notorious in the WP community, as they can often have a knock-on effect, causing them to appear in unintended places.
