### ISSUE TITLE
Events calendar main page: default to week view

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#389]
Can the main events page default to the week instead of the month view?
https://www.cgu.edu/events/

**Comment by davekellam** [comment]
Pretty sure it's doable, will probably take some reworking of the templates.

This can be incorporated in with the design changes in #364

**Comment by davekellam** [comment]
This was more straight-forward than I expected. There's a setting under Events > Settings > Display which allows you to set the default view, I swapped that from month to week, no mucking about in the templates necessary.
