### ISSUE TITLE
Academics page navigation

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#39]
@kpettinga On the Academics page, Schools is missing from the navigation, see attached screenshot of our mockup 

![screen shot 2016-06-10 at 10 50 33 am](https://cloud.githubusercontent.com/assets/1680051/15968375/ab0ad35c-2ef9-11e6-84cf-2bfc9e434279.png)

**Comment by davekellam** [comment]
The menu is dynamically populated from child pages. If there's no schools page, it means there isn't a schools child page beneath programs.

**Comment by kpettinga** [comment]
@Jessdwilson

This is just a content entry issue. A schools page needs to be created and set as a child of Academics.

**Comment by Jessdwilson** [comment]
thanks @kpettinga looking at the Publishing Help for shortcodes it's not clear how to create a layout for the Schools page similar to our mockup. I tried creating two columns but it didn't look right, can you advise?

![academics schools](https://cloud.githubusercontent.com/assets/1680051/16015416/8a900aa4-3163-11e6-9e99-ef41a12ce406.png)
