### ISSUE TITLE
Roles: allow more granular access to schools taxonomy

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#392]
The events editor role needs to be able to tag events with a School (in addition to Event Type and Event Category) - right now, the school options are grayed out in the Quick Edit view, and missing entirely from the Edit view. 

I tried enabling the taxonomy permissions in the role editor, but that doesn't seem to make a difference. Any ideas on how to get this to work?

**Comment by davekellam** [comment]
I probably have to make a few tweaks to the code to provide more granular access control for the taxonomy.

**Comment by davekellam** [comment]
I've added in some access capabilities.

@holliscooper-cgu in the roles editor, under Taxonomies, you should now see two options for `publish_schools` and `edit_schools`. If you check those, that role should now have access to the schools taxonomy.
