### ISSUE TITLE
Financial Calculator: update with new tuition rate ASAP

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#395]
We are announcing next year's tuition rates to students today, and need to update the website accordingly. Currently, the tuition calculator uses a unit price of $1847. **This needs to be changed to $1902.**

https://www.cgu.edu/admissions/cost-aid/financial-calculator/

**Comment by Jessdwilson** [comment]
Hi @holliscooper-cgu we have updated the script and it should be deploying now, I see that the $1,847 is included in text on the page, let us know if you would like us to edit the text as well

**Comment by holliscooper-cgu** [comment]
Thanks! I updated the text.
