### ISSUE TITLE
Shortcode request: Stats formatting

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#396]
We need to use the formatting for the stats modules in places where we can't actually include a module (ex. the admissions post type).

I can fake the layout of the stats module using existing column shortcode and the h5 tag for the heading. What we don't have is a quick way of formatting the red, large text.

![image](https://cloud.githubusercontent.com/assets/18012084/23274293/106a244a-f9b7-11e6-8b2d-6d9ed335e0ef.png)

**Comment by davekellam** [comment]
There was already a statistics shortcode. I've added a color parameter to that.

`[statistic label="Amount Awarded" figure="$11.3 Million" color="red"]`

**Comment by holliscooper-cgu** [comment]
Thanks, Dave. When I use that shortcode, it doesn't match the formatting of the current stats module (it may be that the stats module design was tweaked after the shortcode was created).

Here's the spacing/size of something in a stats module:
![image](https://cloud.githubusercontent.com/assets/18012084/23281106/c5caf88c-f9d0-11e6-91a0-869bc4be1d46.png)

Here's the spacing/size of something using that shortcode:
![image](https://cloud.githubusercontent.com/assets/18012084/23281142/f5995d88-f9d0-11e6-8f02-8ac1261005c9.png)

I was able to mimic the current stats display by using the following classes: 
class="u-font-size-xl u-font-mercury u-nudge u-color-red"

**Comment by davekellam** [comment]
Given that the shortcode previously existed, I'm assuming that it's being used elsewhere on the site.  

The classes currently generated by the current shortcode are `h1 u-hug u-font-mercury u-color-XX`. I'm worried about having knock-on effects elsewhere. The `u-hug` vs `u-nudge` is the spacing. For fonts there are `h1` to `h6` and then `sm`, `lg` (normal), and `xl`.

Do you know if that shortcode is still being used on the site, and if so, where an example might be? If it is, we'll need to mash the formats together in some sort of system. If not, I can replace the existing classes.

**Comment by holliscooper-cgu** [comment]
The example in the publishing help shows the homepage messaging image under events:

![image](https://cloud.githubusercontent.com/assets/18012084/23281740/6928af40-f9d3-11e6-885c-776992ed325b.png)

I don't think we're using it on the front-end anywhere, so maybe it's being used on your end. Would it be easier to create a new shortcode with the correct classes attached, rather than tweak anything existing?

**Comment by davekellam** [comment]
Ahh, those modules are making use of the shortcode. We generally like to stick to DRY principles and avoid unnecessary duplication. So, I've added a size parameter to the shortcode. Adding `size="large"` should produce the larger output you've requested, otherwise it'll fall back to the smaller version.

**Comment by holliscooper-cgu** [comment]
It works great - thanks!
