### ISSUE TITLE
Events: Organizer display

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#397]
2 issues:

- If no phone is listed for the organizer, can the placeholder space for it not appear?
- If an event has more than one organizer, only the first listed organizer is appearing.

Ex.
![image](https://cloud.githubusercontent.com/assets/18012084/23324029/565574de-faa0-11e6-9f7f-fd809fd49d8b.png)

https://www.cgu.edu/event/salary-negotiations-advice-human-resource-professionals/
(this event has 2 organizers)

**Comment by davekellam** [comment]
Multiple organizers should be appearing now, and there's a check to see if the phone number field has been populated.
