### ISSUE TITLE
Event calendar: Event type display bugs

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#398]
- On the event archive page, all events display as "Exhibitions and Performances" even if they are tagged differently. The individual event pages show the correct event type.

![image](https://cloud.githubusercontent.com/assets/18012084/23325039/f15efb7a-faa6-11e6-88b6-b6fcb7389f60.png)

If you filter by event category, the correct event type displays.
![image](https://cloud.githubusercontent.com/assets/18012084/23325105/8853cca4-faa7-11e6-9377-c7c2965baba2.png)

- When you click the previous or next week buttons, the event type doesn't appear at all.

![image](https://cloud.githubusercontent.com/assets/18012084/23325056/15200b58-faa7-11e6-8007-aae2da98cc8b.png)

If you refresh the page, the event type appears, but only as "Exhibitions & Performances"
![image](https://cloud.githubusercontent.com/assets/18012084/23325121/b5c6ee28-faa7-11e6-9ec1-9ecabfa88c8f.png)

**Comment by davekellam** [comment]
Think this is fixed up now. The event cards were trying to grab the types using the ID of the page they were on, rather than the event.
