### ISSUE TITLE
Timeline module problems

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#400]
We're still having some funky issues with the history timelines (currently, they only exist in 2 locations):

**https://www.cgu.edu/**
- On my computer (PC), the timeline plays through correctly, but when it gets to the "More" tab, that tab stays highlighted for 2 rotations (the images for 1925 and 1929), and then it jumps to the 3rd timeline item (1951) and plays forward. On someone else's computer (Mac), it is still running forward, and then going in reverse. We are both viewing it in Chrome.

For me, on a PC, using Firefox, it runs forward correctly, shows the image for 1925 when it hits the "More" tab, and then jumps to 1929, goes back to 1925, and then plays all the way forward again.

Ideally, the rotation would skip the More tab altogether (if this means not having that downward arrow on "more" when it's highlighted, that's fine).

**https://www.cgu.edu/departments/art/**
- The art department timeline currently does not have the more tab, but it's still having issues. 
- After it goes through once, it jumps back one year (1996), then jumps to the 2nd item (1960), then goes back to 1929, then starts playing forwards again.

**Comment by davekellam** [comment]
Hmm, hadn't realized that the timeline carousel was actually two different sliders, one for the dates, one for the images. So, I hadn't turned on looping for the dates. That fixed the disconnect, but I created a new issue...

I didn't have the more link enabled on my local copy, so everything seemed fine. With the more link enabled, it seems to create a date loop at the top. Although, the art department is also looping on the live copy without the more link (my local isn't), it's weird. I'll figure it out.

**Comment by davekellam** [comment]
It seems to have the wrap around issues when there are more than 8 items (including the more link) in the carousel. Now working on how to fix.

**Comment by davekellam** [comment]
I've added in a couple more breakpoints, which should bump the slide + more limit up to 12, before it starts doing that weird looping around thing on desktop.

Seems like things are working properly for me now in Chrome/Safari on mac. Going to close it out, but feel free to reopen if it's still having issues that I'm missing.
