### ISSUE TITLE
Art department: Gallery carousel auto-scrolling

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#401]
The gallery carousels on the art department pages should **not** autoscroll.

https://www.cgu.edu/departments/art/
(See "Art Galleries" just above the Visiting Artist Lecture Series)

https://www.cgu.edu/students/diana-campuzano/ (student example)
https://www.cgu.edu/people/david-amico/ (faculty example)
(see the Galleries under the artwork images)

**Comment by davekellam** [comment]
The art gallery carousels should no longer autoplay.
