### ISSUE TITLE
Events: Organizer display

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#403]
One of the fields available for an organizer is "website" - can we add this to the display?

Ex.
On this event:
https://www.cgu.edu/event/pedagogy-technology-integration-free-preparing-future-faculty-workshop/

![image](https://cloud.githubusercontent.com/assets/18012084/23682408/8540c090-0348-11e7-86d7-3b3357d20b5f.png)
Since there's an associated website with this organizer, it should read:
Preparing Future Faculty
909-607-6225
pff@cgu.edu
http://www.cgu.edu/pff

(The website URL should open in a new window.)

**Comment by davekellam** [comment]
I've added the organizer url if available.
