### ISSUE TITLE
Profile template: Add second phone field

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#407]
We need to add a second phone field to the profile template.

In terms of the front-end display, (if one exists) it can appear directly under the current phone, without a separate header: 
![image](https://cloud.githubusercontent.com/assets/18012084/23961202/6bc9df96-0967-11e7-87e4-edce5afc8b53.png)

**Comment by holliscooper-cgu** [comment]
Sorry for my quick mockup - the text formatting should obviously be identical for the two numbers.

**Comment by davekellam** [comment]
I updated this the other day, and converted the text field to a multiline textarea, which should be backwards compatible and now allows you to add multiple lines with phone numbers and descriptions. Could've sworn I updated and closed the issue, but it must not have gone through before I left the coffeshop.

**Comment by holliscooper-cgu** [comment]
We need a line break inserted on the program/school page displays (the two lines look fine on the profile display)

How it renders now:
![image](https://cloud.githubusercontent.com/assets/18012084/24053903/ae76a5fe-0af7-11e7-9824-479bde1d361a.png)

**Comment by davekellam** [comment]
Ahh, forgot where else the people bubbled up. I've added in the code to deal with the linebreak. The only issue here, is that the `T: ` is hardcoded in, under the original assumption that there was only one phone number, so it doesn't appear in front of the second number. There might be a way to add that in programatically, but I'll have to think on it. The other option is to remove the T and E, but the information hierarchy becomes a little less apparent.

**Comment by holliscooper-cgu** [comment]
Is there a way to indent the second line so the number lines up with the first?

**Comment by holliscooper-cgu** [comment]
Not ideal, but it's possible to fudge it by adding in 4 spaces before the second number:
![image](https://cloud.githubusercontent.com/assets/18012084/24056490/299d0422-0b01-11e7-8eb6-ff8949656cd0.png)

**Comment by davekellam** [comment]
I've sorted out how to add a `T: ` in front of each number. 

Adding spaces would likely have a knock-on effect on the individual profile page. There isn't really a way to align it like that without rearchitecting how those areas work.

**Comment by holliscooper-cgu** [comment]
2 Ts are fine.
