### ISSUE TITLE
Gravity Forms license expiration

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#408]
We're getting a notice that the gravity forms license key has expired. It looks like your team used a developer license, and we would be purchasing the business license. Before we do so, I wanted to check and make sure that by stepping down a license level, we won't be breaking any functionality on the site.

http://www.gravityforms.com/add-ons/

**Comment by davekellam** [comment]
I'm don't think we used any Gravity Forms add-ons, you should be fine stepping down a license. It was the events calendar plugin where we're using a number of add-on features.

**Comment by kpettinga** [comment]
@holliscooper-cgu we're not using any gravity forms add-ons or special functionality within the theme. You should be fine to register with your own license and update as needed.

Will leave to you to close this one out when you're ready.
