### ISSUE TITLE
Areas of Study - Show/Hide issues

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#409]
We have an issue where we have an area of study (Humanities) that needs Faculty Experts assigned to it, but should NOT show up under Academics.

On the faculty experts page, it makes sense that all the humanities people are grouped together.
https://www.cgu.edu/news/faculty-experts-guide/

However, we do not want Humanities to appear as an area of study on the Academics page.
https://www.cgu.edu/academics/?areas_of_study=humanities

Is there any way to keep an area of study from showing up as long as no **programs** are assigned to it?

**Comment by davekellam** [comment]
There isn't a way for a taxonomy to tell if it's empty for a specific post type, however it is possible to exclude specific term IDs. So, I've gone ahead and excluded the humanities term ID from that list.

**Comment by holliscooper-cgu** [comment]
That'll do for now. Thanks!
