### ISSUE TITLE
News search

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#410]
The search box on the news page used to search only news items. Since we've implemented the SearchWP plugin, though (which has made our search results across the site much better), the news search now searches the whole site as well. 

SearchWP has instructions for setting up a supplemental search:
https://searchwp.com/docs/kb/supplemental-search-step-by-step/

Lorraine set up a news supplemental search already (under Settings>Search WP), but it needs to be incorporated into the template. Can you  guys take a look?

**Comment by davekellam** [comment]
I've implemented the supplemental search. Took me a bit longer than expected, was bumping into some issues where things weren't behaving as I expected.
