### ISSUE TITLE
News: Suppress items on homepage

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#411]
We need a way to be able to suppress news items from displaying on the main CGU homepage (like a checkbox on the admin side that will let us hide the news item). There are some news items that should only really appear on school pages (or elsewhere on the site). This only applies to the 4 news items that show up on CGU.edu - we don't need to suppress from anywhere else.

**Comment by davekellam** [comment]
I've added a checkbox to the backend that will allow you to feature news posts on the homepage. You'll need to go in and check off the box for the first four that you want to appear there.

Right now, I've set the default to unchecked, but can invert that if you'd prefer to generally have them appear on the homepage and uncheck when necessary.

**Comment by holliscooper-cgu** [comment]
Thanks, Dave. I think doing the inverse is better - we will more often want things on the homepage than not.

**Comment by davekellam** [comment]
Should be set to checked by default now for new posts.

**Comment by holliscooper-cgu** [comment]
We've noticed a bug - when you suppress an item from the homepage and save it, it all works. However, if you go in to re-edit that same item, the "Featured on homepage" box is re-checked, so if you don't notice it and re-save, the item appears again on the homepage. Is there any way to make the checkbox remember if it's checked or not?

**Comment by davekellam** [comment]
Hrrm, I guess this a side-effect of the default setting. I can put it back to unchecked by default (this situation might be why it was a hidden option). 

There's no real way to preserve previous state with a checkbox. It's an issue with how the checkbox field is stored, it's `checked` or null (the field is blank). It could be changed to a dropdown that has two-specific options, like yes and no. I think that would prevent this sort of editing error, so it becomes something like `yes` & `no`, with no null state.

**Comment by holliscooper-cgu** [comment]
Ah, I see what you're saying. Maybe instead of dropdown, there could be a radio button toggle?

ex. Show news item on homepage? [ ] Yes  [ ] No

With the default set to "Yes."

**Comment by davekellam** [comment]
I've changed this over to radio buttons. It will default to `yes` and now has a `no` state, so it shouldn't reset that to `yes` on post edit. Posts that had been checked will still appear on the homepage, you shouldn't have to edit/update anything.
