### ISSUE TITLE
Search results: utility nav placement incorrect

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#412]
On search results pages, the utility nav is getting smashed against/behind the Request Info button:

![image](https://cloud.githubusercontent.com/assets/18012084/24973991/a6b9adc4-1f75-11e7-8952-ba5b98b9840d.png)

(That nav item actually says "info for") It should look like this:

![image](https://cloud.githubusercontent.com/assets/18012084/24974039/d043ac58-1f75-11e7-8a29-ea432bdf9776.png)

**Comment by davekellam** [comment]
This was trickier than I expected, it was only happening on certain queries. It came down to certain queries somehow identifying themselves as "schools", which would add the bars/global menu to the header and a school footer. I've added in a check to prevent that from happening. Should be fixed now.
