### ISSUE TITLE
Program Request Info form: collect degree name

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#413]
We are running across an issue where for some programs, we can't tell if someone is interested in the MA or PhD, because both programs have the same overall name (ex. English). Is there a way we can also collect the degree name (as a hidden field) when someone submits the form?

**Comment by davekellam** [comment]
The hidden fields are somewhat limited by default. I've added in hidden field `degree` that captures the URL (which typically includes the degree name, like `/php-english/`). I'm looking into the ability to hook into the form to modify hidden fields, but no luck yet.

**Comment by davekellam** [comment]
As per usual, I figure things out after mentioning that I'm having trouble figuring it out. There should now be a hidden degree field that adds a comma separated string listing the `degree_type`s.
