### ISSUE TITLE
Homepage events module updates

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#415]
![events2](https://cloud.githubusercontent.com/assets/18012084/26123206/f3a90cdc-3a2e-11e7-9a55-e4ec7585fbad.jpg)

Here's the mockup for Events revisions:

- [x] View calendar should be moved under the Events listing, and formatted to match "Read more news"
- [x] Remove the RSVP button from the cards entirely - it's extremely unlikely someone would RSVP without reading more about the event first.
- [x] Change "Upcoming Events" to "All"
- [x] Reduce the space between the word and the underline. This can be a global change, since I know it's used elsewhere.
- [x] Add a little more space between the date and "Featured Event" on the card front.

**The page for the "Admissions Events Calendar" link doesn't exist yet, so you can hold on that change for the moment.

**Comment by kpettinga** [comment]
all set @holliscooper-cgu

**Comment by holliscooper-cgu** [comment]
Ok, final change is ready to go -

- Add link to "View Admissions Events Calendar" (ref mockup above for look/placement)
it should point to this page:
https://www.cgu.edu/admissions/admissions-events-calendar/

**Comment by kpettinga** [comment]
all set @holliscooper-cgu
