### ISSUE TITLE
Lines disappearing from program listings and dropdowns in large view

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#417]
I've noticed that the lines above the program listings and dropdowns disappear periodically in the large view. With the dropdowns, this seems to happen when there are 2 columns of dropdown side-by-side

https://www.cgu.edu/school/ssspe/division-of-politics-economics/
![image](https://user-images.githubusercontent.com/18012084/26985182-42bfed60-4cf7-11e7-801c-737a16cccd38.png)

https://www.cgu.edu/student-life/resources-support/
![image](https://user-images.githubusercontent.com/18012084/26985208-6121742c-4cf7-11e7-9395-6e2b0d8e4b15.png)

**Comment by kpettinga** [comment]
@holliscooper-cgu I believe this is an effect caused by the zoom level of your browser window. Can you make sure your browser window is not zoomed out? If you're using chrome or safari on a Mac, you can press **command + 0** to reset the window to the normal zoom.

**Comment by holliscooper-cgu** [comment]
Sorry, I didn't update this issue - that fixed it, Kirk.
