### ISSUE TITLE
Schools: multiple recruiters on pages

### ISSUE THREAD

**Issue by davekellam** [ObjectiveSubject/cgu#47]
Mockup for Arts & Humanities landing:

![pasted_image_at_2016_06_28_01_22_pm_720](https://cloud.githubusercontent.com/assets/60804/16435764/4c85e3d2-3d66-11e6-8d77-202da3669d7c.png)

This might actually be part of modules (#44).

**Comment by Jessdwilson** [comment]
@davekellam @kpettinga for the School of Arts and Humanities Hollis does not want to include photos of the recruiters on the school landing page as it feels too crowded, see attached screenshot of revision. We've added the program info that each recruiter is associated with. 
![sah homepage admission specialists](https://cloud.githubusercontent.com/assets/1680051/16692035/299cf1e6-44fd-11e6-868b-768cacbdf84c.png)

We will only include the recruiter photos on the program page modules. 
![sah program page admission specialist](https://cloud.githubusercontent.com/assets/1680051/16692061/3e7b5634-44fd-11e6-801f-2505b5807dcf.png)

**Comment by Jessdwilson** [comment]
@kpettinga as you will see on the SAH mockups and the message in Basecamp, the request info module for all School landing pages should not have the text fields and should appear like the attached. 
![screen shot 2016-07-27 at 2 48 31 pm](https://cloud.githubusercontent.com/assets/1680051/17187950/39475008-5409-11e6-9fe7-d571dae2f0a8.png)
