### ISSUE TITLE
Program with multiple degrees 

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#50]
When tagging a program with multiple degree types (ex. Masters and Doctoral), it only displays in one category on the Programs page, instead of both. See Early Modern Studies as an example. This was working correctly in the past.

![screen shot 2016-07-15 at 5 17 43 pm](https://cloud.githubusercontent.com/assets/1680051/16888756/10c132a0-4ab0-11e6-9e27-5e47d474740f.png)

**Comment by davekellam** [comment]
I believe there are separate programs for MA and doctoral. For example Early Modern Studies has both an MA (http://cgu.wpengine.com/academics/program/early-modern-studies-ma/) and a PhD program (http://cgu.wpengine.com/academics/program/early-modern-studies-phd/). The field below the title is purely descriptive, for advertising the different degrees available at that level, not used in sorting.
