### ISSUE TITLE
custom sub-header display

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#51]
Would it be possible to turn on the custom sub-header display on the Programs page template? Right now there's a field for it in the admin view, but if you type anything in there, it doesn't appear on the page. The custom header works, though.

**Comment by davekellam** [comment]
Here's an example: http://cgu.wpengine.com/academics/program/phd-media-studies/

Seems like the width percentages are just a little bit off. SASS seems to generate a width of 31.76% for the blocks, which is fine for Chrome, but seems to need 31.73% or less for Safari. Going to throw this back to Kirk, as it's more of a front-end thing that could affect the site's overall grid.

**Comment by davekellam** [comment]
I've added in subtitle support for programs pages, modelled after what appears on the front (home) page.
