### ISSUE TITLE
Faculty profile pages back button

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#53]
On the faculty profile pages, the back button in the browser stops working (I tried this in Safari and Chrome and had an issue).
 
Ex. http://cgu.wpengine.com/people/stewart-i-donaldson/#works (try navigating to this page first from somewhere else, then hit the back button and try to go back to the page you came from)

**Comment by davekellam** [comment]
Spent some time here this aft. The back button is getting hijacked by the Works/Classes view further down the page, which does a redirect of sorts on page load to select the works tab. So, you land on the page, it forwards to #works, you try to hit the back button, it goes back to the one without #works and then it gets forwarded again.

It has something to do with the view-manager.js script (around here https://github.com/ObjectiveSubject/cgu/blob/master/assets/js/src/view-manager.js#L37 or possible further down around lines 80-113). There's probably a way to prevent this behaviour. I'm going to toss it backover to him, as I'm not super-familiar with Velocity.js and don't want to create a problem that will have further knock-on effects.
