### ISSUE TITLE
New fields on Students

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/cgu#57]
@davekellam,

We need some fields for a carousel of artwork on students that are in art programs. These should probably go in a new metabox (e.g. "student artwork").

| Field Name | Type |
|---|---|
| Gallery | repeater |

| Gallery sub-field Name | Type |
|---|---|
| Image | file |
| Title | text |
| Description | text |

**Comment by davekellam** [comment]
Been thinking about this. We can implement this, but I think the implementation needs a bit more thought. Galleries could also be faculty, it's not just students. I don't think images play nicely in repeater fields, but think they are fine in group repeaters (https://github.com/WebDevStudios/CMB2/wiki/Field-Types).

One thing here is that WordPress media already have file/title/description, so we could just use the file_list field type to build out the gallery (sort of like the Carousel module).

**Comment by kpettinga** [comment]
@davekellam sounds good. we'll stick to using the default WP media fields.
