### ISSUE TITLE
Shortcode optimization

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/cgu#6]
**Custom Content Layouts**
- [x] Dropdowns and Dropdown groups
- [x] Columns
- [x] Section Headers
- [x] Video and Video group

**Comment by kpettinga** [comment]
@davekellam the `cgu_video_group` shortcode is rendering `<p>` tags after every line break despite `$content = str_replace( '\r\n', '', $content );` being called before the return. Could you help?

**Comment by davekellam** [comment]
I think it's probably something to do with trying to run `do_shortcode` within the declaration of the shortcode itself. I don't think this is the right way to do things. There are ways to turn off the shortcode auto-formatting that don't involve regex.

I also don't like the idea of running a query inside of a shortcode... there are probably safer ways to achieve what you're trying to do with the drop down... possibly with custom fields. I'm less familiar with the shortcodes you used on a drucker, but maybe a quick rundown somewhere would be useful? Perhaps in the data model i'm putting together.

**Comment by davekellam** [comment]
Ahh, missed the bit in slack that they were documented on the site now. I'll factor add that in. Still feeling like we need to rethink the approach to the dropdowns, really don't like including things like post_type in there.

**Comment by davekellam** [comment]
Think I'm wrong about using `do_shortcut` within a shortcode declaration, seems to be something I've done in the past, and something used in plugins.

**Comment by kpettinga** [comment]
Hey @davekellam, we can probably exclude the part in 'dropdown_group' that lets you query posts. I haven't actually seen where that would be necessary in the wireframes yet. It was just part of what I copied from Drucker

**Comment by davekellam** [comment]
It's alright, I added in a check against existing post types for now... makes it a bit better.

**Comment by davekellam** [comment]
I think we can do something like `return do_shortcode( shortcode_unautop( trim( $content ) ) );` but haven't had a chance to test it everywhere yet. Might depend a bit on the nested shortcodes (the parent one has to deal with the children (hence the do_shortcode there).

**Comment by davekellam** [comment]
Spent a bunch of time on this today... sort of have a fix, but there's probably a better way to implement. It works for now. There's a couple places where we're still getting paragraphs with non-breaking spaces, but is less of a problem than we were getting with various `<p>`s opening up here and there.

**Comment by kpettinga** [comment]
@davekellam we created nestable shortcodes on Worldstrides with the `timeline` and `timeline_node` shortcodes. I wonder why it's working differently. Did Wordpress change the way they output content?

**Comment by davekellam** [comment]
Yeah, I added some hackish code that I included on worldstrides (was in functions.php), which reprioritizes `wpautop` and `shortcode_unautop`. I'm going to put some more time into sorting it out, I should be able to get this stuff working without doing a blanket override, which could have knock-on effects to other shortcodes that get added.

**Comment by kpettinga** [comment]
hey @davekellam, I created a new `program_courses` shortcode but it seems to strip `<p>` tags from the rest of the content when I use it. Could you take a look?

**Comment by davekellam** [comment]
Yeah... wouldn't be surprised if it was a knock-on effect from the hackish approach to getting columns and whatnot to _not_ display padding. I'll try to get this sorted over the next couple days, before they really start entering content.

**Comment by davekellam** [comment]
Think I may have _finally_ sorted out a fix for the grouping shortcodes. I'll leave this open for the time being, to see if any other issues arrive.
