### ISSUE TITLE
photo centering on homepage

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#61]
photo centering on the homepage doesn't work well on wider screens (see attached). The changing dimensions/scaling as implemented makes it hard to correctly crop images, especially at larger screen sizes

![home-widescreen](https://cloud.githubusercontent.com/assets/1680051/17569389/f9ef7c2e-5f15-11e6-9f2c-b0e47431c1d5.jpg)

**Comment by kpettinga** [comment]
@Jessdwilson made some adjustments here. The height of the page header will scale with the width of the browser **up to** 700px, which is the maximum height of the hero image used. 

Can you see how the client likes it? Feel free to re-open if necessary.
