### ISSUE TITLE
Home: sidebar stretches

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#62]
the areas of study sidebar on the homepage stretches (see attached) 

![home-widescreen](https://cloud.githubusercontent.com/assets/1680051/17569624/1886b6b0-5f17-11e6-9abd-a7f4f6f3e374.jpg)

**Comment by kpettinga** [comment]
This is per our design spec, is it not? @Jessdwilson  @elliotarthur @jalbertgagnier?

**Comment by elliotarthur** [comment]
@kpettinga I wonder whether there's a breakpoint for the background. So at extreme circumstances such as this, we don't have a large amount of black on the page but just a couple of columns of background.

**Comment by davekellam** [comment]
Any updates here? @Jessdwilson @elliotarthur

**Comment by Jessdwilson** [comment]
@davekellam @kpettinga is it possible for the Areas of Study section to maintain a set width on larger screens so there isn't a large amount of empty space? 
![screen shot 2016-09-14 at 5 45 25 pm](https://cloud.githubusercontent.com/assets/1680051/18531212/1b77e0ae-7aa3-11e6-854f-cb54124e067f.png)
