### ISSUE TITLE
Why CGU 10 Reasons faculty page

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#65]
the Meet Our Faculty link should go to the Meet Our Faculty Page

##

JW added the Meet Our Faculty page which is a child page of Why CGU, this page will have a similar layout to Creative Paths Remarkable Careers

**Comment by kpettinga** [comment]
@Jessdwilson this link is editable in Wordpress. There are fields for each of the "reasons".
