### ISSUE TITLE
Buttons - Remove outlines

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/cgu#68]
I've noticed a few instances where the buttons have an outline on hover. Can we remove the outline.

![image](https://cloud.githubusercontent.com/assets/12611145/17571030/ac15d046-5f1c-11e6-9fdc-7927381dcb04.png)

**Comment by davekellam** [comment]
Going to close this out.

@elliotarthur in the future, can you add in specific urls where the issue is occurring (makes it easier to track down), makes for a clearer bug report.
