### ISSUE TITLE
Live content for featured programs on schools

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/cgu#7]

**Comment by kpettinga** [comment]
@davekellam need your help here. For some reason the featured programs field isn't returning a value for me.

**Comment by davekellam** [comment]
Combination of things... you had added in a `$prefix` to the field, but it didn't have one. Alternatively, we could prefix the custom field (but we'd want to do this before data gets added). There was also a typo later in the foreach part of the loop. I did a basic wiring up of the data too.
