### ISSUE TITLE
Home: rollover state on the Areas of study module

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/cgu#70]
Can the rollover state be red not grey here? Think that might cause 501 compliance issues. and will align with other text links too.

**Comment by davekellam** [comment]
@elliotarthur is this still an issue? I'm having trouble finding an example.

**Comment by davekellam** [comment]
@elliotarthur sorry, misread that it was specific to the homepage. Appears to be blue/teal now, is that alright?

**Comment by elliotarthur** [comment]
@davekellam @kpettinga Teal is good. Think this was changed a while ago from the dark grey we had. I'll Close
