### ISSUE TITLE
Footer: Stroke width on social icons

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/cgu#71]
Can we reduce from 2px to 1px stroke width on the social media icon boxes. Maybe to align with our button pattern, on rollover, it should be a color fill instead of outline color.

**Comment by davekellam** [comment]
@kpettinga is the border stroke weight here actually part of the font file? Also, should we be using an icon font here, rather than SVG (asking mostly for accessibility)?

**Comment by kpettinga** [comment]
Hey @davekellam, the stroke is indeed part of the font file. I can edit that and regenerate the icont font.

To my knowledge, we ARE using an icon font. I generated it using icomoon.io. Checkout out assets/fonts/cgu-ui.*
