### ISSUE TITLE
Schools: card styling issue

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#73]
@kpettinga I haven't changed anything in WordPress but I noticed that the cards on the Faculty and Research pages are truncated 

![screen shot 2016-08-11 at 3 58 33 pm](https://cloud.githubusercontent.com/assets/1680051/17602892/aa096d6a-5fdc-11e6-8195-177c4b9993d4.png)

**Comment by davekellam** [comment]
@kpettinga still seems to be an issue ([example](http://cgu.wpengine.com/school/school-of-arts-and-humanities/faculty-research/))
