### ISSUE TITLE
Program page footer with department 

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#74]
@kpettinga the client requested that there be a Department link displayed in the footer of program pages, right now the school footer will appear and there isn't an option on program pages to change the footer. I'm wondering if there may be an easier way to implement this other than creating a separate footer for each program with its respective department link

For example on this page: http://cgu.wpengine.com/academics/program/ma-english/

**Comment by kpettinga** [comment]
Hey @Jessdwilson, there's a field on programs to select departments. It's near the bottom. 
In the mockups for programs the department is a section near the bottom, just above the school footer.
When editing a department, you can specify a mailing address, contact info and a department head. All that info will show up on the program.
