### ISSUE TITLE
Programs: Adding modules

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#75]
@kpettinga Where would I go to edit the Study Abroad module on program pages? 

"Study Abroad" should change to "In the Field", we also should have the option to include a carousel like the attached mockup 
![in the field](https://cloud.githubusercontent.com/assets/1680051/17605906/b52f77e4-5fea-11e6-8f8d-2bdc1b8ae9c4.png)

**Comment by davekellam** [comment]
@Jessdwilson what program is this from specifically? You would like want to create a new module using the Carousel format, save it, and then add it in the modules section of the program.

**Comment by Jessdwilson** [comment]
@davekellam thanks, yeah I've figured out the carousel feature. And it looks like Study Abroad has been changed to In the Field as requested so we could probably close this out. Thanks!
