### ISSUE TITLE
on-page navigation style

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#76]
@kpettinga @elliotarthur on faculty landing pages we have an on-page navigation for Works and Classes with bullets, should the bullets be removed to reflect other on-page navigation styles as seen in our mockups? example here: http://cgu.wpengine.com/people/david-luis-brown/#classes

![site mockup nav](https://cloud.githubusercontent.com/assets/1680051/17628948/c5afffa8-6085-11e6-90a7-5e0b47f7a686.png)

**Comment by elliotarthur** [comment]
Yeah, those bullets should be removed. Also, the bullets underneath the professor image should be formatted to reflect the pattern we've created for this type of content. Remove the semi-colons too.

![image](https://cloud.githubusercontent.com/assets/12611145/17629912/e5a4b0b0-608a-11e6-8fd7-08865b81e0f3.png)

**Comment by kpettinga** [comment]
@elliotarthur @Jessdwilson this is fixed.

In terms of elliot's second note about formatting info for people, ive aligned it with the mockup. The name and title, however, are already present in the page title and subtitle, so on single pages for people, i don't think its necessary in the sidebar. 

![screencapture-cgu-local-people-david-luis-brown-1473321831409](https://cloud.githubusercontent.com/assets/1746410/18341724/87cb4962-75d5-11e6-9fe7-47d08bdb54e9.png)
