### ISSUE TITLE
Why CGU: Statistics animations

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/cgu#78]
@kpettinga I was hoping we could implement something along the lines of how this site introduces its stats and figures - http://www.navigatingresponsibly.dk/

I think it'll really make this page engaging and add a lot of sophistication to the university stats.

Let me know if this is something we can work towards.

**Comment by davekellam** [comment]
@elliotarthur it would be helpful here to describe exactly (or in more precise terms) what you're looking to have implemented here.

**Comment by kpettinga** [comment]
@davekellam, @elliotarthur and I have discussed this in the past and I think I know what he's looking for. It's basically the scrolling effect of how the numbers get displayed. Kind of like an old fashioned stock ticker or transit schedule.

**Comment by houmym** [comment]
Hey @kpettinga the illustrations on the Why CGU page seem to shake up and down as you scroll through the statistics.

I am also thinking that maybe they should not be fixed as you scroll, as they lose their connection with the statistics they relate to.

**Comment by kpettinga** [comment]
@houmym the shaking is probably due to bad frame rates. It might be too much for the browser to handle and/or we need to see if any optimizing can be done. Unfixing the graphics would certainly help the situation.

**Comment by holliscooper-cgu** [comment]
@kpettinga We've noticed that the clock animation seems to break often: it doesn't work at all, or doesn't work on page reload, or the hands don't show at all ... 

If it isn't an easy fix, we are okay with removing the animation on the clock hands.

Also, can you reduce the initial empty yellow space above the animations by 1/2 - 2/3rds? The animations are totally hidden below the fold. If there's any way to reduce the empty space between the animations a little, that would be great, too, but if it needs to be that way for it to function, that's fine.

**Comment by kpettinga** [comment]
@holliscooper-cgu Unfortunately that's not an easy fix so I've taken away the animation for the clocktower and it now uses the default "bounce" animation (like the torch and city). That should have a consistent behaviour. I've also decreased the height of each section to be 70% of the page height so that the graphics/stats get a little closer to the top.
