### ISSUE TITLE
School Specific Footers

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/cgu#8]

**Comment by kpettinga** [comment]
Hey @davekellam I think we're going to need a way for them to create footer navs for each school. Right now you can see in footer.php that ive just hard coded some things but we'll most likely need to make this dynamic. Can you brainstorm some ways they can create a series of footer menus for each school?

**Comment by davekellam** [comment]
Been thinking on this one, not sure if there's a way to do this with custom fields, but there might be some sort of approach. One option would be to use the WordPress nav menus, but it does involve explicitly creating them with code (so coding would be involved if they renamed a school, or added a new one). Do you think the given layout could be achieved with on WP nav menu? If not, it might be better to create some sort of custom field solution.

**Comment by davekellam** [comment]
I've added in nav menus for the five schools, and added it to the footer template. Passing over to you for styling.

**Comment by davekellam** [comment]
I also added in another footer menu for the main footer.
