### ISSUE TITLE
Why CGU: Editable text

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#80]
@kpettinga CGU may need to edit the stat text on the animated Why CGU page, can you make this editable in Wordpress? They also want to change the nomenclature for degrees

Specific Edits:
- [x] Everywhere it says "graduate degrees" in the infographic, it should say "Doctoral Degrees"
- [x] "Master Degrees" and "Masters Degrees" should be "Master's Degrees" 
- [x] Under "Meet Our Faculty" section, it should say "Tenured or Tenure-Track" not "Tenured-Track"

**Comment by davekellam** [comment]
Editable text should be doable, it was probably hard-coded as an initial first pass. 

@Jessdwilson by "change nomenclature for degrees" do you mean specific to this page, or is it a broader site issue?

**Comment by davekellam** [comment]
@Jessdwilson Ahh, I see about the degree nomenclature now from #64. I'll close that issue out as a duplicate

> on the Why CGU page, everywhere it says "graduate degrees" in the infographic it should say "doctoral degrees"

> "Master Degrees" and "Masters Degrees" should be "Master's Degrees"

> under "Meet Our Faculty" it should say "Tenured or Tenure-Track" not "Tenured-Track"

**Comment by kpettinga** [comment]
@Jessdwilson these fields are now editable in the backend.
