### ISSUE TITLE
Carousel module not appearing correctly

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#82]
@kpettinga Hollis found that the carousel on the MFA in Art program page is not appearing correctly, she is viewing this in Chrome (see attached). 

![art-module-chrome](https://cloud.githubusercontent.com/assets/1680051/17939490/e3f2ba10-69f8-11e6-9d73-3914923bf4c7.jpg)

However, when I view the same carousel in Chrome it looks fine
![screen shot 2016-08-24 at 12 45 25 pm](https://cloud.githubusercontent.com/assets/1680051/17939500/f1ce0e82-69f8-11e6-975a-75ccea8e2b5f.png)

**Comment by kpettinga** [comment]
hey @Jessdwilson could you confirm with her if she's on Windows or Mac and what version of Chrome it is?

**Comment by Jessdwilson** [comment]
@kpettinga Hollis said she checked again and it's working for her so I'll close this out

**Comment by kpettinga** [comment]
Cool, probably just a cache issue
