### ISSUE TITLE
Events: event_type taxo archive should emulate events template

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/cgu#86]
Hey @davekellam,

CGU wants to have an additional "Event Type" taxonomy for events. This is what they'll use for terms like "Admissions", "Lectures", "Alumni" etc. The default Event Categories taxo will be used for terms like "Arts", "Business", etc (loosely based on areas of study maybe?).

Anyways, when you go to an Event Category archive page, you're brought to something like http://cgu.wpengine/events/category/arts/ which actually seems to be a post type archive template. I'd like for Event Type archive pages to have the same behavior but instead it brings me to a taxonomy archive template (understandably). The nice thing about the post type archive template is that it will still let you filter by day/week/month so you can go to a page like http://cgu.wpengine/events/category/arts/month. 

Do you know what the events calendar plugin does under the hood to make that happen? Wondering if its possible for our new Event Type taxo to also use the post type archive template.

**Comment by davekellam** [comment]
Spent the afternoon digging around in the codebase. At this point I'm pretty sure that you can't extend the templates to an additional taxonomy. The main event categories seemed to be pretty embedded within the system. Obviously we can relate additional taxonomies (like _school and event_type) but we don't seem to be able to get the same template treatment (unless I'm missing something). I can see it being a roadmap option for them... looks like there's some capacity to override the the default name/slug.

So, our best bet moving forward is probably to make the event type taxonomy mirror the categories as close as possible. The one thing that will probably get lost is the ability to deep link to a pre-sorted option like type/week. We'll see as we progress deeper into trying to emulate the appearance.

**Comment by kpettinga** [comment]
Thanks @davekellam. I'll try to put together an archive template that mirrors the calendar as closely as possible.

**Comment by davekellam** [comment]
Getting closer to something functional. It looks kinda like it supposed to, but doesn't work entirely.

Figured out that some scripts needed to be enqueued and did a rough copy of the month template. It should show the right events for the `event_type` in that month, but it doesn't do some of the sorting/filter stuff properly yet. I imagine the data needs to get setup in some fashion behind the scenes. It's not the easiest plugin to extend without really digging into how it's built (probably not a bad thing to understand).

**Comment by kpettinga** [comment]
Hey @davekellam any progress on this?

**Comment by kpettinga** [comment]
We are not able to fully emulate an archive page for custom taxonomies on events. Users can, however, still filter events by Event Type on the calendar pages.
