### ISSUE TITLE
News & Events link View Calendar

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#87]
@kpettinga on the News & Events landing page, how would I link the "view calendar" button to the events calendar page? 
![screen shot 2016-09-01 at 11 04 52 am](https://cloud.githubusercontent.com/assets/1680051/18172593/0e2d14ec-7034-11e6-987c-035f38080eac.png)

**Comment by kpettinga** [comment]
It's not editable but I've fixed the link to always point to the calendar.
