### ISSUE TITLE
Navigation: grandchild page navigation

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/cgu#89]
From Andrea:

Who adds the child page navigation to Resources & Support:http://cgu.wpengine.com/academics/resources-support/?

This is something we need to address. We have a [child_pages] shortcode which will automatically grab all child pages of the current page and create a tabbed nav with all of them listed. This is a problem, however, when a page has too many child pages. The tabbed nav design does not accommodate a large number of items. We anticipated this happening in the early stages of the design, and think we need to consider a sidebar approach similar to the admissions pages.

**Comment by kpettinga** [comment]
Possible solution, sidebar?

**Comment by kpettinga** [comment]
@Jessdwilson this is a more extensible solution:

![image](https://cloud.githubusercontent.com/assets/1746410/18431758/a3c63696-7908-11e6-9df7-8ce05020dd40.png)

Before continuing, can we confirm with the client that this is a direction they'd like to pursue?

**Comment by Jessdwilson** [comment]
@kpettinga just letting you know Andrea is going to give them some more thought. She is concerned about the inconsistency of the child navigation between pages (sidebar vs. sub nav). She thinks it would be helpful to have some rules or guidance for when a sidebar is used and when the sub nav is used

**Comment by kpettinga** [comment]
Understandable. Basically I see it as the sub-nav will handle child pages and the sidebar will handle grand-child pages. So there would never be an instance when a sidebar is visible and a sub-nav is not. The sidebar would never take the place of the sub-nav.

It may be easier to solve this by discussing in person. I'd be happy to jump on a call with you and Andrea if it would help.

cc: @elliotarthur @jalbertgagnier

**Comment by Jessdwilson** [comment]
thanks @kpettinga I discussed with David and with Andrea and they both agree this makes sense. I'll need to go through the sitemap and ensure we're consistent with the use of sub-navs and sidebars on the site.
