### ISSUE TITLE
Departments format on school landing page

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#92]
@kpettinga is there a way to organize the departments in columns on the school landing page similar to how we have in the design mockup? 

![screen shot 2016-09-06 at 10 47 29 am](https://cloud.githubusercontent.com/assets/1680051/18278242/5cc21f46-741f-11e6-987e-972795e66092.png)

**Comment by kpettinga** [comment]
@Jessdwilson yes, the widths got messed up in some recent CSS changes. Thanks for spotting.
