### ISSUE TITLE
Schools: header logos appear low res

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#95]
Also, can the Claremont Graduate University portion be clickable to the CGU homepage?

![screen shot 2016-09-09 at 12 38 23 pm](https://cloud.githubusercontent.com/assets/1680051/18394939/560d15d0-768a-11e6-9122-7e61942d631e.png)

**Comment by kpettinga** [comment]
@Jessdwilson this may just be because of the image getting scaled down from its original size. Can you check it on a retina display and confirm if the blury-ness is still there?

**Comment by Jessdwilson** [comment]
@kpettinga it does look perfect on retina screens
