### ISSUE TITLE
Why CGU Meet Our Faculty link removed

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#98]
@kpettinga on the Why CGU and WHY CGU > 10 Reasons page the Meet Our Faculty button should be removed. I deleted the text in the CTA sections but I see that doesn't remove the button from the site 

![screen shot 2016-09-12 at 1 22 00 pm](https://cloud.githubusercontent.com/assets/1680051/18445529/0b5a2ff0-78ec-11e6-96c9-636134d77ee1.png)

![screen shot 2016-09-12 at 1 20 37 pm](https://cloud.githubusercontent.com/assets/1680051/18445543/16d1601a-78ec-11e6-9692-0d8403be5475.png)

**Comment by davekellam** [comment]
I got this @Jessdwilson, should be fixed now. We just needed a bit of error trapping in case those fields hadn't been filled out.

**Comment by Jessdwilson** [comment]
thanks! @davekellam 

Can we also remove the Meet Our Faculty link on the main Why CGU animated page? 
![screen shot 2016-09-13 at 3 06 01 pm](https://cloud.githubusercontent.com/assets/1680051/18487547/b398cabe-79c3-11e6-9dbe-2e7f09317c41.png)

**Comment by davekellam** [comment]
I’m guessing it’s a similar issue that “no entry” wasn’t taken into account.

Question here, should I be removing the CTA option from the backend? With the previous one, I added a check to make sure there was content/link for the CTA. Should I leave the option in, or remove entirely?

-- 
Dave Kellam
dave@objectivesubject.com

On September 13, 2016 at 3:06:56 PM, Jessdwilson (notifications@github.com) wrote:

thanks! @davekellam

Can we also remove the Meet Our Faculty link on the main Why CGU animated page?

**Comment by Jessdwilson** [comment]
@davekellam it would probably be a good idea to keep the CTA option, in case they wish to include a link at a later date

**Comment by davekellam** [comment]
Ahh, the link/button/cta was actually hardcoded in this instance. Should be gone now.
