### ISSUE TITLE
Top nav not displaying correctly in Firefox

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#99]
@kpettinga In Firefox, there's a 2-logo overlay, and the spacing between the utility nav and main nav is collapsed (see screenshot) 

![top-nav-firefox](https://cloud.githubusercontent.com/assets/1680051/18650229/f10bf704-7e91-11e6-9b0f-3719c799ca67.JPG)

**Comment by kpettinga** [comment]
@Jessdwilson I'm sure this is a caching issue. can you confirm with the client if it's still an issue? Going to close for now but feel free to re-open.
